Repository zama-ai/tfhe-rs, pull requests merged in 2023-09, with the labels that each got.

#521 feat(integer): be smarter about parallel carry propagation usage
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/neg.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
Labels: cla-signed

#513 fix(integer): add assert on scalar bits in scalar_div
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed

#522 chore(wopbs): rework the inner part of WopLUTBase to be easier to use
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/shortint/engine/wopbs/mod.rs
  tfhe/src/shortint/wopbs/mod.rs
Labels: cla-signed

#519 chore(ci): add multiplier to get effective pbs throughput value
  ci/benchmark_parser.py
Labels: cla-signed, ci

#493 chore(bench): add new parameter sets to bench
  tfhe/benches/boolean/bench.rs
Labels: cla-signed

#508 fix(integer): make trim_radix_msb handle dirty inputs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed

#520 chore(bench): add 128 and 256 bit sizes to multi-bit benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, ci

#530 chore(ci): add clippy target for trivium application
  Makefile
Labels: cla-signed, ci

#505 feat(fft): use monomial fft for multibit pbs
  tfhe/Cargo.toml
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/mod.rs
Labels: cla-signed

#527 chore(c_api): mark some functions manipulating pointers as unsafe
  tfhe/src/c_api/utils.rs
Labels: cla-signed

#529 feat(core): add parallel LWE PFPKS and LWE KS
  tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/misc.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
  tfhe/src/core_crypto/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/entities/lwe_private_functional_packing_keyswitch_key.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
Labels: cla-signed

#541 chore(trivium): fix module inception
  apps/trivium/src/trivium/mod.rs
  apps/trivium/src/trivium/trivium_bool.rs
Labels: cla-signed

#524 chore(hlapi): move integrations tests into src dir
  tfhe/src/high_level_api/shortints/tests.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/high_level_api/tests/test_fhe_number_ops.rs
  tfhe/tests/test_integers.rs
  tfhe/tests/test_shortints.rs
Labels: cla-signed

#500 docs(readme): fix typos
  README.md
Labels: cla-signed

#544 chore(ci): avoid running full suite several times on approval
  .github/workflows/trigger_aws_tests_on_pr.yml
Labels: cla-signed, ci, approved

#545 chore(ci): fix trivium test recipes
  Makefile
Labels: cla-signed, ci

#535 smart ops always take mut inputs
  tfhe/src/c_api/shortint/server_key/comp_op.rs
  tfhe/src/high_level_api/shortints/server_key.rs
  tfhe/src/integer/server_key/crt/mul_crt.rs
  tfhe/src/integer/server_key/crt_parallel/mul_crt.rs
  tfhe/src/integer/server_key/radix/mul.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
  tfhe/src/shortint/engine/server_side/comp_op.rs
  tfhe/src/shortint/server_key/comp_op.rs
  tfhe/src/shortint/server_key/tests/shortint.rs
Labels: cla-signed

#547 chore(ci): notify slack about coverage only in case of failure
  .github/workflows/code_coverage.yml
Labels: cla-signed, ci, approved

#525 chore(tfhe): remove unused deps, drop once_cell, enable paste when needed
  tfhe/Cargo.toml
  tfhe/src/core_crypto/fft_impl/fft128/math/fft/mod.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/mod.rs
  tfhe/src/integer/mod.rs
  tfhe/src/keycache/mod.rs
Labels: cla-signed

#550 chore(ci): add boolean layer to code coverage
  .github/workflows/code_coverage.yml
  Makefile
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/src/boolean/keycache.rs
  tfhe/src/boolean/mod.rs
  tfhe/src/boolean/parameters/mod.rs
  tfhe/src/boolean/server_key/tests.rs
Labels: cla-signed, ci, approved

#556 chore(core): remove unsafe new_unchecked on CiphertextModulus
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/commons/ciphertext_modulus.rs
Labels: cla-signed, approved

#558 chore(ci): add compact keys to parameters security checks
  ci/lattice_estimator.sage
  tfhe/examples/utilities/params_to_file.rs
Labels: cla-signed, ci

#555 feat(core): replace unsafe simd intrinsics
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
Labels: cla-signed, approved

#565 fix(csprng): enable target_feature attributes for functions using simd intrinsics
  concrete-csprng/src/generators/implem/aarch64/block_cipher.rs
  concrete-csprng/src/generators/implem/aesni/block_cipher.rs
  concrete-csprng/src/seeders/implem/rdseed.rs
Labels: cla-signed

#552 feat(core): add GLWE linear algebra primitives
  tfhe/src/core_crypto/algorithms/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/mod.rs
  tfhe/src/core_crypto/algorithms/slice_algorithms.rs
  tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/entities/cleartext.rs
Labels: cla-signed, approved

#507 feat(integer): add unchecked implemetation of signed ciphertext
  tfhe/Cargo.toml
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/core_crypto/commons/numeric/mod.rs
  tfhe/src/core_crypto/commons/numeric/signed.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
  tfhe/src/integer/bigint/algorithms.rs
  tfhe/src/integer/bigint/i256.rs
  tfhe/src/integer/bigint/i512.rs
  tfhe/src/integer/bigint/mod.rs
  tfhe/src/integer/bigint/static_signed.rs
  tfhe/src/integer/bigint/static_unsigned.rs
  tfhe/src/integer/bigint/u256.rs
  tfhe/src/integer/bigint/u512.rs
  tfhe/src/integer/block_decomposition.rs
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix/bitwise_op.rs
  tfhe/src/integer/server_key/radix/comparison.rs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix/mul.rs
  tfhe/src/integer/server_key/radix/neg.rs
  tfhe/src/integer/server_key/radix/scalar_mul.rs
  tfhe/src/integer/server_key/radix/scalar_sub.rs
  tfhe/src/integer/server_key/radix/shift.rs
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/abs.rs
  tfhe/src/integer/server_key/radix_parallel/bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/mul.rs
  tfhe/src/integer/server_key/radix_parallel/neg.rs
  tfhe/src/integer/server_key/radix_parallel/rotate.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/shift.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#570 chore(ci): print security level in parameters check
  .github/workflows/parameters_check.yml
  ci/lattice_estimator.sage
Labels: cla-signed, ci, approved

#569 fix(integer): only propagate if necessary after trimming
  tfhe/src/integer/server_key/radix/mod.rs
Labels: cla-signed, approved

#571 chore(docs): fix docstring about encryption key choice
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#567 fix(integer): replace unnecessary unsafe code in integer shift/add
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/shift.rs
Labels: cla-signed, approved

#568 chore(deps): update cargo dependencies
  apps/trivium/Cargo.toml
  concrete-csprng/Cargo.toml
  tasks/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#578 fix(integer): fix signed div_rem test for 0/0
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#553 feat(core): add parallel variant of extract_lwe_sample_from_glwe
  tfhe/src/core_crypto/algorithms/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
Labels: cla-signed, approved

#574 chore(integer): add default signed bitand/or/xor tests
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#517 feat(integer): improve scalar_mul
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mul.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
Labels: cla-signed, approved

#585 feat(core): optimize monic polynomial operations in pbs
  tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
Labels: cla-signed, approved

#581 fix(integer): is_neg/sub/add possible
  tfhe/docs/fine_grained_api/integer/operations.md
  tfhe/src/integer/server_key/radix/add.rs
  tfhe/src/integer/server_key/radix/neg.rs
  tfhe/src/integer/server_key/radix/sub.rs
Labels: cla-signed, approved

#587 chore(hlapi): remove unused keychain_member from macro
  tfhe/src/high_level_api/integers/keys.rs
  tfhe/src/high_level_api/integers/types/static_.rs
  tfhe/src/high_level_api/mod.rs
Labels: cla-signed, approved

#588 fix(integer): StaticSignedBigInt right shift
  tfhe/src/integer/bigint/algorithms.rs
  tfhe/src/integer/bigint/i256.rs
Labels: cla-signed, approved

#586 chore(core): add utils to test noise distribution for power of 2 q
  tfhe/src/core_crypto/algorithms/misc.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/commons/mod.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
Labels: cla-signed, approved

#557 chore(integer): make tests work with different ServerKey
  tfhe/src/integer/client_key/radix.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#591 chore(integer): impl RecomposableSignedInteger for StaticSignedBigInt
  tfhe/src/integer/bigint/static_signed.rs
  tfhe/src/integer/block_decomposition.rs
  tfhe/src/integer/client_key/mod.rs
Labels: cla-signed, approved

#592 feat(integer): add sign extend fn for SignedRadixCiphertext
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
Labels: cla-signed, approved

#594 feat(integer): make compact ciphertext compatible with signed
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/public_key/compact.rs
Labels: cla-signed, approved

#597 chore(csprng): the stabilized aarch64 intrisics were in Rust 1.72
  concrete-csprng/Cargo.toml
Labels: cla-signed, approved
