Repository zama-ai/tfhe-rs, pull requests merged in 2023-11, with the labels that each got.

#669 chore(ci): test examples and apps in the ci
  .github/workflows/aws_tfhe_tests.yml
Labels: cla-signed, ci, approved

#670 test(hlapi): test base and compressed integer conformance
  tfhe/src/core_crypto/entities/lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/integers/types/compact.rs
  tfhe/src/high_level_api/integers/types/compressed.rs
Labels: cla-signed

#672 chore(tfhe): bump version to 0.5.0
  tfhe/Cargo.toml
  tfhe/docs/core_crypto/tutorial.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/how_to/serialization.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
Labels: cla-signed, approved

#655 Boolean value wrapper
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/examples/dark_market/improved_parallel_fhe.rs
  tfhe/examples/regex_engine/execution.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/integer/ciphertext/boolean_value.rs
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/client_key/mod.rs
  tfhe/src/integer/client_key/radix.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix/comparison.rs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed

#675 chore(doc): update a slightly wrong docstring
  tfhe/src/core_crypto/algorithms/lwe_packing_keyswitch.rs
Labels: cla-signed, approved

#668 Generic int over Id
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/parameters.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/integers/types/compact.rs
  tfhe/src/high_level_api/integers/types/compressed.rs
  tfhe/src/high_level_api/integers/types/static_.rs
  tfhe/src/high_level_api/internal_traits.rs
Labels: cla-signed, approved

#677 build(core_crypto): silence dead code warnings on test utils
  tfhe/src/core_crypto/entities/lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
Labels: cla-signed, approved

#682 chore(tfhe): fix required features for the generate_test_keys util
  tfhe/Cargo.toml
Labels: cla-signed, approved

#680 fix(integer): fix signed_overflowing_sub using trivial 0
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
  tfhe/src/shortint/engine/server_side/neg.rs
Labels: cla-signed, approved

#674 feat(integer): add unsigned_oveflowing_add
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/neg.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#686 chore(ci): fix build on main following several big merges
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved

#679 chore(core): fix noise generation which could overflow the custom modulus
  tfhe/src/core_crypto/algorithms/misc.rs
  tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/test/lwe_compact_public_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/commons/generators/encryption/mod.rs
  tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
  tfhe/src/core_crypto/commons/math/random/gaussian.rs
  tfhe/src/core_crypto/commons/math/random/generator.rs
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/commons/math/random/tests.rs
  tfhe/src/core_crypto/commons/math/torus/mod.rs
  tfhe/src/core_crypto/commons/mod.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
  tfhe/src/core_crypto/entities/lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
Labels: cla-signed

#691 chore(ci): refactor integer script and skip div and rem preferring div_rem
  scripts/integer-tests.sh
Labels: cla-signed, approved

#689 chore(integer): make oveflowing_add/sub return BooleanBlock
  tfhe/src/integer/ciphertext/boolean_value.rs
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#695 feat(integer): avoid un-necessary computations in mul params 1_X
  tfhe/src/integer/server_key/radix_parallel/mul.rs
Labels: cla-signed, approved

#694 fix(integer): fix inner index computation in sum
  tfhe/src/integer/server_key/radix_parallel/add.rs
Labels: cla-signed, approved

#696 chore(shortint): fix typo for NoiseLevel variant UNKNOWN
  tfhe/src/shortint/ciphertext/mod.rs
Labels: cla-signed, approved

#697 chore(ci): change benchmark aws ec2 machine type
  ci/ec2_products_cost.json
  ci/slab.toml
Labels: cla-signed, ci, approved

#664 chore(ci): add core_crypto layer to code coverage
  .github/workflows/code_coverage.yml
  Makefile
  tfhe/src/core_crypto/algorithms/mod.rs
  tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/test/lwe_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_compact_public_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/fft_impl/common.rs
  tfhe/src/core_crypto/fft_impl/fft128/crypto/tests.rs
  tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/tests.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/tests.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
  tfhe/src/core_crypto/keycache.rs
  tfhe/src/core_crypto/mod.rs
  tfhe/src/keycache/mod.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/server_key/tests/noise_level.rs
Labels: cla-signed, ci, approved

#628 feat(core): specialize keyswitch implementation for small scalar values
  tfhe/Cargo.toml
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/src/core_crypto/algorithms/slice_algorithms.rs
Labels: cla-signed, approved

#705 chore(core): change the test LUT to apply the identity function
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/fft_impl/common.rs
Labels: cla-signed, approved

#708 chore(ci): update Makefile for semver trick
  Makefile
Labels: cla-signed

#690 feat(tfhe): add LWE encryption with non power of 2 moduli
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/seeded_lwe_ciphertext_decompression.rs
  tfhe/src/core_crypto/algorithms/seeded_lwe_ciphertext_list_decompression.rs
  tfhe/src/core_crypto/algorithms/slice_algorithms.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/commons/ciphertext_modulus.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
Labels: cla-signed, approved

#710 Am/chore/fix clippy trivium
  Makefile
Labels: cla-signed, approved

#707 chore(ci): fix a command naming issue for the CI
  .github/workflows/trigger_aws_tests_on_pr.yml
  ci/slab.toml
Labels: cla-signed, approved

#712 chore(shortint): remove doctest as tests as it is confirmed they fail
  tfhe/src/shortint/wopbs/test.rs
Labels: cla-signed

#714 chore(ci): .gitignore was ignoring all files/directories names keys
  .gitignore
Labels: cla-signed, approved

#716 chore(ci): add aws ec2 fallback profile for cpu tests
  ci/slab.toml
Labels: cla-signed, ci, approved

#718 chore(ci): fix doctest by using parameters with enough precision
  tfhe/src/shortint/wopbs/mod.rs
Labels: cla-signed, approved
