Repository zama-ai/tfhe-rs, pull requests merged in 2023-10, with the labels that each got.

#598 fix(integer): clean output quotient of division
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
Labels: cla-signed, approved

#596 feat(integer): add default signed_scalar div/rem/div_rem
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#595 feat(integer): add encryption of signed radix via compressed pk
  tfhe/src/integer/public_key/compressed.rs
Labels: cla-signed, approved

#599 feat(hlapi): tie scalar ops with corresponding clear type
  tfhe/src/high_level_api/integers/types/base.rs
Labels: cla-signed, approved

#600 refactor(core): remove a copy in the external product
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/mod.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/tests.rs
Labels: cla-signed, approved

#601 chore(hlapi): add InnerCiphertext type to integer wrapper
  tfhe/src/high_level_api/integers/client_key.rs
  tfhe/src/high_level_api/integers/keys.rs
  tfhe/src/high_level_api/integers/parameters.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/integers/types/compressed.rs
  tfhe/src/high_level_api/integers/types/static_.rs
Labels: cla-signed, approved

#606 chore(test): fix incorrect memory buffer size in wopbs core_crypto tests
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/mod.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
Labels: cla-signed, approved

#605 feat(hlapi): add FheInt{8,16,32,64,128,256}
  tfhe/src/high_level_api/errors.rs
  tfhe/src/high_level_api/integers/client_key.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/tests_signed.rs
  tfhe/src/high_level_api/integers/tests_unsigned.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/integers/types/mod.rs
  tfhe/src/high_level_api/integers/types/static_.rs
  tfhe/src/high_level_api/mod.rs
Labels: cla-signed, approved

#610 feat(wasm): add FheInt support
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
  tfhe/src/high_level_api/integers/client_key.rs
  tfhe/src/integer/public_key/standard.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
Labels: cla-signed, approved

#611 chore: fix typos
  apps/trivium/src/kreyvium/kreyvium_byte.rs
  apps/trivium/src/trivium/trivium_byte.rs
  tfhe/docs/fine_grained_api/quick_start.md
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
  tfhe/src/safe_deserialization.rs
Labels: cla-signed, approved

#609 feat(integer): add unsigned_overflowing_sub
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#617 fix(integer): remove remove if_then_else assert
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
Labels: cla-signed, approved

#620 fix(integer): handle trivial ct in if_then_else
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved

#624 test(core): use polynomial tests from NTT PR
  tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
Labels: cla-signed, approved

#625 refactor(shortint): update compact parameters
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/parameters_compact_pk.rs
  tfhe/src/shortint/server_key/tests/shortint_compact_pk.rs
Labels: cla-signed, approved

#619 feat(integer): speed-up division by using overflowing_sub
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
Labels: cla-signed, approved

#633 feat(integer): map cmux to if_then_else
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
Labels: cla-signed, approved

#580 chore(integer): add tests for default signed rotations/shifts
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#579 fix(integer): better estimate which algorithm to choose
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
Labels: cla-signed, approved

#613 doc: updating doc for v0.4
  tfhe/docs/SUMMARY.md
  tfhe/docs/fine_grained_api/integer/operations.md
  tfhe/docs/fine_grained_api/integer/readme.md
  tfhe/docs/fine_grained_api/shortint/operations.md
  tfhe/docs/fine_grained_api/shortint/readme.md
  tfhe/docs/getting_started/benchmarks.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/operations.md
  tfhe/docs/how_to/rust_configuration.md
Labels: cla-signed

#604 chore(ci): enable AVX512 for integer and multi bit integer tests
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_bit_tests.yml
  Makefile
  scripts/integer-tests.sh
Labels: cla-signed, approved

#623 fix(crt): fix mul for non symmetrical parameters
  tfhe/src/integer/server_key/crt/mul_crt.rs
  tfhe/src/integer/server_key/crt/tests.rs
  tfhe/src/integer/server_key/crt_parallel/add_crt.rs
  tfhe/src/integer/server_key/crt_parallel/mod.rs
  tfhe/src/integer/server_key/crt_parallel/mul_crt.rs
  tfhe/src/integer/server_key/crt_parallel/tests.rs
Labels: cla-signed, approved

#640 chore(ci): tell nvm to use node version 20 in wasm parallel tests
  Makefile
  docker/Dockerfile.wasm_tests
Labels: cla-signed, approved

#637 fix(integer): fix unsigned_overflowing_sub on trivials
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved

#631 chore(doc): encourage users to use dedicated keys to Radix or CRT
  tfhe/src/integer/mod.rs
Labels: cla-signed, approved

#603 refactor(core): use avx512 intrinsics when available for data conversions
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
Labels: cla-signed

#636 Nuke doctests LTO
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/m1_tests.yml
  scripts/integer-tests.sh
Labels: cla-signed, approved

#645 chore(ci): enable integer multi bit tests on M1
  .github/workflows/m1_tests.yml
Labels: approved

#653 chore(integer): remove empty where clause
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix/mod.rs
Labels: cla-signed, approved

#602 chore(integer): move comparator test out of it
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
Labels: cla-signed, approved

#638 chore(doc): replace some ^ which could be interpreted as xor not pow
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#656 feat(integer): better handle trivial 0 blocks from LHS
  tfhe/src/integer/server_key/radix_parallel/mul.rs
Labels: cla-signed, approved

#657 chore(integer): use Arc<ServerKey> for executor
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#654 fix(integer): fix worst case noise growth in encrypted shifts
  tfhe/src/integer/server_key/radix_parallel/bit_extractor.rs
  tfhe/src/integer/server_key/radix_parallel/shift.rs
Labels: cla-signed

#662 refactor(hlapi): Remove shortint support from HLAPI
  tfhe/docs/getting_started/operations.md
  tfhe/src/high_level_api/config.rs
  tfhe/src/high_level_api/details.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/keys/client.rs
  tfhe/src/high_level_api/keys/mod.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/shortints/client_key.rs
  tfhe/src/high_level_api/shortints/keys.rs
  tfhe/src/high_level_api/shortints/mod.rs
  tfhe/src/high_level_api/shortints/parameters.rs
  tfhe/src/high_level_api/shortints/public_key.rs
  tfhe/src/high_level_api/shortints/server_key.rs
  tfhe/src/high_level_api/shortints/tests.rs
  tfhe/src/high_level_api/shortints/types/base.rs
  tfhe/src/high_level_api/shortints/types/compressed.rs
  tfhe/src/high_level_api/shortints/types/mod.rs
  tfhe/src/high_level_api/shortints/types/static_.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/high_level_api/tests/test_fhe_number_ops.rs
  tfhe/src/lib.rs
Labels: cla-signed, approved
