Repository zama-ai/tfhe-rs, pull requests merged in 2024-12, with the labels that each got.

#1835 refactor(shortint): use view -> decompress to simplify key decompression
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/server_key/compressed.rs
Labels: cla-signed, approved

#1831 fix: clean noise of skipped block in full_propagate_parallelized
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#1844 chore: slightly simpler test code for distribution tests
  tfhe/src/core_crypto/commons/math/random/tests.rs
Labels: cla-signed, approved

#1845 refactor!: use strong types for outputs of DispersionParameters trait fns
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_keyswitch_noise.rs
  tfhe/src/core_crypto/commons/dispersion.rs
  tfhe/src/core_crypto/commons/math/random/gaussian.rs
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/commons/mod.rs
Labels: cla-signed, approved

#1847 chore(gpu): reduce throughput integer bench time
  .github/workflows/benchmark_gpu_integer_common.yml
  tfhe/benches/integer/bench.rs
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#1849 fix(tfhe-lints): linter was not run, missing compile time env var
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/shortint/wopbs/mod.rs
  utils/cargo-tfhe-lints-inner/src/main.rs
  utils/cargo-tfhe-lints/src/main.rs
Labels: cla-signed, approved

#1834 feat(gpu): add gpu array type in hl api
  tfhe/src/high_level_api/array/gpu/booleans.rs
  tfhe/src/high_level_api/array/gpu/integers.rs
  tfhe/src/high_level_api/array/gpu/mod.rs
  tfhe/src/high_level_api/array/mod.rs
  tfhe/src/high_level_api/array/tests/booleans.rs
  tfhe/src/high_level_api/array/tests/mod.rs
  tfhe/src/high_level_api/array/tests/signed.rs
  tfhe/src/high_level_api/array/tests/unsigned.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/lib.rs
Labels: cla-signed, approved

#1853 chore(docs): fix the bench table
  tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
Labels: cla-signed, approved

#1854 chore(docs): fix the bench table
  tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
Labels: cla-signed, approved

#1852 chore(ci): check more parameters set on lattice estimator
  ci/lattice_estimator.sage
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/examples/utilities/params_to_file.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/multi_bit/gaussian/mod.rs
Labels: cla-signed, ci, approved

#1863 chore(ci): use composite action to setup hyperstack instance
  .github/actions/hyperstack_setup/action.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, ci, approved

#1861 fix(gpu): fix equal
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
Labels: cla-signed, approved

#1862 chore(gpu): remove stream sync in broadcast lut
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#1864 fix(gpu): fix scalar ne
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
Labels: cla-signed, approved

#1865 doc(gpu): add an example to use arrays on GPU
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed, approved

#1873 chore(gpu): add sxm5 vm target
  .github/workflows/benchmark_gpu_erc20.yml
  .github/workflows/benchmark_gpu_integer.yml
  ci/slab.toml
Labels: cla-signed, approved

#1786 chore(hlapi): stabilize FheTypes
  tfhe/Cargo.toml
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/high_level_api/mod.rs
Labels: cla-signed, approved

#1871 Al/rework difference check
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
Labels: cla-signed

#1866 chore: remove aliases for gaussian parameters for compact PK
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/docs/fundamentals/compress.md
  tfhe/docs/guides/js_on_wasm_api.md
  tfhe/docs/guides/public_key.md
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/examples/utilities/hlapi_compact_pk_ct_sizes.rs
  tfhe/examples/utilities/wasm_benchmarks_parser.rs
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/src/c_api/shortint/parameters.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/public_key/tests.rs
  tfhe/src/js_on_wasm_api/shortint.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/classic/compact_pk/mod.rs
  tfhe/src/shortint/parameters/coverage_parameters.rs
  tfhe/src/shortint/parameters/key_switching/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/server_key/tests/shortint_compact_pk.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1869 chore(all): remove the dependency to lazy_static
  tasks/Cargo.toml
  tasks/src/main.rs
  tfhe/Cargo.toml
  tfhe/examples/regex_engine/engine.rs
  tfhe/src/boolean/keycache.rs
  tfhe/src/core_crypto/keycache.rs
  tfhe/src/integer/keycache.rs
  tfhe/src/shortint/keycache.rs
Labels: cla-signed, approved

#1878 chore(gpu): make artifact name unique across different machines
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
Labels: cla-signed, approved

#1874 chore: fix clippy lints after toolchain update
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
Labels: cla-signed, approved

#1867 chore(gpu): rework select to avoid using local streams
  .github/workflows/benchmark_gpu_erc20.yml
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
Labels: cla-signed, approved

#1879 doc(shortint): add some clarification about shortint size
  tfhe/docs/references/fine-grained-apis/shortint/README.md
Labels: cla-signed, approved

#1880 fix(gpu): fix single gpu on device other than 0
  tfhe/src/core_crypto/gpu/slice.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#1881 Al/fix ct degree noise
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/cmux.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
Labels: cla-signed, approved

#1884 fix(gpu): fix lut size in are_all_comparison_blocks_true
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#1888 fix(gpu): fix noise level calculation in full propagation
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#1894 chore(ci): verify triggering actor on pull request from fork
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/check_triggering_actor.yml
Labels: cla-signed, ci, approved

#1889 chore(gpu): rework single carry prop to avoid using local streams
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#1897 chore(gpu): add inputs to erc20 throughput bench with multiple GPUs
  tfhe/benches/high_level_api/erc20.rs
Labels: cla-signed

#1885 feat(gpu): implement subarray search
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_vector_find.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/vector_find.rs
Labels: cla-signed

#1899 chore(deps): bump zama-ai/slab-github-runner
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_tfhe_fft.yml
  .github/workflows/benchmark_tfhe_ntt.yml
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/code_coverage.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/integer_long_run_tests.yml
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1891 chore(gpu): add option to pre-release some buffers in scalar mul
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
Labels: cla-signed, approved

#1848 chore(ci): add randomized long run tests on CPU and GPU
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/integer_long_run_tests.yml
  Makefile
  scripts/integer-tests.sh
  scripts/test_filtering.py
  tfhe/Cargo.toml
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_erc20.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_erc20.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
Labels: cla-signed, approved

#1875 feat(gpu): speed up packing KS for levels==1
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
  backends/tfhe-cuda-backend/cuda/include/keyswitch.h
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, 4090_test

#1900 feat(gpu): implement vector comparisons gpu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  tfhe/src/high_level_api/array/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
Labels: cla-signed, approved
