Repository zama-ai/tfhe-rs, pull requests merged in 2024-02, with the labels that each got.

#843 chore(doc): fix modulus struct docstrings in shortint
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#841 chore(integer): plug keyswitching tests with the ci_run_filter for nextest
  tfhe/src/integer/key_switching_key/test.rs
Labels: cla-signed, approved

#838 feat(integer): add smart_neg_assign
  tfhe/src/integer/server_key/radix/neg.rs
Labels: cla-signed, approved

#846 fix(gpu): fix cuda_memset with size 0
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
Labels: cla-signed, approved

#821 Reuse pbs_buffer, tmp_lwe_before/after for single carry propagation
  backends/tfhe-cuda-backend/cuda/include/integer.h
Labels: cla-signed

#847 chore(doc): update installation to match README
  README.md
  tfhe/docs/getting_started/installation.md
Labels: cla-signed, approved

#853 chore(ci): run ec2 teardown only if setup is not skipped
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
Labels: cla-signed, ci, approved

#835 chore(gpu): abort when trying to launch 32 bit multi-bit PBS
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstraping_key.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
Labels: cla-signed, approved

#855 refactor(boolean): put all parameters into constant array
  tfhe/src/boolean/parameters/mod.rs
Labels: cla-signed, approved

#852 fix(gpu): fix 40 bit integer multiplication
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
Labels: cla-signed, approved

#845 chore(bench): implement integer casting benchmarks
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#857 feat(capi): allow cbindgen to generate docs
  tfhe/cbindgen.toml
Labels: cla-signed, approved

#858 chore(ci): add checks on params before running lattice estimation
  ci/lattice_estimator.sage
Labels: cla-signed, ci, approved

#859 chore(doc): fix docs snippet comments
  tfhe/docs/fine_grained_api/shortint/operations.md
Labels: cla-signed, approved

#866 chore(tfhe): pin bytemuck temporarily as the 1.14.2 is broken
  tfhe/Cargo.toml
Labels: cla-signed, approved

#860 chore(bench): fix ks benchmark
  .github/workflows/core_crypto_benchmark.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/start_benchmarks.yml
  .github/workflows/start_full_benchmarks.yml
  ci/slab.toml
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed

#848 feat(gpu): implement scalar eq/ne
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests.rs
Labels: cla-signed, approved

#863 feat(capi): add Cuda support
  .github/workflows/aws_tfhe_gpu_tests.yml
  Makefile
  scripts/c_api_tests.sh
  tfhe/build.rs
  tfhe/c_api_tests/CMakeLists.txt
  tfhe/c_api_tests/test_high_level_integers_cuda.c
  tfhe/cbindgen.toml
  tfhe/src/c_api/high_level_api/keys.rs
Labels: cla-signed, approved

#873 chore(bench): run keyswitch benchmarks on multi-bit parameters
  tfhe/benches/core_crypto/ks_bench.rs
Labels: cla-signed, approved

#869 chore(ci): notify ec2 teardown failure on slack channel
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
Labels: cla-signed, ci, approved

#862 chore(doc): Update Readme.md
  README.md
Labels: cla-signed, approved

#881 chore(ci): make avx512 enabled by default for benchmarks
  .github/workflows/boolean_benchmark.yml
  .github/workflows/core_crypto_benchmark.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/integer_benchmark.yml
  .github/workflows/integer_full_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/shortint_benchmark.yml
  .github/workflows/shortint_full_benchmark.yml
  .github/workflows/signed_integer_benchmark.yml
  .github/workflows/signed_integer_full_benchmark.yml
  .github/workflows/signed_integer_multi_bit_benchmark.yml
  Makefile
  tfhe/docs/getting_started/benchmarks.md
Labels: cla-signed, approved

#876 feat(shortint): add an atomic counter to keep track of the number of PBSes
  tfhe/Cargo.toml
  tfhe/examples/pbs_count.rs
  tfhe/src/lib.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#865 feat(gpu): scalar shifts with one wave of pbs
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
Labels: cla-signed, approved

#885 chore(bench): fix array declaration for multi-bit gpu
  tfhe/benches/core_crypto/ks_bench.rs
Labels: cla-signed

#883 chore(ci): update gpu aws ec2 ami
  ci/slab.toml
Labels: cla-signed, ci, approved

#877 feat(integer): add [trailing/leading]_[zeros/ones]
  tfhe/src/integer/server_key/radix_parallel/ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#892 chore(gpu): activate all targets for clippy_gpu
  Makefile
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests.rs
Labels: cla-signed, approved

#891 chore(ci): increase timeout for M1 mac CI
  .github/workflows/m1_tests.yml
Labels: cla-signed, approved

#889 fix(c-api): add missing function on FheBool
  tfhe/src/c_api/high_level_api/booleans.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/compressed.rs
Labels: cla-signed, approved

#890 fix(integer): correct degree in small comparisons
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
Labels: cla-signed, approved

#898 chore(ci): use aws-region as input to stop ec2 instances
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
Labels: cla-signed, ci, approved

#894 chore(gpu): add benchmarks for scalar eq/ne and casts
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#871 feat(capi): allow control of threading
  tfhe/c_api_tests/test_c_doc.c
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/c_api_tests/test_high_level_integers_cuda.c
  tfhe/c_api_tests/test_high_level_threading.c
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/c_api/high_level_api/threading.rs
Labels: cla-signed, approved

#901 chore(ci): fix cuda clippy targets
  Makefile
  tfhe/benches/integer/bench.rs
Labels: cla-signed

#904 chore(ci): run gpu benchmarks on rtx4090 every friday
  .github/workflows/integer_gpu_4090_full_benchmark.yml
Labels: cla-signed, ci, approved

#870 Chore/gpu/cuda vec
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shifts.cuh
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/gpu/entities/lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Labels: cla-signed, approved

#899 feat(integer) add ilog2 and checked_ilog2
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
Labels: cla-signed, approved

#878 chore(gpu): improve performance of comparison operations
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#909 chore(ci): fix missing backslash in rtx benchmark workflow
  .github/workflows/integer_gpu_4090_full_benchmark.yml
Labels: cla-signed, ci, approved

#906 feat(gpu): Reintroduce a tool to independently test PBS, Keyswitch, and fft
  .github/workflows/aws_tfhe_gpu_tests.yml
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/tests/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/tests/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/cuda/tests/include/utils.h
  backends/tfhe-cuda-backend/cuda/tests/setup_and_teardown.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/tests/src/README.md
  backends/tfhe-cuda-backend/cuda/tests/src/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/test_fft.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/test_keyswitch.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests/utils.cpp
Labels: cla-signed, approved

#911 chore(ci): lock version of lattice-estimator in workflow
  .github/workflows/parameters_check.yml
Labels: cla-signed, ci, approved

#910 chore(gpu): add core crypto benches to 4090 bench workflow
  .github/workflows/gpu_4090_full_benchmark.yml
Labels: cla-signed, approved, 4090_bench

#921 chore(gpu): fix 4090 bench workflow
  .github/workflows/gpu_4090_full_benchmark.yml
Labels: cla-signed, approved, 4090_bench

#925 chore(bench): format core_crypto benchmark names to ease parsing
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, ci, approved

#924 chore(gpu): move ciphertext info to dedicated file
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#927 chore(ci): add product cost for rtx4090 to compute throughput
  ci/ec2_products_cost.json
Labels: cla-signed, ci, approved, 4090_bench

#912 fix(gpu): fix scalar eq for booleans
  backends/tfhe-cuda-backend/cuda/include/integer.h
Labels: cla-signed

#919 Am/feat/dynamic distribution choice
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs128_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/docs/core_crypto/presentation.md
  tfhe/docs/core_crypto/tutorial.md
  tfhe/src/boolean/engine/bootstrapping.rs
  tfhe/src/boolean/engine/mod.rs
  tfhe/src/boolean/parameters/mod.rs
  tfhe/src/c_api/core_crypto/mod.rs
  tfhe/src/core_crypto/algorithms/lwe_compact_public_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/lwe_public_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_wopbs.rs
  tfhe/src/core_crypto/algorithms/test/lwe_compact_public_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/commons/generators/encryption/mod.rs
  tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
  tfhe/src/core_crypto/commons/generators/encryption/test.rs
  tfhe/src/core_crypto/commons/math/random/gaussian.rs
  tfhe/src/core_crypto/commons/math/random/generator.rs
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/commons/math/random/t_uniform.rs
  tfhe/src/core_crypto/commons/math/torus/mod.rs
  tfhe/src/core_crypto/commons/parameters.rs
  tfhe/src/core_crypto/commons/traits/encryptable.rs
  tfhe/src/core_crypto/commons/traits/mod.rs
  tfhe/src/core_crypto/fft_impl/common.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/prelude.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/shortint/engine/client_side.rs
  tfhe/src/shortint/engine/public_side.rs
  tfhe/src/shortint/engine/server_side.rs
  tfhe/src/shortint/engine/wopbs/mod.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/parameters_wopbs.rs
  tfhe/src/shortint/public_key/compact.rs
Labels: cla-signed

#929 feat(core_crypto): add parallelized pfpks with lwe ciphertext list
  tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
Labels: cla-signed, approved
