Repository zama-ai/tfhe-rs, pull requests merged in 2024-01, with the labels that each got.

#750 chore(doc): fix latex equation typo preventing formatting on GitHub
  tfhe/docs/README.md
Labels: cla-signed, approved

#755 chore(tfhe): update 2023 to 2024 in license files and other places
  LICENSE
  concrete-csprng/LICENSE
  tfhe/LICENSE
  tfhe/cbindgen.toml
Labels: cla-signed, approved

#758 chore(all): update SERIALIZATION_VERSION for 0.5 release
  tfhe/src/safe_deserialization.rs
Labels: cla-signed, approved

#751 doc(all): add doc for safe_(de)serialization
  tfhe/docs/how_to/serialization.md
Labels: cla-signed, approved

#762 chore(doc): fix docstring for FheIntX types
  tfhe/src/high_level_api/integers/types/static_.rs
Labels: cla-signed, approved

#759 feat(boolean): add raw parts methods to the ClientKey
  tfhe/src/boolean/client_key/mod.rs
Labels: cla-signed, approved

#763 chore(ci): add overflowing add and sub to integer benchmarks
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
Labels: cla-signed, ci, approved

#765 chore(core_crypto): remove Serde on some decomposition structs
  tfhe/src/core_crypto/commons/math/decomposition/mod.rs
  tfhe/src/core_crypto/commons/math/decomposition/term.rs
Labels: cla-signed, approved

#740 feat(integer): add unsigned overflowing mul
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned.rs
  tfhe/src/shortint/server_key/bitwise_op.rs
Labels: cla-signed, approved

#766 feat(integer): add cast_to_signed/unsigned
  tfhe/src/integer/server_key/radix/mod.rs
Labels: cla-signed, approved

#770 chore(ci): gather common benchmarks groups
  .github/workflows/integer_full_benchmark.yml
  .github/workflows/signed_integer_full_benchmark.yml
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
Labels: cla-signed, ci, approved

#764 feat(boolean): add raw parts methods to the ClientKey
  tfhe/src/boolean/client_key/mod.rs
Labels: cla-signed, approved

#775 refactor(shortint): make scalar_eq/scalar_not_eq take & not &mut
  tfhe/src/shortint/server_key/comp_op.rs
Labels: cla-signed, approved

#774 chore(ci): add overflowing unsigned multiplication to benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, ci, approved

#772 refactor(c_api): use DynamicBuffer as the buffer type between C and Rust
  Makefile
  scripts/symlink_c_libs_without_fingerprint.sh
  tfhe/Cargo.toml
  tfhe/c_api_tests/CMakeLists.txt
  tfhe/c_api_tests/test_boolean_keygen.c
  tfhe/c_api_tests/test_boolean_server_key.c
  tfhe/c_api_tests/test_high_level_256_bits.c
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/c_api_tests/test_shortint_keygen.c
  tfhe/c_api_tests/test_shortint_server_key.c
  tfhe/cbindgen.toml
  tfhe/docs/how_to/c_api.md
  tfhe/src/c_api/boolean/ciphertext.rs
  tfhe/src/c_api/boolean/client_key.rs
  tfhe/src/c_api/boolean/public_key.rs
  tfhe/src/c_api/boolean/server_key.rs
  tfhe/src/c_api/buffer.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/c_api/shortint/ciphertext.rs
  tfhe/src/c_api/shortint/client_key.rs
  tfhe/src/c_api/shortint/public_key.rs
  tfhe/src/c_api/shortint/server_key/mod.rs
Labels: cla-signed, approved

#782 chore(ci): add placeholder workflow for cuda backend
  .github/workflows/aws_tfhe_gpu_tests.yml
Labels: cla-signed, ci

#784 chore(ci): add newline to workflow
  .github/workflows/aws_tfhe_gpu_tests.yml
Labels: cla-signed

#787 chore(bench): fix multi-bit parameters selection for multi-bit
  tfhe/benches/integer/bench.rs
Labels: cla-signed, ci, approved

#776 refactor(hlapi): prepare hlapi for different backends/representations
  Makefile
  tfhe/Cargo.toml
  tfhe/benches/high_level_api/bench.rs
  tfhe/docs/how_to/trivial_ciphertext.md
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/keys.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/compact.rs
  tfhe/src/high_level_api/booleans/compressed.rs
  tfhe/src/high_level_api/booleans/mod.rs
  tfhe/src/high_level_api/booleans/tests.rs
  tfhe/src/high_level_api/config.rs
  tfhe/src/high_level_api/design.md
  tfhe/src/high_level_api/details.rs
  tfhe/src/high_level_api/errors.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/integers/client_key.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/parameters.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/compact.rs
  tfhe/src/high_level_api/integers/signed/compressed.rs
  tfhe/src/high_level_api/integers/signed/mod.rs
  tfhe/src/high_level_api/integers/signed/static_.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/types/base.rs
  tfhe/src/high_level_api/integers/types/mod.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/compact.rs
  tfhe/src/high_level_api/integers/unsigned/compressed.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/integers/unsigned/tests.rs
  tfhe/src/high_level_api/integers/unsigned/wopbs.rs
  tfhe/src/high_level_api/internal_traits.rs
  tfhe/src/high_level_api/keys/client.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
  tfhe/src/high_level_api/keys/mod.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/ciphertext/boolean_value.rs
  tfhe/src/integer/key_switching_key/mod.rs
Labels: cla-signed, approved

#779 chore(core): remove Serialize and Deserialize on GlweBody
  tfhe/src/core_crypto/entities/glwe_ciphertext.rs
Labels: cla-signed, approved

#789 feat(hlapi): add gpu support
  tfhe/Cargo.toml
  tfhe/examples/sha256.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/tests.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/keys/mod.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
Labels: cla-signed

#792 feat(hlapi): update wasm and c_api
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/src/c_api/high_level_api/booleans.rs
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
Labels: cla-signed, approved

#799 doc: overflow detection
  tfhe/docs/SUMMARY.md
  tfhe/docs/how_to/overflow_operations.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed

#756 doc(data_migration): add documentation on how to migrate data for TFHE
  tfhe/docs/SUMMARY.md
  tfhe/docs/how_to/migrate_data.md
Labels: cla-signed

#757 doc(tfhe): add doc page about data migration which will redirect to 0.4 doc
  tfhe/docs/SUMMARY.md
  tfhe/docs/how_to/migrate_data.md
Labels: cla-signed

#791 chore(ci): separate clippy and tests in different job steps
  .github/workflows/aws_tfhe_gpu_tests.yml
Labels: cla-signed, ci, approved

#803 Doc/0.5.0/gpu
  tfhe/docs/SUMMARY.md
  tfhe/docs/how_to/run_on_gpu.md
Labels: cla-signed

#804 chore(tfhe): add version for tfhe-cuda-backend dependency
  tfhe/Cargo.toml
Labels: cla-signed, approved

#809 chore(docs): fix link to 0.4 semver doc
  tfhe/docs/how_to/migrate_data.md
Labels: cla-signed, approved

#808 chore(docs): fix link to 0.4 semver doc
  tfhe/docs/how_to/migrate_data.md
Labels: cla-signed, approved

#802 chore(hlapi): remove leftover file
  tfhe/src/high_level_api/integers/types/static_.rs
Labels: cla-signed, approved

#798 fix(integer): fix cast in scalar_shift/rotate
  tfhe/src/high_level_api/integers/unsigned/tests.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
Labels: cla-signed, approved

#800 TFHE-cuda-backend | Rename "test vector" to "luts" and "tvi" to "lut indexes"
  backends/tfhe-cuda-backend/cuda/include/bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_low_latency.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_fast_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_low_latency.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_low_latency.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cuh
Labels: cla-signed, approved

#807 fix(core): ignore value in the body when doing LWE encryption
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
Labels: cla-signed, approved

#815 chore(ci): fix inputs for gpu full benchmark workflow
  .github/workflows/integer_gpu_full_benchmark.yml
Labels: cla-signed, ci, approved

#797 fix(integer): is_scalar_out_of_bounds handles bigger ct
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
Labels: cla-signed, approved

#814 chore(ci): add gpu tests from user documentation
  .github/workflows/aws_tfhe_gpu_tests.yml
  Makefile
  tfhe/src/test_user_docs.rs
Labels: cla-signed, ci, approved

#817 chore(doc): correct some typos and wrong phrasing on data migration
  tfhe/docs/how_to/migrate_data.md
Labels: cla-signed, approved

#820 Fix cuda_drop binding, mark async functions unsafe
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/gpu/entities/lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
Labels: cla-signed, approved

#813 Update README.md
  README.md
Labels: cla-signed, approved

#812 Doc update
  tfhe/docs/SUMMARY.md
  tfhe/docs/how_to/debug.md
  tfhe/docs/how_to/rayon_crate.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#811 Add gpu benchmarks for the PBS & multi-bit PBS
  .github/workflows/pbs_gpu_benchmark.yml
  .github/workflows/start_benchmarks.yml
  .github/workflows/start_full_benchmarks.yml
  Makefile
  ci/slab.toml
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, approved

#793 chore(bench): add ciphertexts sum to integer benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, ci, approved

#666 Fix comp
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
Labels: cla-signed, approved

#824 docs(bench): add scalar benchmarks for integer
  tfhe/docs/getting_started/benchmarks.md
Labels: cla-signed, approved

#830 docs(bench): add scalar benchmarks for integer
  tfhe/docs/getting_started/benchmarks.md
Labels: cla-signed, approved

#822 chore(gpu): check for all cuda errors and abort in device.cu/.h
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#833 chore(docs): fix typo
  tfhe/docs/how_to/public_key.md
Labels: cla-signed, approved

#834 chore(integer): remove deprecated parameter set
  tfhe/src/integer/parameters/mod.rs
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/integer/wopbs/test.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/parameters_wopbs.rs
Labels: cla-signed, approved

#836 Am/chore/add more semver compatible make targets
  Makefile
  scripts/integer-tests.sh
  scripts/shortint-tests.sh
Labels: cla-signed, approved

#788 docs(tfhe): add fhe_strings example
  Makefile
  tfhe/Cargo.toml
  tfhe/examples/fhe_strings/README.md
  tfhe/examples/fhe_strings/assert_functions/mod.rs
  tfhe/examples/fhe_strings/assert_functions/test_vectors.rs
  tfhe/examples/fhe_strings/ciphertext.rs
  tfhe/examples/fhe_strings/client_key.rs
  tfhe/examples/fhe_strings/main.rs
  tfhe/examples/fhe_strings/server_key/comp.rs
  tfhe/examples/fhe_strings/server_key/mod.rs
  tfhe/examples/fhe_strings/server_key/no_patterns.rs
  tfhe/examples/fhe_strings/server_key/pattern/contains.rs
  tfhe/examples/fhe_strings/server_key/pattern/find.rs
  tfhe/examples/fhe_strings/server_key/pattern/mod.rs
  tfhe/examples/fhe_strings/server_key/pattern/replace.rs
  tfhe/examples/fhe_strings/server_key/pattern/split/mod.rs
  tfhe/examples/fhe_strings/server_key/pattern/split/split_iters.rs
  tfhe/examples/fhe_strings/server_key/pattern/strip.rs
  tfhe/examples/fhe_strings/server_key/trim.rs
Labels: cla-signed

#840 Am/chore/semver targets 0 5
  Makefile
  scripts/integer-tests.sh
  scripts/shortint-tests.sh
Labels: cla-signed, approved
