Repository zama-ai/tfhe-rs, pull requests merged in 2024-04, with the labels that each got.

#1039 feat(hlapi): bind sum for cuda backend
  tfhe/src/high_level_api/integers/unsigned/inner.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
  tfhe/src/high_level_api/keys/server.rs
Labels: cla-signed, approved

#1029 Feat/gpu/signed eq ne
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/booleans/inner.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_comparisons.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_comparison.rs
Labels: cla-signed, approved

#1048 feat(gpu): signed scalar rotate
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_rotate.rs
Labels: cla-signed, approved

#1049 fix(gpu): fix mult 256 bit benchmark
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#1051 chore(gpu): remove carry prop after scalar mul single carry prop after scalar add/sub
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
Labels: cla-signed, approved

#1052 chore(gpu): fix multi-bit scalar mul benchmark
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#905 refactor(hlapi): improve conformance deserialization API
  tfhe/docs/fundamentals/serialization.md
  tfhe/src/c_api/high_level_api/booleans.rs
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/compact.rs
  tfhe/src/high_level_api/booleans/compressed.rs
  tfhe/src/high_level_api/booleans/mod.rs
  tfhe/src/high_level_api/booleans/tests.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/compact.rs
  tfhe/src/high_level_api/integers/signed/compressed.rs
  tfhe/src/high_level_api/integers/signed/static_.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/compact.rs
  tfhe/src/high_level_api/integers/unsigned/compressed.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/safe_deserialization.rs
Labels: cla-signed, approved

#1054 doc(gpu): add benchmark results
  tfhe/docs/getting_started/benchmarks.md
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed

#1042 Feat/gpu/signed if then else
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/integer/gpu/server_key/radix/cmux.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_cmux.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
Labels: cla-signed, approved

#1062 doc(gpu): add missing benchmark results
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed

#1040 chore(wop): remove outdated parameters and update other parameters
  tfhe/benches/shortint/bench.rs
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/integer/wopbs/test.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/parameters_wopbs.rs
  tfhe/src/shortint/parameters/parameters_wopbs_message_carry.rs
  tfhe/src/shortint/parameters/parameters_wopbs_only.rs
  tfhe/src/shortint/parameters/parameters_wopbs_prime_moduli.rs
  tfhe/src/shortint/wopbs/mod.rs
  tfhe/src/shortint/wopbs/test.rs
Labels: cla-signed, approved

#1063 chore(zk): add metadat for Cargo publish
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/LICENSE
Labels: cla-signed

#1053 Feat/gpu/signed scalar comparisons
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
Labels: cla-signed

#1065 chore(gpu): add lwe_chunk_size targeting RTX 4090 GPUs
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#1064 fix(gpu): add edge test for scalar comparisons
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
Labels: cla-signed, approved

#1067 chore(hl): add method to be able to perform data update from 0.5 compressed
  tfhe/src/high_level_api/integers/signed/compressed.rs
  tfhe/src/high_level_api/integers/unsigned/compressed.rs
Labels: cla-signed, approved

#1071 chore(c): change include <tfhe.h> to "tfhe.h"
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
  tfhe/c_api_tests/test_boolean_keygen.c
  tfhe/c_api_tests/test_boolean_server_key.c
  tfhe/c_api_tests/test_c_doc.c
  tfhe/c_api_tests/test_high_level_128_bits.c
  tfhe/c_api_tests/test_high_level_256_bits.c
  tfhe/c_api_tests/test_high_level_boolean.c
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/c_api_tests/test_high_level_integers_cuda.c
  tfhe/c_api_tests/test_high_level_threading.c
  tfhe/c_api_tests/test_high_level_zk.c
  tfhe/c_api_tests/test_micro_bench_and.c
  tfhe/c_api_tests/test_shortint_keygen.c
  tfhe/c_api_tests/test_shortint_pbs.c
  tfhe/c_api_tests/test_shortint_server_key.c
  tfhe/docs/guides/c_api.md
Labels: cla-signed, approved

#1073 chore(ci): make a github runner remove a label
  .github/workflows/gpu_4090_full_benchmark.yml
Labels: cla-signed

#1086 fix(gpu): fix typo in doc
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed, approved

#1072 chore(ci): fix sage script f-string missing f
  ci/lattice_estimator.sage
Labels: cla-signed, approved

#1078 chore(doc): fix API calls
  apps/trivium/README.md
  tfhe/docs/guides/js_on_wasm_api.md
Labels: cla-signed, approved

#1091 chore(gpu): add casts and signed scalar comparisons to the hl api
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
Labels: cla-signed, approved

#989 chore(gpu): add tests for N=8192 multi-bit PBS
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
Labels: cla-signed

#1061 feat(integer): add vector match_value/index_of/contains/is_in
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_find.rs
  tfhe/src/integer/server_key/radix_parallel/vector_find.rs
  tfhe/src/shortint/ciphertext/common.rs
Labels: cla-signed, approved

#1075 Mz/fix apply lookup table bivariate check
  tfhe/src/integer/server_key/radix/bitwise_op.rs
  tfhe/src/shortint/server_key/bitwise_op.rs
  tfhe/src/shortint/server_key/bivariate_pbs.rs
  tfhe/src/shortint/server_key/comp_op.rs
  tfhe/src/shortint/server_key/mul.rs
Labels: cla-signed, approved

#1100 chore(integer): reduce nb tests for big params
  tfhe/src/integer/server_key/radix_parallel/ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_find.rs
  tfhe/src/integer/server_key/radix_parallel/vector_find.rs
Labels: cla-signed, approved

#1102 fix(zk): correct byte indices for uncompressed serializtion
  tfhe-zk-pok/src/curve_446/mod.rs
Labels: cla-signed, approved

#1101 chore(gpu): reduce memory consumption in host_integer_sum_ciphertexts_vec_kb
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed

#1068 chore(gpu): automatically compute the best lwe_chunk_size
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
Labels: cla-signed, 4090_bench

#1107 chore(gpu): fix params in GPU integer benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1099 chore(core): fix the stair KS test for more generic stair KS parameters
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
Labels: cla-signed

#1112 chore(doc): fix broken link
  tfhe/docs/getting_started/quick_start.md
Labels: cla-signed

#1117 chore(bench): fix naming format for signed scalar operations
  tfhe/benches/integer/signed_bench.rs
Labels: cla-signed, ci, approved

#1115 chore(ci): separate pcc and tests for gpu to allow faster merge
  .github/workflows/aws_tfhe_gpu_tests.yml
Labels: cla-signed, ci, approved

#1106 feat(gpu): implement div_rem for cuda GPU
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/bench.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_div_mod.rs
Labels: cla-signed, approved

#1116 chore(ci): update toolchain to latest nightly
  tfhe-zk-pok/src/curve_446/mod.rs
  tfhe/src/core_crypto/gpu/slice.rs
  tfhe/src/integer/server_key/radix_parallel/vector_find.rs
  toolchain.txt
Labels: cla-signed, approved
