Repository zama-ai/tfhe-rs, pull requests merged in 2024-03, with the labels that each got.

#933 refactor(core): change layout of compact public key encryption for LWE list
  tfhe/src/core_crypto/algorithms/lwe_compact_ciphertext_list_expansion.rs
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
Labels: cla-signed, approved

#934 chore(bench): benchmark 4 bits integer operations
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#935 feat(core): switch GLWE primitives to the new noise distribution system
  tfhe/benches/keygen/bench.rs
  tfhe/docs/core_crypto/tutorial.md
  tfhe/src/boolean/engine/bootstrapping.rs
  tfhe/src/c_api/core_crypto/mod.rs
  tfhe/src/core_crypto/algorithms/ggsw_encryption.rs
  tfhe/src/core_crypto/algorithms/glwe_encryption.rs
  tfhe/src/core_crypto/algorithms/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/lwe_packing_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_private_functional_packing_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/lwe_wopbs.rs
  tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/glwe_linear_algebra.rs
  tfhe/src/core_crypto/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/algorithms/test/lwe_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_packing_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_private_functional_packing_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/commons/generators/encryption/mod.rs
  tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
  tfhe/src/core_crypto/commons/generators/encryption/test.rs
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/fft_impl/common.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/shortint/engine/server_side.rs
  tfhe/src/shortint/engine/wopbs/mod.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/multi_bit.rs
  tfhe/src/shortint/parameters/parameters_wopbs.rs
Labels: cla-signed, approved

#946 chore(ci): fix workflows, missing leading $, skipped does not exist
  .github/workflows/gpu_4090_full_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
Labels: cla-signed, approved

#952 chore(ci): fix CUDA_PATH bin not being exported in GITHUB_PATH
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
Labels: cla-signed, approved

#953 chore(gpu): change recomended lwe_chunk_size for NVIDIA Tesla H100 GPUs
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
Labels: cla-signed, approved

#944 fix(gpu): fix memory bug in multi-bit PBS
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap_multibit.cu
Labels: cla-signed, approved

#949 feat(gpu): signed sub and neg with tests and benchmarks
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/neg.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_neg.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_neg.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#951 chore(core): make torus_modular_diff safer to use
  tfhe/src/core_crypto/algorithms/misc.rs
Labels: cla-signed

#937 test(shortint): add oprf deterministic test
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/oprf.rs
Labels: cla-signed

#945 refactor(tfhe): plug NoiseDistribution in the various APIs
  .github/workflows/aws_tfhe_gpu_4090_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  Makefile
  backends/tfhe-cuda-backend/cuda/.gitignore
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
  backends/tfhe-cuda-backend/cuda/tests/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/cuda/tests/include/utils.h
  backends/tfhe-cuda-backend/cuda/tests/setup_and_teardown.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/tests/src/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/test_keyswitch.cpp
  backends/tfhe-cuda-backend/cuda/tests/src/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests/utils.cpp
  tfhe/Cargo.toml
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/benches/keygen/bench.rs
  tfhe/benches/utilities.rs
  tfhe/c_api_tests/test_boolean_keygen.c
  tfhe/c_api_tests/test_shortint_keygen.c
  tfhe/examples/dist_tuniform.rs
  tfhe/examples/utilities/params_to_file.rs
  tfhe/src/boolean/engine/bootstrapping.rs
  tfhe/src/boolean/engine/mod.rs
  tfhe/src/boolean/parameters/mod.rs
  tfhe/src/c_api/boolean/client_key.rs
  tfhe/src/c_api/boolean/mod.rs
  tfhe/src/c_api/boolean/parameters.rs
  tfhe/src/c_api/core_crypto/mod.rs
  tfhe/src/c_api/shortint/parameters.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/commons/math/random/gaussian.rs
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/commons/math/random/t_uniform.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/parameters/mod.rs
  tfhe/src/js_on_wasm_api/boolean.rs
  tfhe/src/js_on_wasm_api/shortint.rs
  tfhe/src/shortint/engine/server_side.rs
  tfhe/src/shortint/engine/wopbs/mod.rs
  tfhe/src/shortint/mod.rs
  tfhe/src/shortint/parameters/coverage_parameters.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/multi_bit.rs
  tfhe/src/shortint/parameters/parameters_compact_pk.rs
  tfhe/src/shortint/parameters/parameters_wopbs.rs
  tfhe/src/shortint/parameters/parameters_wopbs_message_carry.rs
  tfhe/src/shortint/parameters/parameters_wopbs_prime_moduli.rs
Labels: cla-signed

#940 chore(integer): move & hardden sub/neg tests
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix/neg.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#959 chore(ci): handle new name format to get pbs throughput values
  ci/benchmark_parser.py
Labels: cla-signed, ci, approved

#954 Feat/gpu/signed mul
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/server_key/radix/mul.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_mul.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_mul.rs
Labels: cla-signed, approved

#957 chore(hlapi): add some GPU test for FheUint
  tfhe/src/high_level_api/integers/unsigned/tests.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
Labels: cla-signed, approved

#962 chore(bench): reduce measurement duration to 60 for pbs benchmarks
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, ci, approved

#961 chore(ci): make sure dev_bench is checked by clippy
  tfhe/Cargo.toml
  tfhe/benches/core_crypto/dev_bench.rs
Labels: cla-signed, approved

#966 chore(ci): to avoid stack overlow crashes increase thread stack size
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_4090_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/boolean_benchmark.yml
  .github/workflows/cargo_build.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/gpu_4090_full_benchmark.yml
  .github/workflows/integer_benchmark.yml
  .github/workflows/integer_full_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/m1_tests.yml
  .github/workflows/shortint_benchmark.yml
  .github/workflows/shortint_full_benchmark.yml
  .github/workflows/signed_integer_benchmark.yml
  .github/workflows/signed_integer_full_benchmark.yml
  .github/workflows/signed_integer_multi_bit_benchmark.yml
  .github/workflows/wasm_client_benchmark.yml
Labels: cla-signed, approved

#955 Feat/gpu/signed scalar add
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_add.rs
Labels: cla-signed, approved

#971 chore(tfhe): remove last remaining modular_std_dev
  tfhe/docs/fine_grained_api/Boolean/parameters.md
  tfhe/docs/fine_grained_api/shortint/parameters.md
  tfhe/src/boolean/parameters/mod.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/fft_impl/common.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#974 chore(gpu): rename the low-latency PBS to just PBS and the fast variants to cg
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrap.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstraping_key.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/setup_and_teardown.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_fft.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/utils.cpp
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/entities/lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed

#960 Feat/gpu/signed scalar sub
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_sub.rs
Labels: cla-signed, approved

#981 chore(gpu): fix compilation without a device
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/CMakeLists.txt
Labels: cla-signed, approved

#928 feat(gpu): optimize gpu integer multiplication vector_ add block.
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
Labels: cla-signed, 4090_bench

#958 feat(integer): improve propagation & sum algorithms
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/neg.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
Labels: cla-signed, approved

#976 feat(gpu): add support to larger polynomials on multi-bit PBS
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
Labels: cla-signed

#986 fix(integer): fix parallel carry propagation on empty input
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
Labels: cla-signed, approved

#982 fix(trivium): check warnings in benches
  Makefile
  apps/trivium/benches/kreyvium_shortint.rs
  apps/trivium/benches/trivium_shortint.rs
Labels: cla-signed, approved

#972 Feat/gpu/signed bitops
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_bitwise_op.rs
Labels: cla-signed, approved

#991 chore(tfhe): fix typos
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/fft/bnsmfft.cuh
  backends/tfhe-cuda-backend/cuda/src/fft/twiddles.cuh
  tfhe/docs/how_to/serialization.md
  tfhe/src/boolean/ciphertext/mod.rs
  tfhe/src/boolean/client_key/mod.rs
  tfhe/src/boolean/engine/bootstrapping.rs
  tfhe/src/boolean/key_switching_key/mod.rs
  tfhe/src/boolean/public_key/compressed.rs
  tfhe/src/boolean/public_key/standard.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/core_crypto/entities/modulus_switched_lwe_ciphertext.rs
  tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/ggsw.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/client_key/mod.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/key_switching_key/mod.rs
  tfhe/src/integer/public_key/compact.rs
  tfhe/src/integer/public_key/compressed.rs
  tfhe/src/integer/public_key/standard.rs
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/lib.rs
  tfhe/src/shortint/ciphertext/mod.rs
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/src/shortint/public_key/compressed.rs
  tfhe/src/shortint/public_key/standard.rs
  tfhe/src/shortint/server_key/compressed.rs
  tfhe/src/shortint/server_key/mod.rs
  tfhe/src/shortint/wopbs/mod.rs
Labels: cla-signed

#994 chore(ci): use new workflow fine-grained token
  .github/workflows/approve_label.yml
  .github/workflows/boolean_benchmark.yml
  .github/workflows/core_crypto_benchmark.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/gpu_4090_full_benchmark.yml
  .github/workflows/integer_benchmark.yml
  .github/workflows/integer_full_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/shortint_benchmark.yml
  .github/workflows/shortint_full_benchmark.yml
  .github/workflows/signed_integer_benchmark.yml
  .github/workflows/signed_integer_full_benchmark.yml
  .github/workflows/signed_integer_multi_bit_benchmark.yml
  .github/workflows/start_benchmarks.yml
  .github/workflows/start_full_benchmarks.yml
  .github/workflows/sync_on_push.yml
  .github/workflows/wasm_client_benchmark.yml
Labels: cla-signed, ci, approved

#985 chore(ci): change slack notifications to be less confusing and more robust
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/boolean_benchmark.yml
  .github/workflows/core_crypto_benchmark.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/gpu_4090_full_benchmark.yml
  .github/workflows/integer_benchmark.yml
  .github/workflows/integer_full_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/shortint_benchmark.yml
  .github/workflows/shortint_full_benchmark.yml
  .github/workflows/signed_integer_benchmark.yml
  .github/workflows/signed_integer_full_benchmark.yml
  .github/workflows/signed_integer_multi_bit_benchmark.yml
  .github/workflows/wasm_client_benchmark.yml
Labels: cla-signed, approved

#975 feat(integer): make bitnot a trivial operation
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/examples/fhe_strings/server_key/trim.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/server_key/radix/bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_bitwise_op.rs
  tfhe/src/shortint/server_key/bitwise_op.rs
Labels: cla-signed, approved

#984 Feat/gpu/signed scalar bitops
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_bitwise_op.rs
Labels: cla-signed, approved

#1001 chore(ci): run aws gpu benchmark only on p3 instances
  ci/slab.toml
Labels: cla-signed, ci, approved

#1002 fix(integer): fix the CRT LUT generation
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/integer/wopbs/test.rs
Labels: cla-signed, approved

#1005 fix(gpu): includes tests_and_benchmarks/include to format_tfhe_cuda_backend.sh
  backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
Labels: cla-signed

#1008 fix(gpu): fix compilation when the user doesn't have a CUDA-capable device
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
Labels: cla-signed, approved

#1009 chore(ci): force the removal of the 4090 label for PRs even for failures
  .github/workflows/aws_tfhe_gpu_4090_tests.yml
  .github/workflows/gpu_4090_full_benchmark.yml
Labels: cla-signed, approved

#1007 chore(ci): create workflow to release tfhe-cuda-backend crate
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1014 chore(tfhe): make sure the GPU module is present during doc compilation
  Makefile
  backends/tfhe-cuda-backend/build.rs
  tfhe/Cargo.toml
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#1012 fix(gpu): fix bug in integer mult when k > 1
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
Labels: cla-signed, approved

#1006 feat(gpu): implement overflowing_sub
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/bench.rs
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#1020 feat(gpu): add an entry point to decompress integer server key to cuda server key
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/gpu/server_key/mod.rs
Labels: cla-signed, approved

#1025 fix(gpu): fix build.rs warning
  backends/tfhe-cuda-backend/build.rs
Labels: cla-signed

#1028 chore(doc): fix incorrect comment in repo README
  README.md
Labels: cla-signed

#1018 feat(tfhe): add explicit decompress primitives for all CompressedServerKey
  tfhe/src/boolean/engine/bootstrapping.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/shortint/server_key/compressed.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#1031 chore(gpu): replaces a mention to the low-latency PBS by just 'classical PBS' and removes a mention to the amortized variant
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed, approved

#1030 fix(gpu): replace hardcoded degrees in multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#1026 feat(gpu): implement signed and unsigned encrypted shift and rotate
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cu
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_shift.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_shift.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_shift.rs
Labels: cla-signed, approved

#1037 feat(tfhe): use concrete-fft 0.4.1 for faster pbs 128 by default
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1019 Feat/gpu/scalar mul
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_mul.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_neg.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_shift.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_mul.rs
  tfhe/src/integer/server_key/radix_parallel/ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_signed.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_neg.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_bitwise_op.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_mul.rs
Labels: cla-signed
