Repository zama-ai/tfhe-rs, pull requests merged in 2024-09, with the labels that each got.

#1476 fix(gpu): update the internal benchmark tool for the TBC pbs
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
Labels: cla-signed, approved

#1506 chore(ci): rename benchmark workflows to ease file navigation
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_integer.yml
  .github/workflows/benchmark_gpu_integer_full.yml
  .github/workflows/benchmark_gpu_integer_multi_bit.yml
  .github/workflows/benchmark_gpu_integer_multi_bit_multi_gpu.yml
  .github/workflows/benchmark_gpu_integer_multi_gpu_full.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
Labels: cla-signed, ci, approved

#1507 chore(ci): avoid running integer tests on push to internal repo
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
Labels: cla-signed, ci, approved

#1502 chore(ci): update node project packages
  tfhe/web_wasm_parallel_tests/package-lock.json
  tfhe/web_wasm_parallel_tests/package.json
Labels: cla-signed, approved

#1498 feat(pbs): slightly improve f64 pbs perf
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/fft/x86.rs
Labels: cla-signed, approved

#1510 chore(gpu): add ilog2 bench
  tfhe/benches/integer/bench.rs
Labels: cla-signed

#1511 chore: bump version to 0.8.0-alpha.4
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1504 feat(hlapi): bind cuda's trailing/leading_ones/zeros, ilog2
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
Labels: cla-signed, approved

#1468 feat(hlapi): add tag system
  tfhe/src/high_level_api/array.rs
  tfhe/src/high_level_api/backward_compatibility/booleans.rs
  tfhe/src/high_level_api/backward_compatibility/compact_list.rs
  tfhe/src/high_level_api/backward_compatibility/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/backward_compatibility/integers.rs
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/high_level_api/backward_compatibility/mod.rs
  tfhe/src/high_level_api/backward_compatibility/tag.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/compressed.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/booleans/mod.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/integers/oprf.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/compressed.rs
  tfhe/src/high_level_api/integers/signed/encrypt.rs
  tfhe/src/high_level_api/integers/signed/mod.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/compressed.rs
  tfhe/src/high_level_api/integers/unsigned/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/keys/client.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/tag.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/high_level_api/tests/tags_on_entities.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/high_level_api/utils.rs
  tfhe/tests/backward_compatibility/high_level_api.rs
Labels: cla-signed, approved

#1461 chore(gpu): remove device synchronization in drop for CudaVec
  tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
Labels: cla-signed

#1513 chore(gpu): fix bad merge
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
Labels: cla-signed, approved

#1515 chore(gpu): reduce the amount of weekly multi-gpu bench
  .github/workflows/benchmark_gpu_integer_multi_gpu_full.yml
Labels: cla-signed, approved

#1302 feat(zk): implement faster pke proof
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/src/curve_api.rs
  tfhe-zk-pok/src/curve_api/bls12_446.rs
  tfhe-zk-pok/src/curve_api/msm.rs
  tfhe-zk-pok/src/four_squares.rs
  tfhe-zk-pok/src/lib.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#1514 chore(gpu): pass over all cuda bind
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
  backends/tfhe-cuda-backend/src/cuda_bind.rs
Labels: cla-signed, approved

#1505 refactor(gpu): avoid synchronizations in the keybundle
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
Labels: cla-signed

#1483 chore(gpu): add debug/release modes
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
Labels: cla-signed

#1485 fix(gpu): fix compression
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  Makefile
  backends/tfhe-cuda-backend/cuda/include/compression.h
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed, approved

#1431 refactor(integer): add compression key types
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/high_level_api/keys/client.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/backward_compatibility/list_compression.rs
  tfhe/src/integer/backward_compatibility/mod.rs
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/client_key/mod.rs
  tfhe/src/integer/client_key/radix.rs
  tfhe/src/integer/compression_keys.rs
  tfhe/src/integer/gpu/client_key/radix.rs
  tfhe/src/integer/gpu/list_compression/compressed_server_keys.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/integer/mod.rs
Labels: cla-signed, approved, data_PR

#1526 refactor(shortint): move parameters set to their own directory
  tfhe/benches/integer/zk_pke.rs
  tfhe/docs/guides/zk-pok.md
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/examples/utilities/shortint_key_sizes.rs
  tfhe/src/c_api/shortint/parameters.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/tests/tags_on_entities.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/key_switching_key/test.rs
  tfhe/src/js_on_wasm_api/shortint.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/compact_public_key_only/mod.rs
  tfhe/src/shortint/parameters/compact_public_key_only/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/parameters/compact_public_key_only/p_fail_2_minus_64/mod.rs
  tfhe/src/shortint/parameters/key_switching/mod.rs
  tfhe/src/shortint/parameters/key_switching/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/parameters/key_switching/p_fail_2_minus_64/mod.rs
  tfhe/src/shortint/prelude.rs
Labels: cla-signed, approved

#1520 chore(ci): the detect handles option from jest is freezing the runner
  tfhe/web_wasm_parallel_tests/package.json
Labels: cla-signed, approved

#1530 Am/chore/remove lint reason
  tfhe/src/js_on_wasm_api/js_high_level_api/zk.rs
Labels: cla-signed, approved

#1500 feat(integer): improve comparison algorithm
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_comparison.rs
Labels: cla-signed, approved

#1532 chore(bench): make compression benchmarks available for database
  .github/workflows/benchmark_gpu_integer_full.yml
  .github/workflows/benchmark_integer.yml
  Makefile
  tfhe/benches/integer/glwe_packing_compression.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/list_compression.rs
Labels: cla-signed, ci, approved

#1523 feat(zk): manage D as an upper bound as in the report
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#1537 chore: bump version to 0.8.0-alpha.6
  tfhe/Cargo.toml
Labels: cla-signed

#1535 chore(zk): add some comments to the zk pke v2 proof
  tfhe-zk-pok/src/proofs/pke_v2.rs
  tfhe/src/zk.rs
Labels: cla-signed, approved

#1534 feat(zk): recompute big d in zk v1 to be more efficient when k < k_max
  tfhe-zk-pok/src/proofs/pke.rs
Labels: cla-signed, approved

#1533 Am/feat/expand no verify
  tfhe/src/c_api/high_level_api/compact_list.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/tests/tags_on_entities.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
  tfhe/src/shortint/ciphertext/zk.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed

#1512 fix(integer): do sum by safe chunk sizes
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
Labels: cla-signed, approved

#1540 chore(gpu): change multi-gpu tests to run on rtx so it's cheaper
  ci/slab.toml
Labels: cla-signed, approved

#1538 fix(gpu): add missing synchronize in scalar add, refactor scalar add …
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_addition.cuh
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
Labels: approved

#1539 chore(gpu): use only 1 thread for core crypto tests to better track down bugs
  .github/workflows/gpu_fast_h100_tests.yml
  scripts/integer-tests.sh
Labels: cla-signed, approved

#1541 chore: ensure actions are pinned by commit hash
  .github/workflows/ci_lint.yml
Labels: cla-signed, approved

#1528 Go/feature/implement many luts
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/shortint/engine/mod.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#1549 chore(ci): remove support for slab calls with issue comments
  ci/slab.toml
Labels: cla-signed, ci, approved

#1548 chore: update tfhe to 0.8.0-alpha.8 / cuda-backend to 0.4.0-alpha.1
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1555 chore(ci): only notify for most things on failure
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/benchmark_gpu_integer_full.yml
  .github/workflows/benchmark_gpu_integer_multi_bit.yml
  .github/workflows/benchmark_gpu_integer_multi_bit_multi_gpu.yml
  .github/workflows/benchmark_gpu_integer_multi_gpu_full.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/gpu_4090_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#1554 fix(gpu): fix comparisons
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
Labels: cla-signed, approved

#1558 chore(gpu): remove unchecked benchmarks and add ilog2 to dedup ops
  .github/workflows/benchmark_gpu_integer_full.yml
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1560 fix(gpu): use build profile for cuda release
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, approved

#1561 feat(integer): add raw parts API to integer CompressionPrivateKey
  tfhe/src/integer/compression_keys.rs
Labels: cla-signed, approved

#1562 chore(gpu): temporarily set test threads to 1 for the GPU
  Makefile
  scripts/integer-tests.sh
Labels: cla-signed, approved

#1536 chore(gpu): add checks to ensure limits for compression
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed, approved

#1564 feat(hl): impl Named for key types
  tfhe/src/high_level_api/keys/client.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/high_level_api/keys/server.rs
Labels: cla-signed, approved

#1569 chore(gpu): disable slack notification for fast h100 test success
  .github/workflows/gpu_fast_h100_tests.yml
Labels: cla-signed, approved

#1556 chore(gpu): initialize some arrays to 0
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Labels: cla-signed, approved

#1568 chore(gpu): add file to run full tests on H100 from workflow only
  .github/workflows/gpu_full_h100_tests.yml
Labels: cla-signed, approved

#1565 feat(zk): add metadata to v2
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#1576 chore(gpu): add some scalar ops to dedup benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1508 test(core): add noise formulas and variance tests for KS and PBS
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_keyswitch_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_programmable_boostrapping_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
  tfhe/src/core_crypto/commons/mod.rs
  tfhe/src/core_crypto/commons/noise_formulas/lwe_keyswitch.rs
  tfhe/src/core_crypto/commons/noise_formulas/lwe_programmable_bootstrap.rs
  tfhe/src/core_crypto/commons/noise_formulas/mod.rs
  tfhe/src/core_crypto/commons/noise_formulas/secure_noise.rs
Labels: cla-signed, approved

#1503 feat(integer): add count_ones/zeros
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix_parallel/count_zeros_ones.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_count_zeros_ones.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_count_zeros_ones.rs
Labels: cla-signed, approved

#1567 fix(gpu): add back cuda device synchronize in Drop
  tfhe/src/core_crypto/gpu/vec.rs
Labels: cla-signed, approved

#1577 chore(gpu): print info about inputs in determinism test asserts
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#1550 Al/rework ilog async
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
Labels: cla-signed, approved

#1581 chore: bump tfhe to 0.8.0-alpha.9
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1545 chore(ci): use selenium to run browser wasm tests
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_wasm_client.yml
  .gitignore
  Makefile
  ci/slab.toml
  ci/webdriver.py
  ci/webdriver_requirements.txt
  tfhe/examples/utilities/wasm_benchmarks_parser.rs
  tfhe/web_wasm_parallel_tests/Makefile
  tfhe/web_wasm_parallel_tests/index.html
  tfhe/web_wasm_parallel_tests/index.js
  tfhe/web_wasm_parallel_tests/package-lock.json
  tfhe/web_wasm_parallel_tests/package.json
  tfhe/web_wasm_parallel_tests/test/common.mjs
  tfhe/web_wasm_parallel_tests/test/compact-public-key.test.js
  tfhe/web_wasm_parallel_tests/test/compressed-publik-key-small.test.js
  tfhe/web_wasm_parallel_tests/test/public-key-ct.test.js
  tfhe/web_wasm_parallel_tests/test/server-key.test.js
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, ci

#1531 chore(tfhe): update boolean and shortint parameters
  tfhe/src/boolean/parameters/mod.rs
  tfhe/src/boolean/parameters/params.rs
  tfhe/src/shortint/parameters/classic/compact_pk/gaussian/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/parameters/classic/compact_pk/gaussian/p_fail_2_minus_64/pbs_ks.rs
  tfhe/src/shortint/parameters/classic/gaussian/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/parameters/classic/gaussian/p_fail_2_minus_64/pbs_ks.rs
  tfhe/src/shortint/parameters/classic/tuniform/p_fail_2_minus_64/ks_pbs.rs
  tfhe/src/shortint/parameters/classic/tuniform/p_fail_2_minus_64/pbs_ks.rs
Labels: cla-signed, approved

#1579 feat(gpu): implements fft with reduced shared memory read/write.
  backends/tfhe-cuda-backend/cuda/src/fft/bnsmfft.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#1578 chore(gpu): add bench workflow on L40
  .github/workflows/benchmark_gpu_l40.yml
  ci/ec2_products_cost.json
  ci/slab.toml
Labels: cla-signed, approved

#1583 fix(gpu): fixing plaintext addition
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
Labels: cla-signed, approved

#1590 chore(ci): write gpu parameters to file
  tfhe/examples/utilities/params_to_file.rs
Labels: cla-signed, ci, approved

#1591 chore(gpu): add 2xH100 bench workflow
  .github/workflows/benchmark_gpu_integer_2H100_full.yml
  ci/ec2_products_cost.json
  ci/slab.toml
Labels: cla-signed, approved

#1586 chore(shortint): update multi-bit gpu parameters set
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/ks_pbs_gpu.rs
Labels: cla-signed, approved

#1594 chore(bench): bench 64 bits for ZKs
  tfhe/benches/integer/zk_pke.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1596 chore(gpu): add leading zeros/ones benchmarks
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1593 refactor!: gate wops behind "experimental" feature
  Makefile
  scripts/integer-tests.sh
  scripts/shortint-tests.sh
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/src/integer/keycache.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/wopbs/mod.rs
  tfhe/src/shortint/engine/mod.rs
  tfhe/src/shortint/engine/wopbs/mod.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/mod.rs
  tfhe/src/shortint/wopbs/mod.rs
Labels: cla-signed, approved

#1575 Mz/key conformance
  tfhe/src/core_crypto/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/entities/lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/entities/lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/entities/seeded_ggsw_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_lwe_bootstrap_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_keyswitch_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/compression_keys.rs
  tfhe/src/integer/key_switching_key/mod.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/list_compression/compressed_server_keys.rs
  tfhe/src/shortint/list_compression/mod.rs
  tfhe/src/shortint/list_compression/server_keys.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/multi_bit/mod.rs
  tfhe/src/shortint/server_key/compressed.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed, approved

#1598 chore(gpu): change index array type in decompression
  backends/tfhe-cuda-backend/cuda/include/compression.h
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
Labels: cla-signed

#1599 chore(gpu): add gpu compression in the hl api
  Makefile
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/glwe_packing_compression.rs
  tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/high_level_api/backward_compatibility/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/client_key/radix.rs
  tfhe/src/integer/gpu/list_compression/compressed_server_keys.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed

#1600 chore: bump version for tfhe, tfhe-cuda-backend, tfhe-zk-pok
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe-zk-pok/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, ci, approved

#1429 chore(docs): regroup benchmark pages [WIP]
  tfhe/docs/SUMMARY.md
  tfhe/docs/getting_started/benchmarks.md
  tfhe/docs/getting_started/benchmarks/cpu_benchmarks.md
  tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
  tfhe/docs/getting_started/benchmarks/summary.md
  tfhe/docs/getting_started/benchmarks/zk_proof_benchmarks.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/guides/zk-pok.md
  tfhe/docs/references/fine-grained-apis/shortint/parameters.md
Labels: cla-signed

#1605 fix(gpu): fix end index in gpu compression
  backends/tfhe-cuda-backend/cuda/include/device.h
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#1587 chore(gpu) : add module loading info
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed

#1585 feat(hlapi): Add initial structure of NdArray types
  tfhe/docs/SUMMARY.md
  tfhe/docs/guides/array.md
  tfhe/src/high_level_api/array.rs
  tfhe/src/high_level_api/array/clear_ops.rs
  tfhe/src/high_level_api/array/cpu/booleans.rs
  tfhe/src/high_level_api/array/cpu/integers.rs
  tfhe/src/high_level_api/array/cpu/mod.rs
  tfhe/src/high_level_api/array/dynamic/booleans.rs
  tfhe/src/high_level_api/array/dynamic/mod.rs
  tfhe/src/high_level_api/array/dynamic/signed.rs
  tfhe/src/high_level_api/array/dynamic/unsigned.rs
  tfhe/src/high_level_api/array/helpers.rs
  tfhe/src/high_level_api/array/mod.rs
  tfhe/src/high_level_api/array/ops.rs
  tfhe/src/high_level_api/array/stride.rs
  tfhe/src/high_level_api/array/tests/booleans.rs
  tfhe/src/high_level_api/array/tests/mod.rs
  tfhe/src/high_level_api/array/tests/signed.rs
  tfhe/src/high_level_api/array/tests/unsigned.rs
  tfhe/src/high_level_api/array/traits.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/signed/static_.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/test_user_docs.rs
Labels: cla-signed
