Repository zama-ai/tfhe-rs, pull requests merged in 2024-06, with the labels that each got.

#1193 fix(gpu): ensure `single carry propagation` returns carry
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/neg.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
Labels: cla-signed, approved

#1189 chore(docs): update license FAQ
  README.md
Labels: cla-signed, approved

#1194 chore(gpu): change the number of threads in smart copy, pack blocks and blocks rotate
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Labels: cla-signed, approved

#1188 chore(gpu): parallelize keyswitch further
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/kernel_dimensions.cuh
Labels: cla-signed, approved

#1196 feat(gpu): implement overflowing unsigned add
  tfhe/benches/integer/bench.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
Labels: cla-signed, approved

#1200 chore(bench): add pbs128 to benchmarks suite
  .github/workflows/core_crypto_benchmark.yml
  Makefile
  tfhe/Cargo.toml
  tfhe/benches/core_crypto/pbs128_bench.rs
Labels: cla-signed

#1123 refactor(tfhe): Allow CompactCiphertextList to store heterogeneous types
  tfhe/c_api_tests/test_high_level_compact_list.c
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/c_api_tests/test_high_level_zk.c
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/guides/zk-pok.md
  tfhe/examples/utilities/hlapi_compact_pk_ct_sizes.rs
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
  tfhe/src/c_api/high_level_api/booleans.rs
  tfhe/src/c_api/high_level_api/compact_list.rs
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/booleans/compact.rs
  tfhe/src/high_level_api/booleans/mod.rs
  tfhe/src/high_level_api/booleans/tests.rs
  tfhe/src/high_level_api/booleans/zk.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/errors.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/signed/compact.rs
  tfhe/src/high_level_api/integers/signed/mod.rs
  tfhe/src/high_level_api/integers/signed/static_.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/signed/zk.rs
  tfhe/src/high_level_api/integers/unsigned/compact.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/integers/unsigned/zk.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/mod.rs
  tfhe/src/integer/parameters/mod.rs
  tfhe/src/integer/public_key/compact.rs
  tfhe/src/integer/public_key/tests.rs
  tfhe/src/integer/zk.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
  tfhe/src/safe_deserialization.rs
  tfhe/src/shortint/ciphertext/zk.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/web_wasm_parallel_tests/index.html
  tfhe/web_wasm_parallel_tests/index.js
  tfhe/web_wasm_parallel_tests/test/compact-public-key.test.js
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1209 fix(gpu): fix cuda bench warnings
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_fft.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/utils.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/setup_and_teardown.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/utils.cpp
Labels: cla-signed, approved

#1208 chore(bench): add benchmarks for pbs-ntt64
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, approved

#1213 chore(bench): fix naming pattern on if_then_else cuda benchmark
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1205 fix(gpu): use all gpus in omp loops
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
Labels: cla-signed

#1212 GPU fix: use different streams in if_then_else for OMP loop
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
Labels: cla-signed

#1206 fix(test): there was a typo in a feature name not picked up by clippy
  tfhe/src/integer/ciphertext/compact_list.rs
Labels: cla-signed, approved

#1199 feat(core): add keyswitch that changes the scalar type from input to output
  tfhe/src/core_crypto/algorithms/lwe_keyswitch.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch.rs
Labels: cla-signed, approved

#1216 chore(gpu): fix warnings in pcc_gpu
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_fft.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
Labels: cla-signed, approved

#1215 chore(gpu): removed unused dependency
  backends/tfhe-cuda-backend/Cargo.toml
Labels: cla-signed, approved

#1221 chore(continuous-integration): change commit regex to allow hyphen in scope
  .github/workflows/check_commit.yml
Labels: cla-signed, approved

#1214 refactor(tfhe): create associated CompactPrivateKey and prepare casting
  tfhe/c_api_tests/test_high_level_compact_list.c
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/docs/fundamentals/compress.md
  tfhe/docs/guides/public_key.md
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/src/c_api/high_level_api/booleans.rs
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/integers/signed/encrypt.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/unsigned/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/encryption.rs
  tfhe/src/integer/public_key/compact.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
  tfhe/src/shortint/ciphertext/compact_list.rs
  tfhe/src/shortint/ciphertext/zk.rs
  tfhe/src/shortint/parameters/compact_public_key_only.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/src/shortint/server_key/tests/shortint_compact_pk.rs
Labels: cla-signed, approved

#1217 Refactor signed overflow add sub tests
  tfhe/src/integer/server_key/radix/add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
Labels: cla-signed, approved

#1218 feat(tfhe): add FheUint2048
  tfhe/c_api_tests/test_high_level_2048.c
  tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/c_api/high_level_api/u2048.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/bigint/mod.rs
  tfhe/src/integer/bigint/static_unsigned.rs
  tfhe/src/integer/bigint/u256.rs
  tfhe/src/integer/bigint/u512.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
Labels: cla-signed, approved

#1203 feat(core): add variable Scalar type to PBS for input and output
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/fft64.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
Labels: cla-signed, approved

#1226 chore(ci): update slab-github-runner action
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1229 chore(gpu): update gpu parameters
  tfhe/src/shortint/parameters/multi_bit/mod.rs
  tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_40/mod.rs
  tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/ks_pbs_gpu.rs
  tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/mod.rs
Labels: cla-signed

#1234 feat(gpu): Implement unsigned_overflowing_scalar_add
  tfhe/benches/integer/bench.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved

#1238 chore(ci): reduce number of keys generated in keycache
  tfhe/examples/utilities/generates_test_keys.rs
Labels: m1_test, cla-signed, approved

#1237 chore(gpu): add apply bivariate lut as entry point on the rust side
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed, approved

#1241 chore(ci): manage the memory issues we are seeing
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/m1_tests.yml
  scripts/shortint-tests.sh
  tfhe/src/integer/keycache.rs
Labels: cla-signed, approved

#1248 fix(c-api): bind encrypt CompactFheUint2048List
  tfhe/Cargo.toml
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/guides/migrate_data.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
  tfhe/src/c_api/high_level_api/integers.rs
Labels: cla-signed, approved

#1105 feat(zk): impl CanonicalSerialize/Deserialize
  tfhe-zk-pok/src/curve_api.rs
  tfhe-zk-pok/src/curve_api/bls12_381.rs
  tfhe-zk-pok/src/curve_api/bls12_446.rs
  tfhe-zk-pok/src/lib.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/src/c_api/high_level_api/zk.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/zk.rs
  tfhe/src/zk.rs
Labels: cla-signed, approved

#1228 512,1024,2048
  tfhe/c_api_tests/test_high_level_2048.c
  tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/c_api/high_level_api/u1024.rs
  tfhe/src/c_api/high_level_api/u2048.rs
  tfhe/src/c_api/high_level_api/u512.rs
  tfhe/src/c_api/high_level_api/utils.rs
  tfhe/src/high_level_api/integers/mod.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/bigint/mod.rs
  tfhe/src/integer/bigint/static_unsigned.rs
  tfhe/src/integer/bigint/u256.rs
  tfhe/src/integer/bigint/u512.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
Labels: cla-signed, approved

#1255 chore(doc): update benchmarks timings
  tfhe/docs/getting_started/benchmarks.md
  tfhe/docs/guides/run_on_gpu.md
Labels: documentation, cla-signed

#1256 chore(doc): remove old cpu benchmarks arrays
  tfhe/docs/getting_started/benchmarks.md
Labels: documentation, cla-signed, approved

#1253 Ns/0.6/core crypto versionize
  tfhe/src/core_crypto/backward_compatibility/entities/ggsw_ciphertext.rs
  tfhe/src/core_crypto/backward_compatibility/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/backward_compatibility/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/backward_compatibility/entities/lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/backward_compatibility/entities/lwe_private_functional_packing_keyswitch_key.rs
  tfhe/src/core_crypto/backward_compatibility/entities/mod.rs
  tfhe/src/core_crypto/backward_compatibility/entities/seeded_ggsw_ciphertext.rs
  tfhe/src/core_crypto/backward_compatibility/entities/seeded_glwe_ciphertext_list.rs
  tfhe/src/core_crypto/backward_compatibility/entities/seeded_lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/entities/ggsw_ciphertext.rs
  tfhe/src/core_crypto/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/entities/lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/entities/lwe_private_functional_packing_keyswitch_key.rs
  tfhe/src/core_crypto/entities/seeded_ggsw_ciphertext.rs
  tfhe/src/core_crypto/entities/seeded_glwe_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_lwe_packing_keyswitch_key.rs
Labels: cla-signed, approved

#1247 feat(zk): improve performance of zk pke proofs
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/src/curve_446/mod.rs
  tfhe-zk-pok/src/curve_api.rs
  tfhe-zk-pok/src/curve_api/bls12_381.rs
  tfhe-zk-pok/src/curve_api/bls12_446.rs
  tfhe-zk-pok/src/curve_api/msm.rs
  tfhe-zk-pok/src/proofs/binary.rs
  tfhe-zk-pok/src/proofs/index.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/range.rs
  tfhe-zk-pok/src/proofs/rlwe.rs
Labels: cla-signed, approved

#1260 fix(shortint): count PBS in trivial_many_lut
  tfhe/src/shortint/server_key/mod.rs
  tfhe/src/shortint/server_key/tests/parametrized_test.rs
Labels: cla-signed, approved

#1257 chore(gpu): Add bitnot operation without using pbs
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cu
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
Labels: cla-signed

#1265 chore(ci): update gpu ec2 ami with rustup snap package removed
  ci/slab.toml
Labels: cla-signed, ci, approved

#1267 chore(ci): update npm packages
  tfhe/web_wasm_parallel_tests/package-lock.json
Labels: cla-signed, approved

#1266 chore(gpu): bump cuda backend version
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1259 feat(zk): add randomness to hash functions
  tfhe-zk-pok/src/proofs/binary.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/range.rs
  tfhe-zk-pok/src/proofs/rlwe.rs
Labels: cla-signed, approved

#1268 chore(tfhe): mark zk-pok as non experimental
  Makefile
  scripts/integer-tests.sh
  scripts/shortint-tests.sh
  tfhe/Cargo.toml
  tfhe/build.rs
  tfhe/docs/guides/zk-pok.md
  tfhe/src/c_api/high_level_api/compact_list.rs
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/mod.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/entities/mod.rs
  tfhe/src/error.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/mod.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/integers.rs
  tfhe/src/js_on_wasm_api/js_high_level_api/mod.rs
  tfhe/src/lib.rs
  tfhe/src/shortint/ciphertext/mod.rs
  tfhe/src/shortint/engine/mod.rs
  tfhe/src/shortint/public_key/compact.rs
Labels: cla-signed, approved

#1272 chore(docs): fix broken links
  tfhe/docs/core_crypto/presentation.md
Labels: cla-signed, approved

#1271 doc: fix broken links for docs 0.5
  tfhe/docs/core_crypto/presentation.md
  tfhe/docs/how_to/run_on_gpu.md
Labels: cla-signed, approved

#1263 Add doc for the versioning/backward compat feature
  tfhe/docs/SUMMARY.md
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/guides/data_versioning.md
  tfhe/docs/guides/migrate_data.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#1277 doc: compression updates
  tfhe/docs/fundamentals/compress.md
Labels: cla-signed, approved

#1273 chore(tfhe): update multi bit parameters
  tfhe/src/shortint/parameters/multi_bit/p_fail_2_minus_64/ks_pbs.rs
Labels: cla-signed, approved

#1283 chore(doc): add missing doc for a data breaking change
  tfhe/docs/guides/data_versioning.md
Labels: cla-signed

#1291 chore(ci): update slab-github-runner action
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/wasm_client_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1292 chore(bench): fix display name for gpu unsigned integer operations
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1289 chore(ci): update slab-github-runner action
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/wasm_client_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1295 chore(ci): avoid cancel ongoing benchmarks on main branch
  .github/workflows/gpu_4090_full_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1284 chore(ci): run build workflow on large instances
  .github/actionlint.yaml
  .github/workflows/cargo_build.yml
Labels: cla-signed, ci, approved

#1298 chore(ci): publish only one tag for npm packages
  .github/workflows/make_release.yml
Labels: cla-signed, ci, approved

#1296 feat(zk): zk perf improvements
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/src/curve_api/bls12_446.rs
Labels: cla-signed, approved

#1306 chore(gpu): call nvidia-smi before launching tests on hyperstack
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
Labels: cla-signed, approved

#1305 feat(gpu): Implement propagate_single_carry_get_input_carries
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#1270 Al/fix gpu index
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Labels: cla-signed

#1304 chore(zk): bump version to 0.2.1 for perf patch release
  tfhe-zk-pok/Cargo.toml
Labels: cla-signed, approved

#1301 chore(ci): run full multi-bit gpu benchmarks on demand
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
Labels: cla-signed, ci, approved

#1307 chore(bench): fix naming pattern for zk-pok benchmarks
  tfhe/benches/integer/zk_pke.rs
Labels: cla-signed, approved

#1288 chore(gpu): use byte add, update rust msrv
  tfhe/Cargo.toml
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/slice.rs
  tfhe/src/core_crypto/gpu/vec.rs
Labels: cla-signed, approved

#1314 doc: udpate pfail README
  README.md
Labels: cla-signed

#1312 doc: udpate pfail README
  README.md
Labels: cla-signed, approved

#1282 refactor(shortint): move scalar_div_mod to its own modulue
  tfhe/src/shortint/server_key/div_mod.rs
  tfhe/src/shortint/server_key/mod.rs
  tfhe/src/shortint/server_key/scalar_div_mod.rs
Labels: cla-signed, approved

#1310 refactor(integer): move sum functions into their own module
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/sum.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sum.rs
Labels: cla-signed, approved

#1321 chore(ci): reduce ci duration by not running 4_4 parameters set
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  scripts/integer-tests.sh
  scripts/test_filtering.py
Labels: cla-signed, ci, approved

#1322 feat(perf): optimize some custom mod ops
  tfhe/src/core_crypto/commons/math/decomposition/decomposer.rs
  tfhe/src/core_crypto/commons/numeric/unsigned.rs
Labels: cla-signed, approved
