Repository zama-ai/tfhe-rs, pull requests merged in 2024-11, with the labels that each got.

#1745 chore(ci): fix clippy issue for M1 build
  concrete-csprng/src/seeders/implem/apple_secure_enclave_seeder.rs
Labels: cla-signed, approved

#1746 chore(gpu): remove decompressed ct comparison btw cpu and gpu
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#1752 chore(gpu): increase sm for rtxa6000
  backends/tfhe-cuda-backend/cuda/src/device.cu
Labels: cla-signed, approved

#1750 chore(zk): add a proof compat test between x86_64 and wasm
  .github/workflows/aws_tfhe_wasm_tests.yml
  .gitignore
  Makefile
  tfhe/js_on_wasm_tests/package.json
  tfhe/tests/zk_wasm_x86_test.rs
  tfhe/tests/zk_wasm_x86_test/index.js
  tfhe/tests/zk_wasm_x86_test/package.json
  tfhe/web_wasm_parallel_tests/package.json
Labels: cla-signed, approved

#1754 chore(gpu): add workflows for erc20 bench with 2 and 8 H100
  .github/workflows/benchmark_gpu_erc20_2h100.yml
  .github/workflows/benchmark_gpu_erc20_8h100.yml
Labels: cla-signed, approved

#1753 chore(zk): update arkworks to 0.5.0
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/src/curve_446/mod.rs
Labels: cla-signed, approved

#1717 chore: make more add/sub test use variable num_blocks
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#1759 chore(ci): enable safe_serialization tests
  .github/workflows/aws_tfhe_fast_tests.yml
  Makefile
Labels: cla-signed, approved

#1758 doc: update the doc with the new msrv
  README.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/guides/rust_configuration.md
Labels: cla-signed, approved

#1761 fix(zk): fix build with feature zk-pok without shortint
  Makefile
  tfhe/src/zk.rs
Labels: cla-signed, approved

#1762 chore(ci): use function executor for abs and signed div tests
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_abs.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_div_rem.rs
Labels: cla-signed, approved

#1764 test: add tag check for parameter keyswitch in HL API
  tfhe/src/high_level_api/tests/tags_on_entities.rs
Labels: cla-signed, approved

#1768 chore(gpu): trigger GPU tests if tests are modified
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#1770 chore(ci): run bench profile as ubuntu
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_zk_pke.yml
  ci/slab.toml
Labels: cla-signed, approved

#1751 fix(gpu): general fixes and improvements to PBS
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
Labels: cla-signed, approved

#1721 chore(gpu): use same balanced decomposition code as in the CPU code
  backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
Labels: cla-signed, approved

#1776 chore(gpu): change target for multi-gpu tests
  ci/slab.toml
Labels: cla-signed, approved

#1778 fix(gpu): fix signed overflowing sub for one block case
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
Labels: cla-signed, approved, 4090_test

#1779 chore(gpu): remove 3_3 group 2 tests to gain time in the ci
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
Labels: cla-signed, approved

#1773 chore(gpu): simplifications to the zero_out_if method
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#1757 chore: add parameters getters for CompactPublicKey types
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/public.rs
  tfhe/src/integer/public_key/compact.rs
  tfhe/src/shortint/public_key/compact.rs
Labels: cla-signed, approved

#1777 feat(gpu): Implement abs operation on gpu backend
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cu
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/abs.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_abs.rs
Labels: cla-signed, approved

#1780 chore(gpu): update asserts on base log now that we don't cast to u32 in decomposition
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
Labels: cla-signed, approved

#1785 chore(ci): fix bash script
  scripts/c_api_tests.sh
Labels: cla-signed, approved

#1781 fix(core): fix compact pke with single lwe
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
Labels: cla-signed, approved

#1771 Ns/bench tfhe zk pok
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .gitignore
  Makefile
  ci/benchmark_parser.py
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/benches/pke_v1.rs
  tfhe-zk-pok/benches/pke_v2.rs
  tfhe-zk-pok/benches/utils.rs
  tfhe-zk-pok/src/proofs/mod.rs
Labels: cla-signed, approved

#1790 chore(bench): fix fft bench
  .github/workflows/benchmark_tfhe_fft.yml
Labels: cla-signed, approved

#1791 chore(bench): fix fft bench again
  .github/workflows/benchmark_tfhe_fft.yml
Labels: cla-signed

#1796 chore(ci): fix fft bench parser
  ci/fft_benchmark_parser.py
Labels: cla-signed, approved

#1794 chore(ci): do not run fft workflows on push to main
  .github/workflows/cargo_build_tfhe_fft.yml
  .github/workflows/cargo_test_fft.yml
Labels: cla-signed, approved

#1797 feat(gpu): Implement signed division in cuda backend
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_div_mod.rs
Labels: cla-signed, approved

#1793 fix(hlapi): rework CompressedCiphertextListBuilder
  tfhe/src/high_level_api/booleans/inner.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
Labels: cla-signed, approved

#1806 chore(ci): refacto gpu bench workflows to reduce duplicates
  .github/workflows/benchmark_gpu_integer.yml
  .github/workflows/benchmark_gpu_integer_2H100_full.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/benchmark_gpu_integer_multi_bit.yml
  .github/workflows/benchmark_gpu_integer_multi_bit_multi_gpu.yml
  .github/workflows/benchmark_gpu_integer_multi_gpu_full.yml
  .github/workflows/benchmark_gpu_integer_weekly.yml
  .github/workflows/benchmark_gpu_l40.yml
Labels: ci, approved

#1807 chore(ci): fix gpu integer benchmark workflow
  .github/workflows/benchmark_gpu_integer.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/benchmark_gpu_integer_weekly.yml
Labels: ci, approved

#1816 chore(ci): fix gpu multi values ops flavor parsing
  .github/workflows/benchmark_gpu_integer_common.yml
Labels: ci, approved

#1763 feat(gpu): improve full propagation in sum and sub
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/neg.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
Labels: cla-signed, approved

#1805 Al/long run tests
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/integer_long_run_tests.yml
  Makefile
  tfhe/Cargo.toml
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_erc20.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_erc20.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
Labels: approved

#1817 fix: zk-pok bench workflow using an invalid argument
  .github/workflows/benchmark_tfhe_zk_pok.yml
Labels: approved

#1809 Ns/zk test bad ct
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: approved

#1820 chore(gpu): panic if (k + 1)*l > 8 to avoid issue with tbc
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: approved

#1678 fix(ci): fix secret on CI checkout
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/make_release.yml
  .github/workflows/make_release_concrete_csprng.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_tfhe_versionable.yml
  .github/workflows/make_release_zk_pok.yml
  .github/workflows/sync_on_push.yml
Labels: cla-signed, approved

#1788 Tm/fix sub signed overflow
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
Labels: cla-signed, approved

#1800 Fix: degree for min max
  tfhe/src/integer/server_key/comparator.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/shortint/ciphertext/common.rs
Labels: cla-signed

#1828 chore(ci): add debug mode to shortint test script for easier debug later
  scripts/shortint-tests.sh
Labels: cla-signed, approved

#1830 chore: fix c test on arm64
  tfhe/c_api_tests/test_shortint_pbs.c
Labels: cla-signed, approved

#1829 docs(wasm): add information for web bundlers
  tfhe/docs/guides/js_on_wasm_api.md
Labels: cla-signed, approved

#1833 chore(ci): run fft/ntt bench on push only if certain files changed
  .github/workflows/benchmark_tfhe_fft.yml
  .github/workflows/benchmark_tfhe_ntt.yml
Labels: cla-signed, ci, approved

#1819 chore(zk): add a test with a bad delta for encryption
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#1832 chore(gpu): replace inneficient log2 implementation and use it everyw…
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/polynomial/parameters.cuh
Labels: cla-signed
