Repository zama-ai/tfhe-rs, pull requests merged in 2024-10, with the labels that each got.

#1609 feat(versionable): impl Versionize for `Vec<Vec<T>>`
  utils/tfhe-versionable/src/lib.rs
  utils/tfhe-versionable/tests/types.rs
Labels: cla-signed, approved

#1610 chore(gpu): add ks/pbs benchmarks in the documentation
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/docs/getting_started/benchmarks/gpu_benchmarks.md
Labels: cla-signed, approved

#1612 fix(hlapi): pub use HlCompressible,HlExpandable
  tfhe/src/high_level_api/mod.rs
Labels: cla-signed, approved

#1615 fix(gpu): remove extra single carry propagation from partial sum
  tfhe/src/integer/gpu/server_key/radix/add.rs
Labels: cla-signed, approved

#1588 chore(gpu): reset all test thread values
  .github/workflows/gpu_fast_h100_tests.yml
  Makefile
  scripts/integer-tests.sh
Labels: cla-signed, approved

#1613 chore(ci): fix wasm benchmark results parsing for object sizes
  tfhe/examples/utilities/wasm_benchmarks_parser.rs
Labels: cla-signed, ci, approved

#1614 feat(cuda): modify double to torus cast and normalization for bsk
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
  backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
Labels: cla-signed, approved

#1622 chore(gpu): do not unwrap in blocks_of, to have the same behavior as the CPU
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#1607 fix(gpu): fixes to compression
  backends/tfhe-cuda-backend/cuda/include/ciphertext.h
  backends/tfhe-cuda-backend/cuda/include/compression.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cu
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed, approved

#1623 chore(gpu): increase max sm size again to gain performance on 3_3 params on H100
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
Labels: cla-signed, approved

#1552 feat(gpu): add a benchmark for packing keyswitch
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_packing_keyswitch.rs
Labels: cla-signed, approved

#1604 chore(bench): add a compression bench for 2 bits (also simulates 1 bit)
  tfhe/benches/integer/glwe_packing_compression.rs
Labels: cla-signed, approved

#1641 chore(gpu): force cargo profile to release to build cuda tests & benches
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/CMakeLists.txt
Labels: cla-signed, approved

#1645 chore(versionable): prepare release 0.3.1
  utils/tfhe-versionable-derive/Cargo.toml
  utils/tfhe-versionable/Cargo.toml
Labels: cla-signed, approved

#1640 chore(ci): remove symlinking of the dynamic buffer API
  Makefile
  scripts/symlink_c_libs_without_fingerprint.sh
Labels: cla-signed, approved

#1648 chore(ci): add dry run mode to tfhe-versionable releases
  .github/workflows/make_release_tfhe_versionable.yml
Labels: cla-signed, approved

#1639 chore(ci): add firefox support for wasm tests and benchmarks
  .github/workflows/benchmark_wasm_client.yml
  Makefile
  ci/webdriver.py
Labels: cla-signed, ci, approved

#1626 chore(hlapi): remove useless flags
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/static_.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/static_.rs
Labels: cla-signed, approved

#1652 chore(ci): fix webdriver install in wasm benchmarks
  .github/workflows/benchmark_wasm_client.yml
Labels: cla-signed, ci, approved

#1627 chore(all): enforce polynomial size to be a power of 2
  tfhe/src/core_crypto/commons/parameters.rs
Labels: cla-signed, approved

#1651 fix(gpu): fix sample extract many lut use case
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed

#1638 fix(gpu): fix rtx 4090 tests
  backends/tfhe-cuda-backend/cuda/src/device.cu
Labels: cla-signed, approved

#1643 chore(gpu): panic in single carry prop if message modulus is 2 (1_1 params)
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#1654 chore(ci): fix browser identification on wasm benchmarks
  ci/webdriver.py
Labels: cla-signed, ci, approved

#1642 chore(gpu): limit base log to 32 because of int32 cast in decomposition
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#1658 feat(core_crypto): impl Named for LweSecretKey and GlweSecretKey
  tfhe/src/core_crypto/entities/glwe_secret_key.rs
  tfhe/src/core_crypto/entities/lwe_secret_key.rs
Labels: cla-signed, approved

#1655 chore(csprng): fix clippy warning on M1
  concrete-csprng/src/generators/implem/aarch64/parallel.rs
Labels: cla-signed, approved

#1661 backport impl Named for LweSecretKey and GlweSecretKey
  tfhe/src/core_crypto/entities/glwe_secret_key.rs
  tfhe/src/core_crypto/entities/lwe_secret_key.rs
Labels: cla-signed, approved

#1634 chore(integer): brings the CPU and GPU tests into line.
  Makefile
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  tfhe/docs/fundamentals/compress.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
  tfhe/src/core_crypto/entities/packed_integers.rs
  tfhe/src/high_level_api/tests/tags_on_entities.rs
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/list_compression.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#1647 feat(integer): improve shift/rotate by encrypted amount
  tfhe/src/integer/server_key/radix_parallel/bit_extractor.rs
  tfhe/src/integer/server_key/radix_parallel/block_shift.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/rotate.rs
  tfhe/src/integer/server_key/radix_parallel/shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_rotate.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_shift.rs
Labels: cla-signed, approved

#1676 chore(gpu): make to_glwe_ciphertext_list pub
  tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
Labels: cla-signed

#1666 fix(hlapi): CompressedCiphertextList::get_kind_of
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#1682 fix(gpu): fix default pbs with many luts
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#1679 chore(ci): enforce commit signature for PRs
  .github/workflows/check_commit.yml
Labels: cla-signed, approved

#1675 chore(gpu): print inputs to more determinism tests for debugging purp…
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_ilog2.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_div_mod.rs
Labels: cla-signed, approved

#1685 fix(gpu): add template parameter to packing keyswitch calls
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
Labels: cla-signed

#1681 feat(serialization): add safe_serialized_size
  tfhe/src/safe_serialization.rs
Labels: cla-signed, approved

#1683 chore(ci): fix firefox wasm benchmarks with new aws ami
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_wasm_client.yml
  Makefile
  ci/slab.toml
Labels: cla-signed, ci, approved

#1686 chore(all): update MSRV to 1.81
  tfhe/Cargo.toml
  utils/tfhe-versionable/Cargo.toml
Labels: cla-signed, approved

#1689 chore(ci): rename benchmark parsing option to object-sizes
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_gpu_erc20.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_zk_pke.yml
  ci/benchmark_parser.py
Labels: cla-signed, ci, approved

#1684 chore: fix some overflow related panics
  tfhe/src/integer/bigint/algorithms.rs
  tfhe/src/integer/bigint/static_signed.rs
  tfhe/src/integer/bigint/static_unsigned.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/shortint/server_key/tests/parametrized_test.rs
Labels: cla-signed, approved

#1693 chore(ci): run aws workflows as ubuntu user
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/csprng_randomness_tests.yml
  ci/slab.toml
Labels: cla-signed, ci, approved

#1695 fix(serialization): serialized_size_limit includes the header
  tfhe/src/safe_serialization.rs
Labels: cla-signed, approved

#1629 remove noise level from CompactCt
  tfhe/src/shortint/backward_compatibility/ciphertext/mod.rs
  tfhe/src/shortint/ciphertext/compact_list.rs
  tfhe/src/shortint/ciphertext/zk.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/public_key/compact.rs
Labels: cla-signed, approved

#1694 chore(ci): make build script regenerate bindings at all times
  Makefile
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/src/bindings.rs
Labels: cla-signed, approved

#1597 Ns/refactor zk tests
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#1703 chore: fix typos
  apps/trivium/README.md
  concrete-csprng/README.md
Labels: cla-signed, approved

#1705 chore(docs): seen some diffs during a merge, uniformizing toml blocks
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/guides/data_versioning.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
Labels: cla-signed, approved

#1706 feat(wasm): export safe_deserialize for CompactPkePublicParams
  tfhe/src/js_on_wasm_api/js_high_level_api/zk.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1708 fix(wasm): fix size used for serialization in benches
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1709 backport: fix size used for serialization in benches
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1646 chore(integer): add a test to check that a malicious list is sanitized
  tfhe/src/integer/ciphertext/compact_list.rs
Labels: cla-signed, approved

#1710 chore(backward): use the Deprecated type from tfhe-versionable
  tfhe/src/core_crypto/backward_compatibility/entities/seeded_lwe_keyswitch_key.rs
  tfhe/src/core_crypto/backward_compatibility/entities/seeded_lwe_packing_keyswitch_key.rs
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/integer/backward_compatibility/key_switching_key.rs
  tfhe/src/integer/backward_compatibility/list_compression.rs
  tfhe/src/integer/backward_compatibility/server_key/mod.rs
  tfhe/src/shortint/backward_compatibility/key_switching_key.rs
  tfhe/src/shortint/backward_compatibility/list_compression.rs
  tfhe/src/shortint/backward_compatibility/server_key/mod.rs
Labels: cla-signed, approved

#1700 fix(fhe_strings): fix size error
  tfhe/examples/fhe_strings/server_key/pattern/replace.rs
  tfhe/examples/fhe_strings/server_key/trim.rs
Labels: cla-signed, approved

#1712 chore(core): remove the fmadd split accumulation
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
Labels: cla-signed, approved

#1702 chore(bench): add packing keyswtich benchmarks
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/integer/glwe_packing_compression.rs
  tfhe/benches/utilities.rs
  tfhe/examples/utilities/shortint_key_sizes.rs
Labels: cla-signed, approved

#1711 fix(core): fix decomposition over 1 level to be balanced
  tfhe/src/core_crypto/commons/math/decomposition/decomposer.rs
  tfhe/src/core_crypto/commons/math/decomposition/iter.rs
  tfhe/src/core_crypto/commons/math/decomposition/tests.rs
  tfhe/src/core_crypto/experimental/algorithms/glwe_fast_keyswitch.rs
  tfhe/src/core_crypto/fft_impl/fft128/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft128_u128/crypto/tests.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/ggsw.rs
  tfhe/src/core_crypto/fft_impl/fft64/math/decomposition.rs
Labels: cla-signed, approved

#1720 chore(ci): update chrome version
  Makefile
Labels: cla-signed, approved

#1631 regroup optionals in proofs
  tfhe-zk-pok/src/backward_compatibility/mod.rs
  tfhe-zk-pok/src/backward_compatibility/pke.rs
  tfhe-zk-pok/src/backward_compatibility/pke_v2.rs
  tfhe-zk-pok/src/curve_api.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
  tfhe-zk-pok/src/proofs/rlwe.rs
  tfhe/src/shortint/ciphertext/zk.rs
Labels: cla-signed, approved

#1724 chore(bench): skip tuniform parameters for pbs with ntt
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, approved

#1723 chore(ci): verify commit on release
  .github/workflows/make_release.yml
  .github/workflows/make_release_concrete_csprng.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_tfhe_versionable.yml
  .github/workflows/make_release_zk_pok.yml
  .github/workflows/verify_tagged_commit.yml
Labels: cla-signed, ci, approved

#1734 chore(ci): update version of selenium to 4.26.0
  ci/webdriver_requirements.txt
Labels: cla-signed, ci, approved

#1725 chore(gpu): restrict should run
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#1737 chore(gpu): restrict bindings generation
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/wrapper.h
Labels: cla-signed, approved

#1728 chore(docs): fix the survey format
  tfhe/docs/README.md
Labels: cla-signed, approved

#1727 chore(docs): fix the survey format
  tfhe/docs/README.md
Labels: cla-signed, approved

#1726 chore(docs): fix a format issue
  tfhe/docs/README.md
Labels: cla-signed, approved

#1736 fix(gpu): fix memory error in cg classical PBS
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
Labels: cla-signed, approved

#1739 chore(scope): no longer check macOS version
  concrete-csprng/src/seeders/implem/apple_secure_enclave_seeder.rs
Labels: cla-signed, approved
