Repository zama-ai/tfhe-rs, pull requests merged in 2024-07, with the labels that each got.

#1332 chore(doc): add the GPU video tutorial to doc
  tfhe/docs/tutorials/see-all-tutorials.md
Labels: cla-signed, approved

#1335 chore(doc): add the GPU video tutorial to doc
  tfhe/docs/tutorials/see-all-tutorials.md
Labels: cla-signed

#1338 chore(ci): lock version of wasm-pack to fix tfhe-rs build
  Makefile
Labels: cla-signed, ci, approved

#1300 chore(bench): add benchmarks for integer oprf
  Makefile
  tfhe/Cargo.toml
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/oprf.rs
Labels: cla-signed, approved

#1337 chore(bench):fix filtering for unsigned integer cuda benchmarks
  Makefile
  tfhe/benches/integer/bench.rs
Labels: cla-signed, approved

#1339 chore(ci): lock version of wasm-pack to fix tfhe-rs build
  Makefile
Labels: cla-signed, ci, approved

#1340 refactor(gpu): start releasing memory before cleanup in scalar mul
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
Labels: cla-signed, approved

#1348 chore(ci): use large ubuntu runner to get more disk space
  .github/actionlint.yaml
  .github/workflows/cargo_build.yml
Labels: cla-signed, ci, approved

#1349 chore(ci): check labels to launch only on approval
  .github/workflows/aws_tfhe_integer_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_gpu_tests.yml
  .github/workflows/aws_tfhe_tests.yml
Labels: cla-signed, ci, approved

#1350 chore(ci): update slab-github-runner to latest version
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/wasm_client_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1351 chore(tfhe): bump version to 0.8.0
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/guides/data_versioning.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
Labels: cla-signed

#1353 chore(gpu): reduce integer bench time
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/signed_bench.rs
Labels: cla-signed, approved

#1355 chore(ci): check for files changes to run fast aws tests
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_tests.yml
Labels: cla-signed, ci, approved

#1358 chore(bench): benchmark oprf function against all available precisions
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/oprf.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#1356 chore(gpu): fix unsigned ci tests
  scripts/integer-tests.sh
Labels: cla-signed, approved

#1336 Al/optimize multiplication memory usage
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed

#1341 chore(gpu): pin bsk host memory
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
Labels: cla-signed

#1359 chore(bench): create modules to avoid headaches with features in utils
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#1347 feat(gpu): implement signed_overflowing_add
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_add.rs
Labels: cla-signed

#1363 chore(ci): fix the no internal test patch
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
Labels: cla-signed, approved

#1365 chore(ci): fix test filtering for gpu multi-bit parameters set
  scripts/test_filtering.py
Labels: cla-signed, ci, approved

#1364 fix(gpu): add missing delete
  backends/tfhe-cuda-backend/cuda/include/integer.h
Labels: cla-signed, approved

#1369 chore(gpu): clean overflowing sub memory
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
Labels: cla-signed, approved

#1370 chore(gpu): remove unnecessary templates
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cu
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
Labels: cla-signed, approved

#1376 chore(ci): update slab-github-runner action
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/wasm_client_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1375 chore(ci): update slab-github-runner action
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_pcc.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/code_coverage.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/wasm_client_benchmark.yml
  .github/workflows/zk_pke_benchmark.yml
Labels: cla-signed, ci, approved

#1371 chore(gpu): fix some int_radix_luts numbers of blocks
  backends/tfhe-cuda-backend/cuda/include/integer.h
Labels: cla-signed, approved

#1374 Ns/vesionize hl ksk
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
Labels: cla-signed, approved

#1281 Chore/add slsa framework
  .github/workflows/make_release.yml
Labels: cla-signed, approved

#1377 feat(hl): add serialize/versionize for hl KSK
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
Labels: cla-signed, approved

#1380 chore(ci): pin node version, 22.5 is affected by a bug
  Makefile
Labels: cla-signed, approved

#1381 chore(ci): generate lockfile before packaging
  .github/workflows/make_release.yml
Labels: cla-signed, approved

#1385 chore(ci): do not block integer tests due to concurrency on push to main
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
Labels: cla-signed, approved

#1372 chore(ci): add should-run capability for gpu workflows
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_gpu_tests.yml
  .github/workflows/aws_tfhe_multi_gpu_tests.yml
  .github/workflows/aws_tfhe_signed_integer_gpu_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
Labels: cla-signed, ci

#1387 Ns/unversionize ksk
  tfhe/src/high_level_api/backward_compatibility/keys.rs
  tfhe/src/high_level_api/keys/key_switching_key.rs
Labels: cla-signed, approved

#1383 chore(gpu): remove stream callbacks
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#1368 chore(backward): allow custom data repo branch for tests
  Makefile
Labels: cla-signed

#1386 chore(ci): fix nvm version usage for web parallel tests
  Makefile
Labels: cla-signed, approved

#1388 refactor(gpu): add restrict and const keywords
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstraping_key.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
Labels: cla-signed, approved

#1391 chore(ci): do not trigger notification if bench did not run
  .github/workflows/integer_gpu_benchmark.yml
Labels: cla-signed

#1390 chore(bench): increase wasm bench timeout
  tfhe/web_wasm_parallel_tests/test/server-key.test.js
Labels: cla-signed, approved

#1394 fix(gpu): add missing delete
  backends/tfhe-cuda-backend/cuda/include/integer.h
Labels: cla-signed, approved

#1393 feat(gpu): Add signed_overflowing_sub in cuda backend
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_sub.rs
Labels: cla-signed, approved

#1399 feat(gpu): Add signed_overflowing_scalar_add and signed_overflowing_scalar_sub on cuda backend
  tfhe/benches/integer/signed_bench.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
Labels: cla-signed, approved

#1227 Multi GPU: dispatch/gather inputs and outputs to the ks/pbs on all GPUs
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/include/integer.h
  backends/tfhe-cuda-backend/cuda/include/keyswitch.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  ci/ec2_products_cost.json
  ci/slab.toml
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#1409 chore(docs): add links to CompressedServerKey in several places
  tfhe/src/integer/mod.rs
  tfhe/src/integer/server_key/mod.rs
Labels: cla-signed, approved

#1398 refactor(core): make GGSW encryption consistent
  tfhe/src/c_api/core_crypto/mod.rs
  tfhe/src/core_crypto/algorithms/ggsw_encryption.rs
  tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_bootstrap_key_generation.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/fft64.rs
  tfhe/src/core_crypto/algorithms/test/ggsw_encryption.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/wop_pbs/tests.rs
Labels: cla-signed, approved

#1416 chore(gpu): fix hardware name in multi-gpu workflows
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
Labels: cla-signed, approved

#1407 fix(gpu): fix add with 1 block
  backends/tfhe-cuda-backend/cuda/src/device.cu
Labels: cla-signed, approved

#1412 doc(integer): fix typo in shl doc
  tfhe/src/integer/server_key/radix/shift.rs
Labels: cla-signed

#1414 refactor(gpu): refactor sample extract and modulus switch to match CPU's version
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
Labels: cla-signed, approved

#1419 chore(gpu): add nvidia-smi call in all hyperstack workflows
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/integer_multi_bit_multi_gpu_benchmark.yml
  .github/workflows/integer_multi_gpu_full_benchmark.yml
Labels: cla-signed, approved

#1421 fix(ci): auto merge job used wrong variable
  .github/workflows/data_pr_close.yml
Labels: cla-signed, approved, data_PR

#1417 fix(gpu): fix memory error in mul
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#1428 chore(gpu): add comments inside host_integer_sum_ciphertexts_vec_kb function
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#1413 chore(gpu): add checks in hillis&steele to avoid wrong memory access
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#1427 chore(gpu): simplify 4090 bench workflow
  .github/workflows/gpu_4090_benchmark.yml
  Makefile
  tfhe/benches/core_crypto/pbs_bench.rs
Labels: cla-signed, approved

#1323 feat(integer): improve carry propagation algorithm
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix/add.rs
  tfhe/src/integer/server_key/radix/scalar_sub.rs
  tfhe/src/integer/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/add.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/neg.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#1433 Al/clean pbs
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/include/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#1434 chore(gpu): remove remaining par_iter over gpu_indexes
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/core_crypto/gpu/slice.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Labels: cla-signed, approved

#1435 chore(versionable): add Send and Sync marker traits to Err type
  utils/tfhe-versionable/src/lib.rs
Labels: cla-signed, approved
