Repository zama-ai/tfhe-rs, pull requests merged in 2024-05, with the labels that each got.

#1119 feat(gpu): add compatibility with cuda from package managers
  backends/tfhe-cuda-backend/Cargo.toml
  backends/tfhe-cuda-backend/build.rs
Labels: cla-signed, approved

#1122 style(chore): keep a single version of generate_programmable_bootstra…
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_fast_keyswitch.rs
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
  tfhe/src/core_crypto/fft_impl/common.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
Labels: cla-signed, approved

#1130 Fix bash script shebangs
  backends/tfhe-cuda-backend/cuda/format_tfhe_cuda_backend.sh
  backends/tfhe-cuda-backend/get_os_name.sh
  scripts/integer-tests.sh
  scripts/shortint-tests.sh
Labels: cla-signed

#1121 feat(integer): add an eq_slice function
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_vector_comparisons.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_comparisons.rs
  tfhe/src/integer/server_key/radix_parallel/vector_comparisons.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#1113 chore(ci): update usage of slab-github-runner to last version
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/make_release_cuda.yml
  ci/slab.toml
Labels: cla-signed, ci

#1141 chore(gpu): add a compilation conditional to assert we won't be checking for cudaDevAttrClusterLaunch on archs < 9.0
  backends/tfhe-cuda-backend/cuda/src/device.cu
Labels: cla-signed, approved

#1135 chore(ci): run gpu benchmarks on hyperstack platform
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/start_benchmarks.yml
  .github/workflows/start_full_benchmarks.yml
  ci/ec2_products_cost.json
  ci/slab.toml
Labels: cla-signed, ci, approved

#1140 feat(integer): add contains_sub_slice
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_comparisons.rs
  tfhe/src/integer/server_key/radix_parallel/vector_comparisons.rs
Labels: cla-signed, approved

#1142 chore(ci): fix slack notification in gpu benchmarks
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
Labels: cla-signed, ci, approved

#1139 feat(gpu): implement host functions for radix_blocks_rotates
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Labels: cla-signed, approved

#1129 Implement (G)lweCiphertextList::from_fn/from_elem methods
  tfhe/src/core_crypto/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/entities/lwe_ciphertext_list.rs
Labels: cla-signed

#1149 chore(core): make the mulit bit mod switch public
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
Labels: cla-signed, approved

#1146 feat(gpu): modify `integer_radix_apply_bivariate_lookup_table_kb` to accept shift parameter
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
Labels: cla-signed

#1148 feat(c_api): quick 'n' dirty C API for some array fn
  tfhe/c_api_tests/test_high_level_array.c
  tfhe/src/c_api/high_level_api/array.rs
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/mod.rs
  tfhe/src/high_level_api/array.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/integer/server_key/radix_parallel/vector_comparisons.rs
Labels: cla-signed, approved

#1137 Mz/pack in carry
  tfhe/src/integer/ciphertext/compressed_modulus_switched_ciphertext.rs
  tfhe/src/integer/server_key/radix_parallel/modulus_switch_compression.rs
Labels: cla-signed, approved

#1154 chore(tfhe): bump version to 0.7.0
  tfhe/Cargo.toml
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/guides/migrate_data.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
Labels: cla-signed, approved

#1132 refactor(tfhe): provide functions to select some encryption parameters
  tfhe/src/boolean/client_key/mod.rs
  tfhe/src/boolean/engine/mod.rs
  tfhe/src/core_crypto/commons/parameters.rs
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/engine/client_side.rs
  tfhe/src/shortint/engine/public_side.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/src/shortint/public_key/compressed.rs
  tfhe/src/shortint/public_key/standard.rs
Labels: cla-signed, approved

#1159 chore(ci): run gpu benchmarks on push only in public repository
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
Labels: cla-signed, ci, approved

#1161 chore(gpu): change the number of threads used in the keyswitch
  backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_keyswitch.cpp
Labels: cla-signed, approved

#1165 chore(gpu): remove broken ks benchmark
  tfhe/benches/core_crypto/ks_bench.rs
Labels: cla-signed, approved

#1166 chore(ci): create release workflow for tfhe-zk-pok
  .github/workflows/make_release_zk_pok.yml
Labels: cla-signed, ci, approved

#1147 chore(ci): run workflows based on file changes
  .github/workflows/aws_tfhe_tests.yml
Labels: cla-signed, ci, approved

#1176 chore(ci): fix dependabot alert by using latest changed files
  .github/workflows/aws_tfhe_tests.yml
Labels: cla-signed, approved

#1173 fix(gpu): disable non-portable cluster sizes on TBC PBSs
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
Labels: cla-signed

#1175 chore(tfhe): add the ability to get raw parts from an FheBool
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/integer/ciphertext/boolean_value.rs
Labels: cla-signed, approved

#1167 Mz/prf sha3
  tfhe/Cargo.toml
  tfhe/src/shortint/oprf.rs
Labels: cla-signed, approved

#1144 chore(ci): new workflow target to handle ci execution from forks
  .github/workflows/approve_label.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_4090_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/m1_tests.yml
Labels: cla-signed, ci, approved

#1180 fix(gpu): fix indexing on DSM mode
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cu
Labels: cla-signed, approved

#1184 chore(ci): use only pull_request event in workflow
  .github/workflows/approve_label.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_4090_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/m1_tests.yml
Labels: cla-signed, ci, approved, external-contribution

#1183 chore(tfhe): add the ability to get raw parts from an FheBool
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/integer/ciphertext/boolean_value.rs
Labels: cla-signed, approved

#1181 chore(gpu): rebuild cuda backend if files changed
  backends/tfhe-cuda-backend/build.rs
Labels: cla-signed

#1182 chore(ci): improve npm release procedure
  .github/workflows/make_release.yml
Labels: cla-signed, ci, approved

#1187 chore(ci): update slab-github-runner to latest version
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_gpu_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/core_crypto_gpu_benchmark.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/hyperstack_tfhe_gpu_tests.yml
  .github/workflows/integer_gpu_benchmark.yml
  .github/workflows/integer_gpu_full_benchmark.yml
  .github/workflows/integer_multi_bit_gpu_benchmark.yml
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1186 chore(tfhe): make sha3 an optional dependency enabled with shortint
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1185 chore(tfhe): alias if_then_else to select
  tfhe/docs/getting_started/operations.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
Labels: cla-signed, approved
