Repository zama-ai/tfhe-rs, pull requests merged in 2025-08, with the labels that each got.

#2621 fix: wrong include guard's name
  backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
Labels: cla-signed, approved

#2619 chore(gpu): fix index type
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
Labels: cla-signed, approved

#2625 chore: fix noise checks timeout again as there are TWO timeout locations
  .github/workflows/aws_tfhe_noise_checks.yml
Labels: cla-signed, approved

#2603 chore(gpu): enable nvidia mps in long run tests
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#2563 chore(bench): write params to file for each zk benchmark on gpu
  tfhe-benchmark/benches/integer/zk_pke.rs
Labels: cla-signed, ci, approved

#2648 chore(versionable): bump version to 0.6.1
  tfhe-zk-pok/Cargo.toml
  tfhe/Cargo.toml
  utils/tfhe-versionable-derive/Cargo.toml
  utils/tfhe-versionable/Cargo.toml
Labels: cla-signed, approved

#2595 fix(bench): store correct pfail from params
  tfhe-benchmark/src/utilities.rs
  tfhe/src/shortint/parameters/ks32.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#2651 chore(ci): use crates.io trusted publishing feature
  .github/workflows/make_release.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_hpu.yml
  .github/workflows/make_release_tfhe_csprng.yml
  .github/workflows/make_release_tfhe_fft.yml
  .github/workflows/make_release_tfhe_ntt.yml
  .github/workflows/make_release_tfhe_versionable.yml
  .github/workflows/make_release_zk_pok.yml
Labels: cla-signed, ci, approved

#2655 chore(ci): deploy trusted publishing usage to all remaining crates
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_hpu.yml
  .github/workflows/make_release_tfhe_csprng.yml
  .github/workflows/make_release_tfhe_fft.yml
  .github/workflows/make_release_tfhe_ntt.yml
  .github/workflows/make_release_tfhe_versionable.yml
  .github/workflows/make_release_zk_pok.yml
Labels: cla-signed, ci, approved, backport

#2663 chore(bench): add 2 bits integer to full benchmarks
  tfhe-benchmark/src/utilities.rs
Labels: cla-signed, approved

#2669 chore(ci): add permission to github token to release crates
  .github/workflows/make_release.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_hpu.yml
  .github/workflows/make_release_tfhe_csprng.yml
  .github/workflows/make_release_tfhe_fft.yml
  .github/workflows/make_release_tfhe_ntt.yml
  .github/workflows/make_release_tfhe_versionable.yml
  .github/workflows/make_release_zk_pok.yml
Labels: cla-signed, ci, approved, backport

#2640 refactor!: Use NonZero<T> in DataKind
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/high_level_api/strings/ascii/mod.rs
  tfhe/src/integer/backward_compatibility/ciphertext/mod.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/integer/ciphertext/utils.rs
  tfhe/src/integer/gpu/ciphertext/compact_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/zk/mod.rs
  tfhe/src/shortint/ciphertext/compact_list.rs
  tfhe/src/strings/ciphertext.rs
  tfhe/src/zk/mod.rs
  utils/tfhe-versionable/src/lib.rs
Labels: cla-signed, approved

#2662 chore: fix some warnings appearing during compilation with 1.89
  tfhe/src/core_crypto/entities/lwe_ciphertext.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/integer/noise_squashing/keys.rs
Labels: cla-signed, approved

#2673 chore(core): add len checks for polynomial lists
  tfhe/src/core_crypto/algorithms/glwe_encryption.rs
  tfhe/src/core_crypto/algorithms/polynomial_algorithms.rs
Labels: cla-signed, approved

#2677 fix(gpu): fix memory leak in count consecutive bits
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#2624 chore(gpu): fix typos
  backends/tfhe-hpu-backend/config_store/v80/README.md
  backends/tfhe-hpu-backend/src/ffi/sim/ipc.rs
  tfhe/src/core_crypto/algorithms/slice_algorithms.rs
Labels: cla-signed, approved

#2498 chore(gpu): add coprocessor benchmarks in tfhe-rs gpu ci
  .github/workflows/coprocessor-benchmark-gpu.yml
Labels: cla-signed, approved

#2630 chore(gpu): add assert macro
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ggsw.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cast.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/zk/zk.cuh
Labels: cla-signed, approved

#2695 chore(gpu): fix coprocessor bench
  .github/workflows/coprocessor-benchmark-gpu.yml
Labels: cla-signed, approved

#2689 chore(gpu): fix oom in 4090 tests
  Makefile
Labels: cla-signed
