Repository zama-ai/tfhe-rs, pull requests merged in 2025-06, with the labels that each got.

#2388 fix(gpu): fix hardcoded use of message modulus
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#2392 chore(gpu): fix overflow in div in long run tests
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
Labels: cla-signed

#2384 Al/cmux memory tracking
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/cmux.rs
Labels: cla-signed

#2390 refactor(gpu): moving trim_radix_blocks_lsb_async to backend
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/cast.cu
  backends/tfhe-cuda-backend/cuda/src/integer/cast.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed

#2380 chore(ci): check ks32 parameters with lattice estimator
  Makefile
  tfhe/Cargo.toml
  tfhe/examples/utilities/params_to_file.rs
  tfhe/src/core_crypto/commons/ciphertext_modulus.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/v1_2/mod.rs
  tfhe/src/shortint/parameters/v1_3/mod.rs
Labels: cla-signed, ci, approved

#2408 chore(ci): fix benchmark matrix parameters generation
  .github/workflows/benchmark_gpu_common.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_zk_pke.yml
Labels: cla-signed, ci, approved

#2417 chore(ci): add bench type to zk benchmarks artifact name
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_zk_pke.yml
Labels: cla-signed, ci, approved

#2386 feat(gpu): add squash noise in the hlapi
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_128_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/booleans/squashed_noise.rs
  tfhe/src/high_level_api/integers/signed/squashed_noise.rs
  tfhe/src/high_level_api/integers/unsigned/squashed_noise.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/tests/noise_squashing.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/ciphertext/squashed_noise.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/noise_squashing/keys.rs
  tfhe/src/integer/gpu/noise_squashing/mod.rs
  tfhe/src/integer/gpu/noise_squashing/noise_squashing_keys.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/shortint/ciphertext/squashed_noise.rs
  tfhe/src/shortint/noise_squashing/compressed_server_key.rs
Labels: cla-signed, approved

#2420 chore(ci): parse all pbs counts files for dex benchmarks
  .github/workflows/benchmark_dex.yml
Labels: cla-signed, ci, approved

#2423 fix(gpu): fix the packing keyswitch buffer not being allocated on large parameter sets
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
Labels: cla-signed, approved, 4090_bench

#2415 refactor(gpu): return trivial indexes after ms noise reduction
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
Labels: cla-signed, approved

#2430 chore(ci): use gh cli instead of api calls done with curl
  .github/workflows/data_pr_close.yml
Labels: cla-signed, ci, approved

#2429 chore(gpu): fix ci on H100
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#2440 chore(ci): fix missing env variable for 4090 benchmark
  .github/workflows/benchmark_gpu_4090.yml
Labels: cla-signed, ci, approved

#2442 chore(ci): add missing env variable in cuda release workflow
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#2402 chore(csprng): bump to 0.6.0
  tfhe-csprng/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2453 chore(bench): harmonize dex benchmark function names
  tfhe-benchmark/benches/high_level_api/dex.rs
Labels: cla-signed, ci, approved

#2450 Ns/chore/prepare release 1 3
  apps/trivium/README.md
  apps/trivium/benches/kreyvium_shortint.rs
  apps/trivium/benches/trivium_shortint.rs
  apps/trivium/src/kreyvium/test.rs
  apps/trivium/src/trivium/test.rs
  tfhe-benchmark/src/params_aliases.rs
  tfhe/Cargo.toml
  tfhe/c_api_tests/test_high_level_custom_integers.c
  tfhe/c_api_tests/test_high_level_integers.c
  tfhe/c_api_tests/test_shortint_keygen.c
  tfhe/c_api_tests/test_shortint_pbs.c
  tfhe/c_api_tests/test_shortint_server_key.c
  tfhe/docs/configuration/gpu_acceleration/run_on_gpu.md
  tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
  tfhe/docs/configuration/parallelized_pbs.md
  tfhe/docs/fhe-computation/advanced-features/zk-pok.md
  tfhe/docs/fhe-computation/compute/parameters.md
  tfhe/docs/fhe-computation/data-handling/data_versioning.md
  tfhe/docs/fhe-computation/data-handling/serialization.md
  tfhe/docs/fhe-computation/types/array.md
  tfhe/docs/fhe-computation/types/strings.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/integration/js_on_wasm_api.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
  tfhe/examples/sha256.rs
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/js_on_wasm_tests/test-hlapi-signed.js
  tfhe/js_on_wasm_tests/test-hlapi-unsigned.js
  tfhe/js_on_wasm_tests/test.js
  tfhe/src/c_api/shortint/parameters.rs
  tfhe/src/integer/gpu/zk/mod.rs
  tfhe/src/js_on_wasm_api/shortint.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/test_params.rs
  tfhe/src/shortint/prelude.rs
  tfhe/src/shortint/server_key/mul.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#2333 refactor(gpu): optimize sum_ciphertexts in cuda backend
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
Labels: cla-signed, approved

#2426 feat(core): plug XofSeed in core's RNG
  tfhe/src/core_crypto/commons/generators/encryption/mask_random_generator.rs
  tfhe/src/core_crypto/commons/generators/encryption/mod.rs
  tfhe/src/core_crypto/commons/math/random/generator.rs
Labels: cla-signed, approved

#2436 feat: improve division for 2_2 parameters
  tfhe/src/integer/server_key/radix_parallel/div_mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_div_mod.rs
Labels: cla-signed, approved

#2463 chore(ci): set pull-requests permission to write in commit checks
  .github/workflows/check_commit.yml
Labels: cla-signed, ci, approved

#2449 Ns/chore/zk refactor hashes
  tfhe-zk-pok/src/proofs/pke_v2/hashes.rs
  tfhe-zk-pok/src/proofs/pke_v2/mod.rs
Labels: cla-signed, approved

#2469 fix(hpu): Remove some hardcoded filename in tandem
  backends/tfhe-hpu-backend/src/ffi/v80/ami.rs
  backends/tfhe-hpu-backend/src/ffi/v80/mod.rs
  setup_hpu.sh
Labels: cla-signed, approved

#2470 fix(shortint): wrong LweDimension returned by prf multibit mod switched ct
  tfhe/src/shortint/oprf.rs
Labels: cla-signed, approved

#2467 chore: make multi bit pbs 128 more flexible
  tfhe/src/core_crypto/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
Labels: cla-signed, approved

#2484 feat(hpu): Adding support for modulus switch mean compensation
  backends/tfhe-hpu-backend/config_store/sim/hpu_config.toml
  backends/tfhe-hpu-backend/config_store/sim/hpu_regif_core_cfg_1in3.toml
  backends/tfhe-hpu-backend/config_store/u55c_gf64/hpu_config.toml
  backends/tfhe-hpu-backend/config_store/v80/hpu_config.toml
  backends/tfhe-hpu-backend/config_store/v80/hpu_regif_core_cfg_1in3.toml
  backends/tfhe-hpu-backend/config_store/v80_archives/psi64.hpu
  backends/tfhe-hpu-backend/src/interface/backend.rs
  backends/tfhe-hpu-backend/src/interface/config.rs
  backends/tfhe-hpu-backend/src/interface/rtl/params.rs
  backends/tfhe-hpu-backend/src/interface/rtl/runtime.rs
  mockups/tfhe-hpu-mockup/params/tuniform_64b_pfail128_psi64.toml
  mockups/tfhe-hpu-mockup/src/lib.rs
  mockups/tfhe-hpu-mockup/src/modules/regmap.rs
Labels: cla-signed

#2477 chore(gpu): add abs to random op sequence test on GPU
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/test_signed_random_op_sequence.rs
Labels: cla-signed, approved
