Repository zama-ai/tfhe-rs, pull requests merged in 2025-01, with the labels that each got.

#1909 chore: force wasm-bindgen-rayon to 1.2.2
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1911 chore(ci): fix concurrency group format on pull request event
  .github/workflows/aws_tfhe_fast_tests.yml
Labels: cla-signed, ci, approved

#1910 test(shortint): remove oprf test flakiness
  tfhe/src/shortint/oprf.rs
Labels: cla-signed, approved

#1914 chore(ci): switch gpu tests on push to l40
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
  ci/slab.toml
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed

#1915 chore(ci): fix workflow not triggering on pull request
  .github/workflows/aws_tfhe_fast_tests.yml
Labels: cla-signed, approved

#1916 chore(gpu): bump backend version
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1882 feat(hlapi): add strings
  Makefile
  tfhe/src/high_level_api/backward_compatibility/mod.rs
  tfhe/src/high_level_api/backward_compatibility/strings.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/strings/ascii/comp.rs
  tfhe/src/high_level_api/strings/ascii/contains.rs
  tfhe/src/high_level_api/strings/ascii/find.rs
  tfhe/src/high_level_api/strings/ascii/mod.rs
  tfhe/src/high_level_api/strings/ascii/no_pattern.rs
  tfhe/src/high_level_api/strings/ascii/replace.rs
  tfhe/src/high_level_api/strings/ascii/strip.rs
  tfhe/src/high_level_api/strings/ascii/trim.rs
  tfhe/src/high_level_api/strings/mod.rs
  tfhe/src/high_level_api/strings/tests/cpu.rs
  tfhe/src/high_level_api/strings/tests/mod.rs
  tfhe/src/high_level_api/strings/traits.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/strings/backward_compatibility/mod.rs
  tfhe/src/strings/ciphertext.rs
  tfhe/src/strings/client_key.rs
  tfhe/src/strings/mod.rs
  tfhe/src/strings/server_key/comp.rs
  tfhe/src/strings/server_key/mod.rs
  tfhe/src/strings/server_key/no_patterns.rs
Labels: cla-signed, approved

#1920 chore: update docs version to be 0.11
  tfhe/docs/fundamentals/serialization.md
  tfhe/docs/getting_started/benchmarks/summary.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/guides/array.md
  tfhe/docs/guides/data_versioning.md
  tfhe/docs/guides/run_on_gpu.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
Labels: cla-signed, approved

#1850 chore(docs): update discord link
  tfhe/docs/README.md
Labels: cla-signed, approved

#1926 chore(docs): update discord link
  tfhe/docs/README.md
Labels: cla-signed, approved

#1925 chore(test): modify cpu multi-bit parameters for noise test
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
Labels: cla-signed, approved

#1928 chore(ci): fix pull_request_target event handling
  .github/workflows/aws_tfhe_fast_tests.yml
Labels: cla-signed, ci, approved, backport

#1930 chore(test): modify cpu multi-bit parameters for noise test
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
Labels: cla-signed, approved

#1931 chore(trivium): fix params, reverted back to gaussian
  apps/trivium/README.md
  apps/trivium/benches/kreyvium_shortint.rs
  apps/trivium/benches/trivium_shortint.rs
  apps/trivium/src/kreyvium/test.rs
  apps/trivium/src/trivium/test.rs
Labels: cla-signed, approved

#1934 chore(ci): push tfhe-cuda-backend to crates.io unconditionally
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1942 chore(ci): put back weekly core_crypto benchmarks
  .github/workflows/benchmark_core_crypto.yml
Labels: cla-signed, ci, approved

#1938 fix(gpu): fix cornercase in match value function
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
Labels: cla-signed, approved

#1937 chore: enable strings for docs.rs generation
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1936 chore(backward): move compat tests to avoid compiling them everytime
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .gitignore
  Cargo.toml
  Makefile
  tasks/src/check_tfhe_docs_are_tested.rs
  tests/Cargo.toml
  tests/backward_compatibility/high_level_api.rs
  tests/backward_compatibility/mod.rs
  tests/backward_compatibility/shortint.rs
  tests/backward_compatibility_tests.rs
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1917 chore(zk): add bench zk v1 vs v2
  tfhe/benches/integer/zk_pke.rs
  tfhe/src/js_on_wasm_api/shortint.rs
  tfhe/web_wasm_parallel_tests/worker.js
Labels: cla-signed, approved

#1941 chore: remove unused cargo key
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1951 chore(ci): run teardown job only if setup is a success
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/code_coverage.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/integer_long_run_tests.yml
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#1908 feat(gpu): optimize packing keyswitch on gpu
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#1944 chore(docs): add strings guides
  Makefile
  tfhe/docs/SUMMARY.md
  tfhe/docs/guides/strings.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#1922 chore(docs): add strings guides
  Makefile
  tfhe/docs/SUMMARY.md
  tfhe/docs/guides/strings.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#1924 doc(zk): explain how to use zkv1
  tfhe/docs/guides/zk-pok.md
Labels: cla-signed, approved

#1946 backport 0.11: explain how to use zkv1
  tfhe/docs/guides/zk-pok.md
Labels: cla-signed, approved

#1959 chore(gpu): update new_multi_gpu() description
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#1953 chore(backward): update data repo to 0.5
  Makefile
  tests/Cargo.toml
Labels: cla-signed, approved

#1940 chore(ci): temporarily disable the multi bit noise check on Apple M1
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
Labels: cla-signed, approved

#1962 chore(ci): choose pull request event with path changes
  .github/workflows/aws_tfhe_fast_tests.yml
Labels: cla-signed, ci, approved

#1954 Ns/chore/zk use stable isqrt
  tfhe-zk-pok/Cargo.toml
  tfhe-zk-pok/src/backward_compatibility/mod.rs
  tfhe-zk-pok/src/four_squares.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
  tfhe/Cargo.toml
Labels: cla-signed, approved

#1971 Am/chore/fix doc
  tfhe/docs/getting_started/security_and_cryptography.md
  tfhe/docs/guides/strings.md
  tfhe/docs/references/fine-grained-apis/boolean/parameters.md
  tfhe/docs/references/fine-grained-apis/shortint/parameters.md
Labels: cla-signed, approved

#1972 chore(docs): fix various issues with the docs
  tfhe/docs/getting_started/security_and_cryptography.md
  tfhe/docs/guides/strings.md
  tfhe/docs/references/fine-grained-apis/boolean/parameters.md
  tfhe/docs/references/fine-grained-apis/shortint/parameters.md
Labels: cla-signed, approved

#1970 chore: fix new lints
  tfhe-ntt/src/product.rs
  tfhe/src/core_crypto/fft_impl/fft128/math/fft/mod.rs
  tfhe/src/core_crypto/fft_impl/fft128_u128/math/fft/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix/slice.rs
  tfhe/src/integer/server_key/radix_parallel/comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_shift.rs
  tfhe/src/shortint/client_key/mod.rs
  utils/tfhe-versionable-derive/src/lib.rs
Labels: cla-signed, approved

#1978 chore(gpu): add reference to gemm algorithm
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
Labels: cla-signed, approved

#1977 chore(docs): Remove mention to NVLink
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed, approved

#1979 chore(docs): Remove mention to NVLink
  tfhe/docs/guides/run_on_gpu.md
Labels: cla-signed, approved

#1973 chore(ci): fix clippy on M1 for disabled multi bit noise
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
Labels: cla-signed, approved

#1974 fix(shortint): error message in packing keyswitch
  tfhe/src/shortint/list_compression/compression.rs
Labels: cla-signed, approved

#1968 chore(ci): skip aws fast tests if ci files changed
  .github/workflows/aws_tfhe_fast_tests.yml
Labels: cla-signed, ci, approved

#1958 feat(gpu): implement fhe rand on gpu
  backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/negation.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/negation.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/benches/integer/bench.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/booleans/oprf.rs
  tfhe/src/high_level_api/integers/oprf.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/oprf.rs
  tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
  tfhe/src/shortint/engine/mod.rs
  tfhe/src/shortint/oprf.rs
  tfhe/src/shortint/server_key/mod.rs
Labels: cla-signed

#1982 fix(safe_ser): aliases in named for renamed types deserialization
  tfhe/src/named.rs
  tfhe/src/safe_serialization.rs
  tfhe/src/zk/mod.rs
Labels: cla-signed, approved

#1983 chore(ci): use ubuntu 22.04 to run security checks
  .github/actionlint.yaml
  .github/workflows/parameters_check.yml
Labels: cla-signed, ci, approved

#1986 backport 0.11: fix(safe_ser): aliases in named for renamed types deserialization
  tfhe/src/named.rs
  tfhe/src/safe_serialization.rs
  tfhe/src/zk/mod.rs
Labels: cla-signed, approved

#1976 test(core): use 5 bits parameters tweaked to 4 bits to avoid high pfail
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_fast_keyswitch.rs
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
Labels: cla-signed, approved

#1984 chore: feature gating js_high_level_api
  tfhe/src/js_on_wasm_api/js_high_level_api/mod.rs
  tfhe/src/js_on_wasm_api/mod.rs
  tfhe/src/js_on_wasm_api/shortint.rs
Labels: cla-signed, approved

#1981 Ns/doc strings
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/src/lib.rs
Labels: cla-signed, approved

#1991 chore: update bench file pbs 128 parameters
  tfhe/benches/core_crypto/pbs128_bench.rs
Labels: cla-signed, approved

#1826 feat: centralize encoding in shortint
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/shortint/ciphertext/standard.rs
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/encoding.rs
  tfhe/src/shortint/engine/client_side.rs
  tfhe/src/shortint/engine/mod.rs
  tfhe/src/shortint/engine/public_side.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/mod.rs
  tfhe/src/shortint/parameters/compact_public_key_only/mod.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/src/shortint/server_key/mod.rs
  tfhe/src/shortint/server_key/neg.rs
  tfhe/src/shortint/server_key/scalar_add.rs
  tfhe/src/shortint/server_key/scalar_sub.rs
Labels: cla-signed, approved

#1870 Am/refactor/factorize expansion code
  tfhe/src/integer/ciphertext/compact_list.rs
Labels: cla-signed

#1994 chore(gpu): use struct to pass radix data in the ffi
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/integer/radix_ciphertext.h
  backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
  backends/tfhe-cuda-backend/cuda/src/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cu
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/abs.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/cmux.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mul.rs
  tfhe/src/integer/gpu/server_key/radix/neg.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
  tfhe/src/shortint/ciphertext/common.rs
Labels: cla-signed, approved

#2005 chore(ci): use complete bot names on permission checks
  .github/workflows/check_actor_permissions.yml
Labels: cla-signed, ci, approved

#2001 Al/refactor lut
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
Labels: cla-signed, approved

#2008 chore(ci): fix boolean logic for bot permission checks
  .github/workflows/check_actor_permissions.yml
Labels: cla-signed, ci, approved

#2009 chore(bench): add some v0_11 parameters into keycache
  tfhe/src/shortint/keycache.rs
Labels: cla-signed, approved

#2004 chore(gpu): add back async entry points
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/abs.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/cmux.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/mul.rs
  tfhe/src/integer/gpu/server_key/radix/neg.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/gpu/server_key/radix/vector_comparisons.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
Labels: cla-signed, approved

#2013 chore(gpu): shorten workflow names
  .github/workflows/gpu_4090_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed

#1990 feat(hlapi): add gpu selection
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/array/gpu/booleans.rs
  tfhe/src/high_level_api/array/gpu/integers.rs
  tfhe/src/high_level_api/array/mod.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/inner.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/inner.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/inner.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/mod.rs
  tfhe/src/high_level_api/tests/gpu_selection.rs
  tfhe/src/high_level_api/tests/mod.rs
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
Labels: cla-signed, approved

#2015 feat(integer): impl Named for compression keys
  tfhe/src/integer/compression_keys.rs
Labels: cla-signed, approved

#2023 fix(integer): fix a typo in a comment
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved
