Repository zama-ai/tfhe-rs, pull requests merged in 2025-04, with the labels that each got.

#2226 feat(hl): create FheTypes from i32
  tfhe/Cargo.toml
  tfhe/src/high_level_api/mod.rs
Labels: cla-signed, approved

#2229 chore(ci): fix data PR close workflow
  .github/workflows/data_pr_close.yml
Labels: cla-signed, approved

#2227 fix(gpu): update panic condition to apply only to tbc
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
Labels: cla-signed, approved

#2234 chore(gpu): decrease test threads for small instances
  scripts/integer-tests.sh
Labels: cla-signed, approved

#2225 chore(ci): fix handling of instance setup failure
  .github/workflows/benchmark_gpu_common.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
Labels: cla-signed, ci, approved

#2231 feat(gpu): add drift to 128-bit pbs tests
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/ks_pbs_bench.rs
  tfhe/benches/core_crypto/pbs128_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/benches/utilities.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/core_crypto/gpu/entities/lwe_bootstrap_key.rs
  tfhe/src/core_crypto/keycache.rs
  tfhe/src/integer/gpu/server_key/mod.rs
Labels: cla-signed, approved

#2221 feat(gpu): implement ZK's expand
  Makefile
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/include/integer/radix_ciphertext.h
  backends/tfhe-cuda-backend/cuda/include/keyswitch/ks_enums.h
  backends/tfhe-cuda-backend/cuda/include/zk/zk.h
  backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
  backends/tfhe-cuda-backend/cuda/src/zk/expand.cu
  backends/tfhe-cuda-backend/cuda/src/zk/expand.cuh
  backends/tfhe-cuda-backend/cuda/src/zk/zk.cu
  backends/tfhe-cuda-backend/cuda/src/zk/zk.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  backends/tfhe-cuda-backend/wrapper.h
  tfhe/benches/integer/zk_pke.rs
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/mod.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/ciphertext/compact_list.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/key_switching_key/mod.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/zk/mod.rs
  tfhe/src/shortint/parameters/test_params.rs
Labels: cla-signed, approved

#2148 feat(ntt-bnf) Add back&Forth ntt implementation
  tfhe/src/core_crypto/algorithms/lwe_bootstrap_key_conversion.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/mod.rs
  tfhe/src/core_crypto/algorithms/lwe_programmable_bootstrapping/ntt64_bnf_pbs.rs
  tfhe/src/core_crypto/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/commons/math/ntt/ntt64.rs
Labels: cla-signed, approved

#2239 chore(gpu): add a feature to build for multiple architectures
  backends/tfhe-cuda-backend/Cargo.toml
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2244 feat(shortint): add from_raw_parts for NoiseSquashingKey
  tfhe/src/shortint/noise_squashing/server_key.rs
Labels: cla-signed, approved

#2242 docs: add dot prod & scalar_select
  tfhe/docs/SUMMARY.md
  tfhe/docs/fhe-computation/operations/dot-product.md
  tfhe/docs/fhe-computation/operations/ternary-conditional-operations.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#2251 docs: add dot prod & scalar_select
  tfhe/docs/SUMMARY.md
  tfhe/docs/fhe-computation/operations/dot-product.md
  tfhe/docs/fhe-computation/operations/ternary-conditional-operations.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#2250 chore(gpu): update parameter sets in the C++ test/benchmark tools
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_classical_pbs.cpp
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_multibit_pbs.cpp
Labels: cla-signed, approved

#2257 chore(gpu): add bench command for zk-pok in workflow
  .github/workflows/benchmark_gpu.yml
  Makefile
Labels: cla-signed, approved

#2248 fix(integer): handles compression of empty ct in empty list
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/strings/ciphertext.rs
  tfhe/src/strings/test_functions/test_compression.rs
Labels: cla-signed, approved

#2256 chore(core): remove useless export from test module
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_fast_keyswitch.rs
  tfhe/src/core_crypto/experimental/algorithms/test/lwe_stair_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/fft.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_linear_algebra.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
  tfhe/src/core_crypto/gpu/algorithms/test/modulus_switch_noise_reduction.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
Labels: cla-signed, approved

#2259 chore(shortint): to/from_raw_parts for NoiseSquashingPrivateKey
  tfhe/src/shortint/noise_squashing/private_key.rs
Labels: cla-signed, approved

#2233 docs: add handbook reference
  tfhe/docs/README.md
Labels: cla-signed, approved

#2264 docs: add handbook reference
  tfhe/docs/README.md
Labels: cla-signed, approved

#2265 chore(gpu): add multi-bit parameters to be used with ZK's expand
  tfhe/benches/integer/zk_pke.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/gpu/zk/mod.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/v1_1/key_switching/p_fail_2_minus_128/ks_pbs_gpu.rs
  tfhe/src/shortint/parameters/v1_1/key_switching/p_fail_2_minus_128/mod.rs
Labels: cla-signed, approved

#2268 fix(core): fix success probability for Ternary Uniform generation
  tfhe/src/core_crypto/commons/math/random/uniform_ternary.rs
Labels: cla-signed, approved

#2269 feat(hl): add AsRef implementation on ServerKey to access NoiseSquashingKey
  tfhe/src/high_level_api/keys/server.rs
Labels: cla-signed, approved

#2266 docs(gpu): small update in the integer benchmark page
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m128_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m128_plaintext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m128_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m128_plaintext.svg
  tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
Labels: cla-signed, approved

#2271 chore: update toolchain to 2025-04-16
  tfhe/src/core_crypto/keycache.rs
  tfhe/src/integer/gpu/key_switching_key/mod.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/public_key/standard.rs
  toolchain.txt
  utils/tfhe-versionable-derive/src/versionize_impl.rs
Labels: cla-signed, approved

#2272 chore(gpu): reduce test threads for small instances case
  scripts/integer-tests.sh
Labels: cla-signed, approved

#2273 chore(gpu): remove unused events for carry prop
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#2274 chore(tfhe): allow clippy::struct_field_names at the crate level
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/integer/gpu/key_switching_key/mod.rs
  tfhe/src/lib.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/public_key/standard.rs
Labels: cla-signed, approved

#2279 chore(all): make clippy_rustdoc output less noisy
  Makefile
Labels: cla-signed, approved

#2275 feat(core): enable custom modulus generation for TUniform
  tfhe/src/core_crypto/commons/math/random/mod.rs
  tfhe/src/core_crypto/commons/math/random/t_uniform.rs
  tfhe/src/core_crypto/commons/math/random/tests.rs
Labels: cla-signed, approved

#2280 chore(core): fix a wrong comment on gaussian generation
  tfhe/src/core_crypto/commons/math/random/gaussian.rs
Labels: cla-signed, approved

#2283 doc(core): fix badly closed tags in lwe_wopbs doc
  tfhe/src/core_crypto/algorithms/lwe_wopbs.rs
Labels: cla-signed, approved

#2286 chore: add CODEOWNERS file to avoid unwanted changes to core_crypto source
  CODEOWNERS
Labels: cla-signed, approved

#2287 docs: fix typo
  tfhe/docs/fhe-computation/operations/arithmetic-operations.md
Labels: cla-signed, approved

#2289 chore(gpu): removes the alias synchronize_threads_in_block()
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/gadget.cuh
  backends/tfhe-cuda-backend/cuda/src/crypto/ggsw.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/functions.cuh
Labels: cla-signed, approved

#2284 chore(gpu): add nvtx tool for profiling
  backends/tfhe-cuda-backend/Cargo.toml
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cu
  backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cuh
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2288 chore(core): remove some pub(crate) in structs
  tfhe/src/core_crypto/backward_compatibility/entities/compressed_modulus_switched_lwe_ciphertext.rs
  tfhe/src/core_crypto/commons/ciphertext_modulus.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/packed_integers.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed, approved

#2196 docs: update section links
  CONTRIBUTING.md
  README.md
  tfhe/docs/configuration/parallelized_pbs.md
  tfhe/docs/fhe-computation/compute/parameters.md
  tfhe/docs/references/fine-grained-apis/integer/operations.md
  tfhe/docs/references/fine-grained-apis/shortint/README.md
Labels: cla-signed

#2297 chore: update CODEOWNERS for more paths
  CODEOWNERS
Labels: cla-signed, approved

#2295 chore(ci): log action to perform on approval for external pr
  .github/workflows/approve_label.yml
Labels: cla-signed, ci, approved

#2299 chore: update toolchain to 2025-04-28
  apps/trivium/src/kreyvium/test.rs
  apps/trivium/src/static_deque/static_deque.rs
  apps/trivium/src/trivium/test.rs
  backends/tfhe-cuda-backend/build.rs
  tests/backward_compatibility/high_level_api.rs
  tests/backward_compatibility_tests.rs
  tfhe-csprng/src/generators/implem/aesni/block_cipher.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/serialization.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/docs/references/fine-grained-apis/shortint/operations.md
  tfhe/docs/tutorials/parity_bit.md
  tfhe/examples/regex_engine/engine.rs
  tfhe/examples/regex_engine/execution.rs
  tfhe/examples/regex_engine/parser.rs
  tfhe/examples/sha256_bool/main.rs
  tfhe/examples/sha256_bool/padding.rs
  tfhe/examples/sha256_bool/sha256_function.rs
  tfhe/examples/utilities/hlapi_compact_pk_ct_sizes.rs
  tfhe/examples/utilities/params_to_file.rs
  tfhe/examples/utilities/shortint_key_sizes.rs
  tfhe/examples/utilities/wasm_benchmarks_parser.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/server_key/radix/add.rs
  tfhe/src/integer/server_key/radix/bitwise_op.rs
  tfhe/src/integer/server_key/radix/neg.rs
  tfhe/src/integer/server_key/radix/scalar_mul.rs
  tfhe/src/integer/server_key/radix/sub.rs
  toolchain.txt
  utils/tfhe-versionable-derive/src/dispatch_type.rs
  utils/tfhe-versionable-derive/src/version_type.rs
  utils/tfhe-versionable-derive/src/versionize_impl.rs
Labels: cla-signed, approved

#2298 chore(shortint): add asserts
  tfhe/src/conformance.rs
  tfhe/src/shortint/oprf.rs
Labels: cla-signed, approved

#2291 fix(core): remove additional body coeff in multi bit ms compression
  tfhe/src/core_crypto/backward_compatibility/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
Labels: cla-signed, approved
