Repository zama-ai/tfhe-rs, pull requests merged in 2025-09, with the labels that each got.

#2697 chore(core): size checks in Fourier128GgswCiphertext::from_container
  tfhe/src/core_crypto/fft_impl/fft128/crypto/ggsw.rs
Labels: cla-signed, approved

#2600 fix: remove references to 2^-64 pfail for GPU
  README.md
  tfhe/docs/fhe-computation/compute/parameters.md
  tfhe/docs/getting-started/security-and-cryptography.md
  tfhe/docs/references/fine-grained-apis/shortint/parameters.md
Labels: cla-signed, approved

#2682 chore(fft): remove dead store in stockham dif16
  tfhe-fft/src/dif16.rs
Labels: cla-signed, approved

#2716 feat(gpu): improve communication scheme
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/oprf.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
Labels: cla-signed, approved

#2676 feat(gpu): implement support for 128-bit compression on the HL API
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/high_level_api/booleans/squashed_noise.rs
  tfhe/src/high_level_api/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/high_level_api/integers/signed/squashed_noise.rs
  tfhe/src/high_level_api/integers/unsigned/squashed_noise.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/squashed_noise.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed, approved

#2733 chore(ci): configure tfhe-ntt tests to have an avx512 + IFMA instance
  .github/workflows/cargo_test_ntt.yml
Labels: cla-signed, approved

#2735 fix(zk): handle limit cases in the four_squares algorithm
  tfhe-zk-pok/src/four_squares.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke_v2/mod.rs
Labels: cla-signed, approved

#2739 chore(zk): bump tfhe-zk-pok to 0.7.2
  tfhe-zk-pok/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2737 feat(gpu): enable lut generation with preallocated buffers
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
Labels: cla-signed, approved

#2747 chore(bench): remove 2-bits size for full precision bench on gpu
  tfhe-benchmark/src/utilities.rs
Labels: cla-signed, ci, approved

#2736 doc(gpu): add a section about noise squashing
  tfhe/docs/configuration/gpu-acceleration/noise-squashing.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed

#2741 feat(integer): add flip operation
  tfhe-benchmark/benches/integer/bench.rs
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
Labels: cla-signed, approved

#2750 chore(gpu): reduce test threads for 4090 doc tests
  Makefile
Labels: cla-signed, approved, 4090_test

#2753 chore(gpu): update sxm5 cost
  ci/ec2_products_cost.json
Labels: cla-signed, approved

#2758 fix(c-api): add missing safe_deser for ServerKey
  tfhe/src/c_api/high_level_api/keys.rs
Labels: cla-signed, approved

#2771 chore(ci): run cargo audit
  .cargo/audit.toml
  .github/workflows/cargo_audit.yml
  Makefile
Labels: cla-signed, approved

#2776 chore(bench): add crs size in zk-pke benchmark names
  tfhe-benchmark/benches/integer/zk_pke.rs
Labels: cla-signed, approved

#2777 chore(ci): perform sync on push without third-party action
  .github/workflows/sync_on_push.yml
Labels: cla-signed, ci, approved

#2731 fix(gpu): coprocessor bench
  .github/workflows/coprocessor-benchmark-gpu.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  Makefile
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/device.cu
  ci/slab.toml
Labels: cla-signed, approved

#2790 chore(core): use a single rng for cpk encryption
  tfhe/src/core_crypto/algorithms/lwe_encryption.rs
  tfhe/src/core_crypto/algorithms/test/lwe_encryption.rs
  tfhe/src/core_crypto/commons/generators/encryption/mod.rs
  tfhe/src/core_crypto/commons/generators/encryption/noise_random_generator.rs
  tfhe/src/core_crypto/commons/math/random/generator.rs
  tfhe/src/high_level_api/re_randomization.rs
  tfhe/src/integer/ciphertext/re_randomization.rs
  tfhe/src/shortint/ciphertext/re_randomization.rs
  tfhe/src/shortint/public_key/compact.rs
Labels: cla-signed, approved

#2751 fix(gpu): avoid out of memory when benchmarking throughput
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  tfhe-benchmark/src/utilities.rs
Labels: cla-signed, approved

#2794 fix(versionable): use full type path in proc macro
  utils/tfhe-versionable-derive/src/associated.rs
  utils/tfhe-versionable-derive/src/lib.rs
Labels: cla-signed, approved

#2818 chore: bump tfhe-cuda-backend to 0.12.0-alpha.0
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2808 chore(ci): increase timeout to 8hours for unsigned integer tests
  .github/workflows/aws_tfhe_integer_tests.yml
Labels: cla-signed, approved

#2820 chore(ci): use artifact for cuda backend to speed up publishing
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, ci, approved

#2825 Fix oprf with multi-GPU
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/oprf.cu
  backends/tfhe-cuda-backend/cuda/src/integer/oprf.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/oprf.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_oprf.rs
Labels: cla-signed, approved

#2830 chore: prepare alpha.2
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2823 chore(gpu): get decompress size on gpu without calling on_gpu
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed, approved

#2828 feat(gpu): Implements optimized division algorithm for message_2_carry_2
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
Labels: cla-signed, approved
