Repository zama-ai/tfhe-rs, pull requests merged in 2025-07, with the labels that each got.

#2472 chore(gpu): add cuda debug target for integer tests
  Makefile
  backends/tfhe-cuda-backend/Cargo.toml
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2465 feat(integer): add CompressedSquasedNoiseCiphertextList
  tfhe/src/integer/backward_compatibility/list_compression.rs
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/integer/ciphertext/mod.rs
  tfhe/src/integer/noise_squashing/keys.rs
  tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/shortint/list_compression/server_keys.rs
  tfhe/src/shortint/noise_squashing/private_key.rs
  tfhe/src/shortint/parameters/test_params.rs
Labels: cla-signed, approved

#2487 chore: move gated import to section with feature gate in HL erc20 bench
  tfhe-benchmark/benches/high_level_api/erc20.rs
Labels: cla-signed, approved

#2501 chore(gpu): bump backend version
  backends/tfhe-cuda-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2509 chore(hpu): bump backend version
  backends/tfhe-hpu-backend/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2508 fix(gpu): refactor the (128-bit and regular) classical PBS entry point to remove the num_samples parameter
  tfhe-benchmark/benches/core_crypto/ks_pbs_bench.rs
  tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
  tfhe-benchmark/benches/core_crypto/pbs_bench.rs
  tfhe-benchmark/src/utilities.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
  tfhe/src/integer/gpu/server_key/radix/oprf.rs
Labels: cla-signed, approved

#2439 chore(gpu): update noise squashing parameters
  tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/high_level_api/tests/noise_squashing.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/v1_3/mod.rs
  tfhe/src/shortint/parameters/v1_3/noise_squashing/p_fail_2_minus_128/mod.rs
Labels: cla-signed

#2505 chore(gpu): remove template from sum ciphertexts, add two missing delete
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
Labels: cla-signed

#2515 chore(gpu): update noise squashing parameters
  tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
  tfhe/Cargo.toml
  tfhe/docs/configuration/gpu_acceleration/run_on_gpu.md
  tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
  tfhe/docs/fhe-computation/data-handling/data_versioning.md
  tfhe/docs/fhe-computation/data-handling/serialization.md
  tfhe/docs/fhe-computation/types/array.md
  tfhe/docs/fhe-computation/types/strings.md
  tfhe/docs/getting_started/installation.md
  tfhe/docs/getting_started/quick_start.md
  tfhe/docs/references/core-crypto-api/tutorial.md
  tfhe/docs/tutorials/ascii_fhe_string.md
  tfhe/docs/tutorials/parity_bit.md
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/high_level_api/tests/noise_squashing.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/v1_3/mod.rs
  tfhe/src/shortint/parameters/v1_3/noise_squashing/p_fail_2_minus_128/mod.rs
Labels: cla-signed, approved

#2520 Fix Typo in CONFIGURATION Section Header
  tfhe/src/test_user_docs.rs
Labels: cla-signed

#2448 feat(gpu): implement 128-bit multi-bit PBS
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/fft128/fft128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit_128.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe-benchmark/benches/core_crypto/pbs128_bench.rs
  tfhe-benchmark/src/utilities.rs
  tfhe/examples/utilities/params_to_file.rs
  tfhe/src/core_crypto/algorithms/test/mod.rs
  tfhe/src/core_crypto/algorithms/test/params.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping_128.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
  tfhe/src/core_crypto/gpu/entities/lwe_multi_bit_bootstrap_key.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/shortint/backward_compatibility/parameters/noise_squashing.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/noise_squashing.rs
  tfhe/src/shortint/parameters/v1_3/mod.rs
  tfhe/src/shortint/parameters/v1_3/noise_squashing/p_fail_2_minus_128/mod.rs
Labels: cla-signed, approved

#2525 chore: remove dead link from docs
  tfhe/docs/README.md
Labels: cla-signed, approved

#2521 test: use hamming weight = 1/2 for core noise tests
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_encryption_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_hpu_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_keyswitch_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/algorithms/test/noise_distribution/mod.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/mod.rs
Labels: cla-signed, approved

#2524 chore: remove dead link from docs
  tfhe/docs/README.md
Labels: cla-signed, approved

#2531 Am/chore/close stale p rs
  .github/workflows/unverified_prs.yml
Labels: cla-signed, approved

#2523 docs: add noise squashing documentation
  tfhe/docs/SUMMARY.md
  tfhe/docs/fhe-computation/advanced-features/noise-squashing.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#2504 chore(gpu): refactor size tracker to avoid future bugs
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/bitwise_ops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cast.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/subtraction.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
  backends/tfhe-cuda-backend/cuda/src/zk/zk.cuh
Labels: cla-signed

#2538 chore(shortint): make `decrypt_no_decode` public
  tfhe/src/shortint/client_key/mod.rs
Labels: cla-signed, approved

#2541 docs: describe noise squashed compression
  tfhe/docs/fhe-computation/advanced-features/noise-squashing.md
Labels: cla-signed, approved, backport

#2447 feat(gpu): update GPU documentation
  tfhe/docs/SUMMARY.md
  tfhe/docs/configuration/gpu_acceleration/array_type.md
  tfhe/docs/configuration/gpu_acceleration/benchmark.md
  tfhe/docs/configuration/gpu_acceleration/compressing_ciphertexts.md
  tfhe/docs/configuration/gpu_acceleration/gpu_operations.md
  tfhe/docs/configuration/gpu_acceleration/multi_gpu.md
  tfhe/docs/configuration/gpu_acceleration/run_on_gpu.md
  tfhe/docs/configuration/gpu_acceleration/simple_example.md
  tfhe/docs/configuration/gpu_acceleration/zk-pok.md
  tfhe/docs/getting_started/benchmarks/README.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#2547 chore(gpu): reduce ci time by reducing testing of unused parameters
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_add.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_mul.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_rotate.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_mul.rs
Labels: cla-signed, approved

#2499 refactor(gpu): moving unsigned_scalar_div_rem and signed_scalar_div_rem to the backend
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
Labels: cla-signed, approved

#2559 fix(gpu): fix pbs128 multi-gpu bug
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
Labels: cla-signed, approved

#2527 chore(gpu): minor refactor in sum ctxt
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#2556 fix(gpu): reduces number of elements in the ZK throughput benchmark
  tfhe-benchmark/benches/integer/zk_pke.rs
Labels: cla-signed

#2544 fix(gpu): fix regression on ERC20 throughput
  tfhe-benchmark/benches/high_level_api/erc20.rs
Labels: cla-signed, approved

#2557 chore(gpu): remove nightly schedule now that ci is lighter
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#2560 refactor(gpu): creating CudaScalarDivisorFFI for storing decomposed scalars and their metadata
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_div.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
Labels: cla-signed, approved

#2564 chore(gpu): add checks on noise levels in debug mode
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/subtraction.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
Labels: cla-signed

#2573 fix: correct tuple element in izip! macro for 7 parameters
  tfhe/src/core_crypto/commons/utils.rs
Labels: cla-signed

#2575 chore: add missing into/from_raw_parts for SQCompression
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/shortint/list_compression/compressed_server_keys.rs
  tfhe/src/shortint/list_compression/server_keys.rs
Labels: cla-signed, approved

#2582 chore: missing from/into_raw_parts for noise squash comp priv key
  tfhe/src/integer/ciphertext/compressed_noise_squashed_ciphertext_list.rs
  tfhe/src/shortint/list_compression/private_key.rs
Labels: cla-signed, approved

#2581 fix: fix typo in word "implementor"
  tfhe/src/core_crypto/commons/generators/seeder.rs
Labels: cla-signed

#2586 chore: remove unused gitignore entry
  .gitignore
Labels: cla-signed, approved

#2589 refactor(shortint): cleanup decompression key
  tfhe/src/shortint/backward_compatibility/list_compression.rs
  tfhe/src/shortint/list_compression/compressed_server_keys.rs
  tfhe/src/shortint/list_compression/compression.rs
  tfhe/src/shortint/list_compression/server_keys.rs
Labels: cla-signed, approved

#2590 chore: enable unused_imports lint in doctests
  tfhe/docs/configuration/gpu-acceleration/compressing-ciphertexts.md
  tfhe/docs/configuration/gpu-acceleration/multi-gpu.md
  tfhe/docs/fhe-computation/operations/string-operations.md
  tfhe/src/core_crypto/entities/compressed_modulus_switched_lwe_ciphertext.rs
  tfhe/src/high_level_api/gpu_utils.rs
  tfhe/src/high_level_api/integers/oprf.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/strings/ascii/comp.rs
  tfhe/src/high_level_api/strings/ascii/contains.rs
  tfhe/src/high_level_api/strings/ascii/find.rs
  tfhe/src/high_level_api/strings/ascii/mod.rs
  tfhe/src/high_level_api/strings/ascii/no_pattern.rs
  tfhe/src/high_level_api/strings/ascii/replace.rs
  tfhe/src/high_level_api/strings/ascii/strip.rs
  tfhe/src/high_level_api/strings/ascii/trim.rs
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_div_mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/lib.rs
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/key_switching_key/mod.rs
Labels: cla-signed, approved

#2598 chore(gpu): correct pfail in readme
  README.md
Labels: cla-signed, approved

#2594 fix: correct typo in InvalidRangeError message
  tfhe/src/error.rs
Labels: cla-signed, approved

#2592 fix(gpu): fixes some wrong indexes used in cuda_set_device()
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#2577 feat(gpu): utility debug workflows in ci
  .github/actions/gpu_setup/action.yml
  .github/workflows/gpu_code_validation_tests.yml
  Makefile
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cu
  scripts/check_memory_errors.sh
Labels: cla-signed, approved

#2481 fix(api): add clear error for .min/.max called with ciphertext by val…
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/tests/cpu.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/signed/tests/mod.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/cpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
Labels: cla-signed

#2609 fix(gpu): fix inconsistent types
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#2588 fix: couple of typos in comment
  backends/tfhe-cuda-backend/cuda/include/zk/zk_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
Labels: cla-signed, approved

#2608 chore(gpu): add corner case test for mul
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_mul.rs
Labels: cla-signed, approved

#2611 chore(gpu): enhance scatter to check gpu count is ok
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
Labels: cla-signed, approved

#2614 fix(gpu): update soon deprecated version nvtx
  backends/tfhe-cuda-backend/cuda/src/utils/helper_profile.cuh
Labels: cla-signed, approved

#2618 chore: install & check gcc when needed
  .github/actions/gpu_setup/action.yml
Labels: cla-signed, approved

#2569 chore(gpu): change multi gpu logic
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cuh
Labels: cla-signed, approved

#2615 chore(gpu): fix warnings detection
  Makefile
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/polynomial/dot_product.cuh
Labels: cla-signed, approved
