Repository zama-ai/tfhe-rs, pull requests merged in 2025-02, with the labels that each got.

#2018 fix(gpu): fix noise/degree bug
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
Labels: cla-signed, approved

#2027 chore(gpu): refactor small scalar mul to keep track of degree and noise changes
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Labels: cla-signed, approved

#2019 fix(hlapi): ciphertext list decompress after safe_deser
  tfhe/src/core_crypto/gpu/entities/glwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed, approved

#2006 refactor!: Add invariant to GpuIndex
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
  tfhe/src/core_crypto/gpu/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_multi_bit_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_multi_bit_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/gpu/algorithms/test/noise_distribution/lwe_programmable_bootstrapping_noise.rs
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/core_crypto/gpu/slice.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/tests/gpu_selection.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/oprf.rs
  tfhe/src/integer/gpu/server_key/radix/tests_long_run/mod.rs
Labels: cla-signed, approved

#2028 Al/refactor scalar add
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_addition.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_addition.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
Labels: cla-signed, approved

#2029 chore(gpu): refactor shift and rotate to keep track of degree and noise changes
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_bitops.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cu
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
  tfhe/src/integer/gpu/server_key/radix/shift.rs
Labels: cla-signed, approved

#2020 style(c_api): use destructuring to avoid missing fields
  tfhe/src/c_api/shortint/parameters.rs
Labels: cla-signed, approved

#2034 chore(ci): always run should-run step against base commit
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/check_ci_files_change.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, ci, approved

#2039 fix(gpu): fix degree after shift/rotate
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
Labels: cla-signed, approved

#2042 fix(gpu): fix tuniform noise bound in 3_3 gpu multi-bit params
  tfhe/src/shortint/parameters/multi_bit/tuniform/p_fail_2_minus_64/ks_pbs_gpu.rs
Labels: cla-signed

#2045 chore(gpu): fix long run tests ranges
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
Labels: cla-signed, approved

#2050 test(core): make check a little less stringent on improved var for ms
  tfhe/src/core_crypto/algorithms/test/modulus_switch_noise_reduction.rs
Labels: cla-signed, approved

#2052 chore(ci): install github runner as ubuntu user for gpu workflows
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/make_release_cuda.yml
  ci/slab.toml
Labels: cla-signed, ci, approved

#2036 CudaCompressedList fixes
  tfhe/src/core_crypto/entities/glwe_ciphertext.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/core_crypto/gpu/vec.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/shortint/ciphertext/compressed_ciphertext_list.rs
Labels: cla-signed

#2051 chore(ci): remove pull_request_target for external contributions
  .github/actions/gpu_setup/action.yml
  .github/actions/hyperstack_setup/action.yml
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/check_actor_permissions.yml
  .github/workflows/check_ci_files_change.yml
  .github/workflows/check_external_pr.yml
  .github/workflows/ci_lint.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/data_pr_close.yml
  .github/workflows/gpu_4090_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/m1_tests.yml
Labels: cla-signed, ci, approved

#2041 fix(integer): rotations/shifts < 2 blocks
  tfhe/src/integer/server_key/radix_parallel/block_shift.rs
  tfhe/src/integer/server_key/radix_parallel/shift.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
Labels: cla-signed, approved

#2060 chore(core): use real modulus in test
  tfhe/src/core_crypto/algorithms/modulus_switch_noise_reduction.rs
  tfhe/src/core_crypto/algorithms/test/modulus_switch_noise_reduction.rs
Labels: cla-signed, approved

#2061 chore(ci): deduplicate parameters set to send to lattice estimator
  ci/lattice_estimator.sage
  tfhe/examples/utilities/params_to_file.rs
  tfhe/src/core_crypto/commons/parameters.rs
Labels: cla-signed, ci, approved

#2053 chore(gpu): refactor arithmetic scalar shift
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/abs.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_shift.rs
Labels: cla-signed, approved

#2002 feat(strings): make strings compatible with compact list
  tfhe/src/error.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/utils.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/ciphertext/utils.rs
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
  tfhe/src/lib.rs
  tfhe/src/strings/ciphertext.rs
  tfhe/src/strings/test_functions/mod.rs
  tfhe/src/strings/test_functions/test_compact.rs
Labels: cla-signed, approved

#2048 Al/refactor overflowing sub
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_addition.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/addition.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
Labels: cla-signed, approved

#2064 chore(gpu): remove unused variables
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
Labels: cla-signed, approved

#2062 Tm/strings in compressed
  tfhe/src/strings/ciphertext.rs
  tfhe/src/strings/test_functions/mod.rs
  tfhe/src/strings/test_functions/test_compression.rs
Labels: cla-signed, approved

#2046 chore: homogenize conformance parameters
  tfhe/src/core_crypto/entities/compressed_modulus_switched_glwe_ciphertext.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/compressed_modulus_switched_multi_bit_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/glwe_ciphertext.rs
  tfhe/src/core_crypto/entities/lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/entities/lwe_compact_public_key.rs
  tfhe/src/core_crypto/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/entities/lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/entities/seeded_ggsw_ciphertext_list.rs
  tfhe/src/core_crypto/entities/seeded_glwe_ciphertext.rs
  tfhe/src/core_crypto/entities/seeded_lwe_bootstrap_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_ciphertext.rs
  tfhe/src/core_crypto/entities/seeded_lwe_compact_public_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_keyswitch_key.rs
  tfhe/src/core_crypto/entities/seeded_lwe_packing_keyswitch_key.rs
  tfhe/src/core_crypto/fft_impl/fft64/crypto/bootstrap.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/integer/compression_keys.rs
  tfhe/src/shortint/ciphertext/compressed_modulus_switched_ciphertext.rs
  tfhe/src/shortint/ciphertext/zk.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/list_compression/compressed_server_keys.rs
  tfhe/src/shortint/list_compression/mod.rs
  tfhe/src/shortint/list_compression/server_keys.rs
  tfhe/src/shortint/parameters/mod.rs
  tfhe/src/shortint/parameters/multi_bit/mod.rs
  tfhe/src/shortint/public_key/compact.rs
  tfhe/src/shortint/server_key/compressed.rs
  tfhe/src/shortint/server_key/mod.rs
  tfhe/src/shortint/server_key/modulus_switch_noise_reduction.rs
Labels: cla-signed, approved

#2066 fix: rotations of 1 blocks of 4_4
  tfhe/src/integer/server_key/radix_parallel/shift.rs
Labels: cla-signed, approved

#2067 fix(gpu): enable larger number of samples in the keyswitch
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cuh
Labels: cla-signed, approved

#2073 chore(ci): enable throughput benchmarks for zk-pok
  .github/workflows/benchmark_tfhe_zk_pok.yml
  tfhe/benches/integer/zk_pke.rs
Labels: cla-signed, ci, approved

#2068 fix(gpu): enable large number of samples in pbs tbc
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
Labels: cla-signed, approved

#2077 chore(ci): fix cuda release workflow to have rust re-installed for cargo
  .github/workflows/make_release_cuda.yml
Labels: cla-signed, approved

#2078 chore(ci): fix packaging job to also have exported env vars
  .github/workflows/make_release_cuda.yml
Labels: cla-signed

#2080 chore(ci): fix web packages publish with provenance
  .github/workflows/make_release.yml
Labels: cla-signed, approved

#2071 fix(gpu): Remove unnecessary and incorrect bound check for decompression
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
Labels: cla-signed, approved

#2074 feat(gpu): enable if then else for boolean ciphertexts in hlapi
  tfhe/src/high_level_api/booleans/base.rs
Labels: cla-signed, approved

#2085 feat(gpu): enable signed division in high level api
  tfhe/src/high_level_api/integers/signed/ops.rs
Labels: cla-signed, approved

#2090 chore(ci): fix release workflow for tfhe-versionable
  .github/workflows/make_release_tfhe_versionable.yml
Labels: cla-signed, ci, approved

#2095 fix(gpu): fix wrong assert in division
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
Labels: cla-signed, approved

#2088 chore: update toolchain
  Cargo.toml
  tfhe/docs/fhe-computation/advanced-features/overflow_operations.md
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  toolchain.txt
Labels: cla-signed, approved

#2096 fix(gpu): fix wrong number of blocks used in cast
  tfhe/src/integer/gpu/server_key/radix/mod.rs
Labels: cla-signed, approved

#2101 chore(gpu): update backend readme
  backends/tfhe-cuda-backend/README.md
Labels: cla-signed, approved

#2091 chore(ci): add should-run to tfhe-fft and tfhe-ntt tests
  .github/workflows/cargo_test_fft.yml
  .github/workflows/cargo_test_ntt.yml
Labels: cla-signed, ci, approved

#2102 test: make the bound on the base variance check a bit looser
  tfhe/src/core_crypto/algorithms/test/modulus_switch_noise_reduction.rs
Labels: cla-signed, approved

#2105 chore(ci): update cpu aws ami and install git-lfs
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  ci/slab.toml
Labels: cla-signed, ci, approved

#2082 chore(ci): add contributing instructions
  CONTRIBUTING.md
  tasks/src/check_tfhe_docs_are_tested.rs
Labels: cla-signed

#2089 feat(gpu): refactor the sample extract entry point
  backends/tfhe-cuda-backend/cuda/include/ciphertext.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/algorithms/glwe_sample_extraction.rs
  tfhe/src/core_crypto/gpu/algorithms/test/glwe_sample_extraction.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#2107 chore(ci): fix workflow concurrency condition
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
  .github/workflows/benchmark_tfhe_fft.yml
  .github/workflows/benchmark_tfhe_ntt.yml
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/code_coverage.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/data_pr_close.yml
  .github/workflows/gpu_4090_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/integer_long_run_tests.yml
  .github/workflows/m1_tests.yml
Labels: cla-signed, ci, approved

#2110 chore: link CONTRIBUTING.md in the documentation
  tfhe/docs/README.md
  tfhe/docs/SUMMARY.md
  tfhe/docs/dev/contributing.md
Labels: cla-signed, approved

#2113 docs(js): update JS example
  tfhe/docs/integration/js_on_wasm_api.md
Labels: cla-signed, approved

#2115 chore(gpu): increase 4090 test timeout
  .github/workflows/gpu_4090_tests.yml
Labels: cla-signed, approved

#2106 chore(gpu): replace asserts with panic
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/fast_packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
Labels: cla-signed, approved

#2109 fix(cpu): fix corner case when estimating the num blocks required
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/integer/server_key/radix_parallel/count_zeros_ones.rs
Labels: cla-signed, approved

#2104 fix(gpu): fix scalar comparisons with 1 block
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/integers/signed/encrypt.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_comparison.rs
Labels: cla-signed, approved

#2116 docs(js): update JS example
  tfhe/docs/integration/js_on_wasm_api.md
Labels: cla-signed, approved

#2120 docs: add link in the README
  README.md
Labels: cla-signed, approved

#2111 fix(c-api): add missing casts
  tfhe/src/c_api/high_level_api/integers.rs
  tfhe/src/c_api/high_level_api/utils.rs
Labels: cla-signed, approved

#2122 docs: add link in the README
  README.md
Labels: cla-signed, approved

#2054 Al/refactor comparisons
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cu
  backends/tfhe-cuda-backend/cuda/src/integer/negation.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/subtraction.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
Labels: cla-signed, approved

#2119 chore(ci): switch environment and add fallback for gpu profiles
  ci/slab.toml
Labels: cla-signed, ci, approved

#2123 docs: rename to README as its needed for link to work
  tfhe/docs/README.md
  tfhe/docs/SUMMARY.md
  tfhe/docs/getting_started/README.md
Labels: cla-signed, approved

#2127 chore(gpu): fix typo in doc
  tfhe/docs/getting_started/benchmarks/gpu/README.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
Labels: cla-signed, approved

#2075 fix(gpu): enforce tighter bounds on compression output
  backends/tfhe-cuda-backend/cuda/include/integer/compression/compression_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  tfhe/src/integer/gpu/ciphertext/compressed_ciphertext_list.rs
  tfhe/src/integer/gpu/list_compression/server_keys.rs
Labels: cla-signed, approved

#2103 chore(gpu): plug in signed gpu tests in the hl api
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/tests.rs
  tfhe/src/high_level_api/integers/signed/tests/cpu.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/signed/tests/mod.rs
  tfhe/src/high_level_api/integers/unsigned/mod.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/tests/mod.rs
  tfhe/src/integer/gpu/server_key/radix/rotate.rs
Labels: cla-signed, approved

#2129 feat(gpu): add a function to set a CudaLweList to 0
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/vec.rs
Labels: cla-signed, approved
