Repository zama-ai/tfhe-rs, pull requests merged in 2025-03, with the labels that each got.

#1823 feat(gpu): Implement fft128 in cuda backend
  _typos.toml
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/fft/fft128.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/fft128/f128.cuh
  backends/tfhe-cuda-backend/cuda/src/fft128/fft128.cu
  backends/tfhe-cuda-backend/cuda/src/fft128/fft128.cuh
  backends/tfhe-cuda-backend/cuda/src/fft128/twiddles.cu
  backends/tfhe-cuda-backend/cuda/src/fft128/twiddles.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  backends/tfhe-cuda-backend/wrapper.h
  tfhe/src/core_crypto/gpu/algorithms/test/fft.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#2132 chore(ci): fallback on permanent h100 instance on shortage
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
Labels: cla-signed, ci

#2130 refactor(gpu): use hexes to initialize twiddles for 64 bit fft
  _typos.toml
  backends/tfhe-cuda-backend/cuda/src/fft/twiddles.cu
Labels: cla-signed

#2117 fix: fix the atomic pattern used to cast in trivium and a test in shortint
  apps/trivium/src/trans_ciphering/mod.rs
  tfhe/src/shortint/key_switching_key/test.rs
Labels: cla-signed

#2114 Al/refactor mul and scalar mul to track degree and noise level
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/cmux.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_mul.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cu
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_shifts.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/shift_and_rotate.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/ciphertext/info.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_mul.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
Labels: cla-signed, approved

#2131 refactor(gpu): refactor double2 operators to use cuda intrinsics
  backends/tfhe-cuda-backend/cuda/src/types/complex/operations.cuh
Labels: cla-signed, approved

#2150 chore(ci): disable dylint until rustup issue is fixed
  Makefile
Labels: cla-signed, approved

#2151 chore(ci): disable dylint until rustup issue is fixed
  Makefile
Labels: cla-signed, approved

#2138 fix: fix the atomic pattern used to cast in trivium and a test in sho…
  apps/trivium/src/trans_ciphering/mod.rs
  tfhe/src/shortint/key_switching_key/test.rs
Labels: cla-signed, approved

#2141 [backport] chore(bench): run core_crypto benchmarks on all parameters p-fail
  .github/workflows/benchmark_core_crypto.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  Makefile
  tfhe/Cargo.toml
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/ks_pbs_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/benches/utilities.rs
  tfhe/src/core_crypto/commons/parameters.rs
  tfhe/src/shortint/engine/server_side.rs
  tfhe/src/shortint/keycache.rs
  tfhe/src/shortint/parameters/aliases.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed

#2140 fix(shortint): make noise_level field of Ciphertext private again
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
  tfhe/src/integer/gpu/ciphertext/mod.rs
  tfhe/src/integer/server_key/crt/scalar_mul_crt.rs
  tfhe/src/integer/server_key/crt_parallel/scalar_mul_crt.rs
  tfhe/src/integer/server_key/radix_parallel/block_shift.rs
  tfhe/src/integer/server_key/radix_parallel/mod.rs
  tfhe/src/integer/server_key/radix_parallel/mul.rs
  tfhe/src/integer/server_key/radix_parallel/tests_cases_unsigned.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_vector_find.rs
  tfhe/src/shortint/ciphertext/compact_list.rs
  tfhe/src/shortint/ciphertext/compressed.rs
  tfhe/src/shortint/ciphertext/standard.rs
  tfhe/src/shortint/oprf.rs
  tfhe/src/shortint/server_key/tests/modulus_switch_compression.rs
Labels: cla-signed, approved

#2142 chore(gpu): refactor full propagation to track noise / degree
  backends/tfhe-cuda-backend/cuda/include/integer/integer.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_sub.rs
Labels: cla-signed

#2128 fix: BlockDecomposer
  tfhe/src/integer/block_decomposition.rs
  tfhe/src/integer/server_key/radix/scalar_sub.rs
Labels: cla-signed, approved

#2156 chore(ci): fix permanent instance selection condition
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_erc20_common.yml
  .github/workflows/benchmark_gpu_integer_common.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_full_h100_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
Labels: cla-signed, ci, approved

#2152 docs: change svg benchmark tables appearance
  tfhe/docs/_static/cpu_gpu_integer_benchmark_fheuint64_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_plaintext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_plaintext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_plaintext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_plaintext.svg
  tfhe/docs/getting_started/benchmarks/README.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
Labels: documentation, cla-signed

#2157 chore(ci): add hourly cost for sxm5 vms
  ci/ec2_products_cost.json
Labels: cla-signed, approved

#2112 chore(ci): use new heuristic for throughput benchmarks
  Makefile
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/glwe_packing_compression.rs
  tfhe/benches/integer/oprf.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/benches/integer/zk_pke.rs
  tfhe/benches/utilities.rs
  tfhe/src/integer/gpu/ciphertext/boolean_value.rs
Labels: cla-signed, ci

#2158 [backport] docs: change svg benchmark tables appearance
  tfhe/docs/_static/cpu_gpu_integer_benchmark_fheuint64_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m128_plaintext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/cpu_integer_benchmark_tuniform_2m64_plaintext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x1_multi_bit_tuniform_2m64_plaintext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_ciphertext.svg
  tfhe/docs/_static/gpu_integer_benchmark_h100x2_multi_bit_tuniform_2m64_plaintext.svg
  tfhe/docs/getting_started/benchmarks/README.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/gpu/gpu_programmable_bootstrapping.md
Labels: documentation, cla-signed, approved

#2162 chore: pre-generate keyswitching keys for shortint tests
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/src/keycache/mod.rs
Labels: cla-signed, approved

#2161 docs: change svg benchmark tables appearance for pbs
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m128.svg
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m40.svg
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m64.svg
  tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m40.svg
  tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m64.svg
Labels: documentation, cla-signed, approved

#2163 chore: pre-generate keyswitching keys for shortint tests
  tfhe/examples/utilities/generates_test_keys.rs
  tfhe/src/keycache/mod.rs
Labels: cla-signed, approved

#2165 docs: change svg benchmark tables appearance for pbs
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m128.svg
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m40.svg
  tfhe/docs/_static/cpu_pbs_benchmark_tuniform_2m64.svg
  tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m40.svg
  tfhe/docs/_static/gpu_pbs_benchmark_tuniform_2m64.svg
Labels: documentation, cla-signed, approved

#2139 fix(gpu): fix ilog2 result when input is 0
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cu
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cu
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/ilog2.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/gpu/server_key/radix/vector_find.rs
Labels: cla-signed

#2167 chore(ci): add pull-request url to slack notification message
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, ci, approved

#2160 chore(bench): add pbs-stats required feature
  tfhe/Cargo.toml
Labels: cla-signed, approved

#2170 fix(gpu): fix scalar eq bug
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
Labels: cla-signed, approved

#2171 Al/fix bug in mul
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#2133 Tm/fix signed decomposer
  tfhe/src/integer/block_decomposition.rs
  tfhe/src/integer/encryption.rs
  tfhe/src/integer/gpu/server_key/radix/mod.rs
  tfhe/src/integer/server_key/radix/tests.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_comparison.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
Labels: cla-signed, approved

#2175 chore(ci): install dependencies as standalone job
  .github/workflows/benchmark_gpu_common.yml
Labels: cla-signed, ci, approved

#2173 fix(gpu): fix logic of host_compare_with_zero_equality
  backends/tfhe-cuda-backend/cuda/src/integer/comparison.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
Labels: cla-signed

#2178 chore: remove trivium from main workspace
  Cargo.toml
  Makefile
  apps/trivium/Cargo.toml
Labels: cla-signed, approved

#2172 fix: a shortint docstring had values not matching the explanation
  tfhe/src/shortint/server_key/mul.rs
Labels: cla-signed, approved

#2182 chore(ci): pin changed files action to a sha1 corresponding to a tag
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/benchmark_tfhe_zk_pok.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  .github/workflows/cargo_test_fft.yml
  .github/workflows/cargo_test_ntt.yml
  .github/workflows/code_coverage.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
Labels: cla-signed, approved

#2180 fix(gpu): fix bug introduced when reworking host_compare_with_zero
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/scalar_comparison.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
Labels: cla-signed, approved

#2188 fix(gpu): fix corner case in sum ctxt
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
Labels: cla-signed, approved

#2189 chore(gpu): reduce testing time after parameter update
  tfhe/examples/utilities/shortint_key_sizes.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_signed/test_scalar_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/mod.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_comparison.rs
  tfhe/src/integer/gpu/server_key/radix/tests_unsigned/test_scalar_comparison.rs
  tfhe/src/shortint/parameters/test_params.rs
Labels: cla-signed, approved

#2191 chore(gpu): add an alias for GPU compression parameters
  tfhe/docs/configuration/run_on_gpu.md
  tfhe/src/shortint/parameters/aliases.rs
Labels: cla-signed, approved

#2185 chore(gpu): supress warnings in pcc_gpu
  backends/tfhe-cuda-backend/cuda/include/device.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_multibit_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap_multibit.h
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/integer/div_rem.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/bootstrapping_key.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_amortized.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_tbc_multibit.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
Labels: cla-signed, approved

#2181 feat(integer): add scalar cmux
  tfhe/src/integer/server_key/radix_parallel/cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_cmux.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_cmux.rs
Labels: cla-signed, approved

#2146 feat: add trivial enc/dec for strings
  tfhe/src/high_level_api/strings/ascii/mod.rs
  tfhe/src/strings/ciphertext.rs
  tfhe/src/strings/client_key.rs
  tfhe/src/strings/server_key/mod.rs
Labels: cla-signed, approved

#2192 refactor(gpu): remove lwe_input_indexes, lwe_output_indexes and lut_vector_indexes for pbs128
  backends/tfhe-cuda-backend/cuda/include/pbs/programmable_bootstrap.h
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/benches/core_crypto/pbs128_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_programmable_bootstrapping.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_programmable_bootstrapping_128.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#2201 chore(gpu): relax too strict condition in copy slice
  backends/tfhe-cuda-backend/cuda/src/integer/radix_ciphertext.cuh
Labels: cla-signed, approved

#2205 chore(gpu): detect if we are in first or last iter with template argument for split kernel multi-bit PBS
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_multibit.cuh
Labels: cla-signed, approved

#2207 Al/template arg iter pbs128
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cuh
Labels: cla-signed, approved

#2209 chore(gpu): modify erc20 throughput bench for better multi-gpu performance
  tfhe/benches/high_level_api/erc20.rs
Labels: cla-signed, approved

#2211 chore: update tfhe-fft and tfhe-ntt minor version
  tfhe-fft/Cargo.toml
  tfhe-ntt/Cargo.toml
  tfhe/Cargo.toml
Labels: cla-signed, dependencies, approved

#2216 chore(gpu): fix integer throughput bench
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#2214 chore(gpu): reduce test threads for multi-gpu tests
  .github/workflows/gpu_full_multi_gpu_tests.yml
Labels: cla-signed, approved

#2215 fix(tests): re-enable backward tests that were skipped
  tests/Cargo.toml
  tests/backward_compatibility_tests.rs
Labels: cla-signed, approved

#2213 feat(tfhe-ntt): Add custom root-of-unity for Solinas Prime
  tfhe-ntt/src/prime64.rs
  tfhe-ntt/src/roots.rs
Labels: cla-signed, approved

#2224 fix(gpu): fix max shared memory bug for CG PBS
  backends/tfhe-cuda-backend/cuda/src/device.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_classic.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_cg_multibit.cuh
Labels: cla-signed, approved

#2183 chore(bench): implement throughput benchmarks on core_crypto layer
  .github/workflows/benchmark_gpu.yml
  .github/workflows/benchmark_gpu_common.yml
  .github/workflows/benchmark_gpu_core_crypto.yml
  .github/workflows/benchmark_gpu_weekly.yml
  Makefile
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/benches/core_crypto/ks_pbs_bench.rs
  tfhe/benches/core_crypto/pbs128_bench.rs
  tfhe/benches/core_crypto/pbs_bench.rs
  tfhe/benches/integer/bench.rs
  tfhe/benches/integer/glwe_packing_compression.rs
  tfhe/benches/integer/oprf.rs
  tfhe/benches/integer/signed_bench.rs
  tfhe/benches/integer/zk_pke.rs
  tfhe/benches/utilities.rs
Labels: cla-signed

#2210 feat: add clear - ciphertex
  Makefile
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/integer/server_key/radix/neg.rs
  tfhe/src/integer/server_key/radix/scalar_add.rs
  tfhe/src/integer/server_key/radix_parallel/scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_signed/test_scalar_sub.rs
  tfhe/src/integer/server_key/radix_parallel/tests_unsigned/test_scalar_sub.rs
Labels: cla-signed, approved
