Repository zama-ai/tfhe-rs, pull requests merged in 2025-05, with the labels that each got.

#2304 docs(all): add hardware description in the summary bench page
  tfhe/docs/getting_started/benchmarks/README.md
  tfhe/docs/getting_started/benchmarks/cpu/README.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
Labels: cla-signed, approved

#2303 feat(gpu): add necessary entry points for 128 bit compression
  backends/tfhe-cuda-backend/build.rs
  backends/tfhe-cuda-backend/cuda/include/ciphertext.h
  backends/tfhe-cuda-backend/cuda/include/integer/integer_utilities.h
  backends/tfhe-cuda-backend/cuda/include/keyswitch/keyswitch.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/keyswitch.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/integer/compression/compression.cuh
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/include/setup_and_teardown.h
  backends/tfhe-cuda-backend/src/bindings.rs
  backends/tfhe-cuda-backend/wrapper.h
  tfhe/benches/core_crypto/ks_bench.rs
  tfhe/src/core_crypto/gpu/algorithms/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/gpu/algorithms/test/lwe_packing_keyswitch.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#2301 chore(gpu): write swap bench
  .github/workflows/benchmark_dex.yml
  .github/workflows/benchmark_gpu_dex.yml
  .github/workflows/benchmark_gpu_dex_common.yml
  .github/workflows/benchmark_gpu_dex_weekly.yml
  Makefile
  tfhe/Cargo.toml
  tfhe/benches/high_level_api/dex.rs
  tfhe/benches/high_level_api/erc20.rs
  tfhe/benches/utilities.rs
Labels: cla-signed, approved

#2311 feat(shortint): add CompressedAtomicPatternServerKey
  tfhe/examples/utilities/shortint_key_sizes.rs
  tfhe/src/core_crypto/algorithms/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/algorithms/test/lwe_keyswitch_key_generation.rs
  tfhe/src/core_crypto/entities/seeded_lwe_keyswitch_key.rs
  tfhe/src/integer/gpu/server_key/mod.rs
  tfhe/src/integer/server_key/mod.rs
  tfhe/src/shortint/atomic_pattern/compressed/ks32.rs
  tfhe/src/shortint/atomic_pattern/compressed/mod.rs
  tfhe/src/shortint/atomic_pattern/compressed/standard.rs
  tfhe/src/shortint/atomic_pattern/mod.rs
  tfhe/src/shortint/atomic_pattern/standard.rs
  tfhe/src/shortint/backward_compatibility/atomic_pattern.rs
  tfhe/src/shortint/backward_compatibility/server_key/mod.rs
  tfhe/src/shortint/backward_compatibility/server_key/modulus_switch_noise_reduction.rs
  tfhe/src/shortint/engine/server_side.rs
  tfhe/src/shortint/key_switching_key/mod.rs
  tfhe/src/shortint/server_key/compressed.rs
Labels: cla-signed, approved

#2030 feat(gpu): add circulant matrix for one vs many poly product
  backends/tfhe-cuda-backend/cuda/CMakeLists.txt
  backends/tfhe-cuda-backend/cuda/include/linear_algebra.h
  backends/tfhe-cuda-backend/cuda/src/crypto/packing_keyswitch.cuh
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cu
  backends/tfhe-cuda-backend/cuda/src/linearalgebra/multiplication.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/dot_product.cuh
  backends/tfhe-cuda-backend/cuda/src/polynomial/polynomial_math.cuh
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/algorithms/glwe_linear_algebra.rs
  tfhe/src/core_crypto/gpu/algorithms/mod.rs
  tfhe/src/core_crypto/gpu/algorithms/test/glwe_dot_product_with_clear.rs
  tfhe/src/core_crypto/gpu/algorithms/test/mod.rs
Labels: cla-signed, approved

#2313 chore(ci): upgrade actionlint to v1.7.7
  .github/workflows/ci_lint.yml
Labels: cla-signed, ci, approved, backport

#2307 docs(all): add hardware description in the summary bench page
  tfhe/docs/getting_started/benchmarks/README.md
  tfhe/docs/getting_started/benchmarks/cpu/README.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_integer_operations.md
  tfhe/docs/getting_started/benchmarks/cpu/cpu_programmable_bootstrapping.md
Labels: cla-signed

#2310 refactor(zk): run pke_v2 verification inside dedicated thread pools
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
Labels: cla-signed, approved

#2314 chore(bench): update pbs count parsing in dex benchmark
  .github/workflows/benchmark_dex.yml
  .github/workflows/benchmark_gpu_dex.yml
Labels: cla-signed

#2319 fix(shortint): store correct ap in ciphertext during encryption
  tfhe/src/core_crypto/commons/parameters.rs
  tfhe/src/shortint/client_key/mod.rs
  tfhe/src/shortint/engine/client_side.rs
  tfhe/src/shortint/parameters/mod.rs
Labels: cla-signed, approved

#2318 chore: fix Makefile to specify toolchain for cargo xtask
  Makefile
Labels: m1_test, cla-signed

#2322 chore(ci): remove misleading continue-on-error
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_dex.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_gpu_common.yml
  .github/workflows/benchmark_integer.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_signed_integer.yml
Labels: cla-signed, ci, approved

#2324 chore(ci): avoid double-quote on dry-run variable
  .github/workflows/make_release.yml
  .github/workflows/make_release_cuda.yml
  .github/workflows/make_release_tfhe_csprng.yml
  .github/workflows/make_release_tfhe_fft.yml
  .github/workflows/make_release_tfhe_ntt.yml
  .github/workflows/make_release_zk_pok.yml
Labels: cla-signed, ci, approved

#2325 chore(ci): ensure minimal permission for github default token
  .github/workflows/aws_tfhe_backward_compat_tests.yml
  .github/workflows/aws_tfhe_fast_tests.yml
  .github/workflows/aws_tfhe_integer_tests.yml
  .github/workflows/aws_tfhe_signed_integer_tests.yml
  .github/workflows/aws_tfhe_tests.yml
  .github/workflows/aws_tfhe_wasm_tests.yml
  .github/workflows/benchmark_gpu_4090.yml
  .github/workflows/cargo_build.yml
  .github/workflows/cargo_build_tfhe_fft.yml
  .github/workflows/cargo_build_tfhe_ntt.yml
  .github/workflows/cargo_test_fft.yml
  .github/workflows/cargo_test_ntt.yml
  .github/workflows/check_commit.yml
  .github/workflows/ci_lint.yml
  .github/workflows/code_coverage.yml
  .github/workflows/csprng_randomness_tests.yml
  .github/workflows/gpu_4090_tests.yml
  .github/workflows/gpu_fast_h100_tests.yml
  .github/workflows/gpu_fast_tests.yml
  .github/workflows/gpu_full_multi_gpu_tests.yml
  .github/workflows/gpu_integer_long_run_tests.yml
  .github/workflows/gpu_pcc.yml
  .github/workflows/gpu_signed_integer_classic_tests.yml
  .github/workflows/gpu_signed_integer_h100_tests.yml
  .github/workflows/gpu_signed_integer_tests.yml
  .github/workflows/gpu_unsigned_integer_classic_tests.yml
  .github/workflows/gpu_unsigned_integer_h100_tests.yml
  .github/workflows/gpu_unsigned_integer_tests.yml
  .github/workflows/m1_tests.yml
Labels: cla-signed, ci, approved

#2315 chore(gpu): parallelize dex bench
  tfhe-benchmark/benches/high_level_api/dex.rs
Labels: cla-signed

#2326 chore: update clap dependency version to 4.5.30
  tasks/Cargo.toml
  tfhe-benchmark/Cargo.toml
  tfhe-csprng/Cargo.toml
  tfhe/Cargo.toml
  utils/param_dedup/Cargo.toml
Labels: cla-signed, approved

#2327 chore(gpu): add hardware types for gpu bench
  .github/workflows/benchmark_gpu.yml
  .github/workflows/benchmark_gpu_dex.yml
  .github/workflows/benchmark_gpu_erc20.yml
Labels: cla-signed, approved

#2321 chore(bench): store object measurements results in tfhe-benchmark
  .github/workflows/benchmark_boolean.yml
  .github/workflows/benchmark_dex.yml
  .github/workflows/benchmark_erc20.yml
  .github/workflows/benchmark_shortint.yml
  .github/workflows/benchmark_wasm_client.yml
  .github/workflows/benchmark_zk_pke.yml
  ci/benchmark_parser.py
  ci/webdriver.py
  tfhe-benchmark/src/bin/boolean_key_sizes.rs
  tfhe-benchmark/src/bin/hlapi_compact_pk_ct_sizes.rs
  tfhe-benchmark/src/bin/shortint_key_sizes.rs
  tfhe-benchmark/src/bin/wasm_benchmarks_parser.rs
Labels: cla-signed, ci, approved

#2245 feat(gpu): add support for a custom device selection on multi-gpu mode
  backends/tfhe-cuda-backend/cuda/include/helper_multi_gpu.h
  backends/tfhe-cuda-backend/cuda/src/utils/helper_multi_gpu.cu
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/tests/test_keyswitch.cpp
  backends/tfhe-cuda-backend/src/cuda_bind.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/array/gpu/booleans.rs
  tfhe/src/high_level_api/array/gpu/integers.rs
  tfhe/src/high_level_api/booleans/base.rs
  tfhe/src/high_level_api/booleans/encrypt.rs
  tfhe/src/high_level_api/booleans/oprf.rs
  tfhe/src/high_level_api/compressed_ciphertext_list.rs
  tfhe/src/high_level_api/global_state.rs
  tfhe/src/high_level_api/integers/oprf.rs
  tfhe/src/high_level_api/integers/signed/base.rs
  tfhe/src/high_level_api/integers/signed/encrypt.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/overflowing_ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/encrypt.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/overflowing_ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/tests/gpu_selection.rs
Labels: cla-signed

#2336 chore(ci): fix env var usage in make recipe for gpu benchmarks
  .github/workflows/benchmark_gpu_common.yml
Labels: cla-signed, ci, approved

#2329 chore(zk): check that crs group element at index n is 0
  tfhe-zk-pok/src/curve_api.rs
  tfhe-zk-pok/src/proofs/mod.rs
  tfhe-zk-pok/src/proofs/pke.rs
  tfhe-zk-pok/src/proofs/pke_v2.rs
  tfhe-zk-pok/src/serialization.rs
Labels: cla-signed, approved

#2309 feat(gpu): add memory tracking functions for add/sub and scalar add/sub
  tfhe/src/high_level_api/gpu_utils.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_add.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_sub.rs
  tfhe/src/integer/gpu/server_key/radix/sub.rs
Labels: cla-signed

#2337 fix(bench): compilation error without the internal-keycache feature
  tfhe-benchmark/src/params.rs
  tfhe-benchmark/src/utilities.rs
Labels: cla-signed, approved

#2348 fix(doc): uniformized readme file names - 1.2
  backends/tfhe-hpu-backend/README.md
  backends/tfhe-hpu-backend/config_store/u55c_gf64/README.md
  backends/tfhe-hpu-backend/config_store/v80/README.md
  mockups/tfhe-hpu-mockup/README.md
  tasks/src/check_tfhe_docs_are_tested.rs
  tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
Labels: cla-signed, approved

#2350 fix(doc): uniformized readme file names - main
  backends/tfhe-hpu-backend/README.md
  backends/tfhe-hpu-backend/config_store/u55c_gf64/README.md
  backends/tfhe-hpu-backend/config_store/v80/README.md
  mockups/tfhe-hpu-mockup/README.md
  tasks/src/check_tfhe_docs_are_tested.rs
  tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
Labels: cla-signed, approved

#2353 chore(hpu): fix Cargo.toml for release
  backends/tfhe-hpu-backend/Cargo.toml
Labels: cla-signed, approved

#2351 chore: use wrapping div in long_run
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_random_op_sequence.rs
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
Labels: cla-signed, approved

#2342 chore(bench): add suitable heuristic for zk throughput
  tfhe-benchmark/benches/integer/zk_pke.rs
Labels: cla-signed, ci, approved

#2343 feat(gpu): add memory tracking functions for bitops
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/bitwise_op.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_bitwise_op.rs
Labels: cla-signed, approved

#2357 fix(gpu): fix pbs and ks benchmark
  tfhe-benchmark/benches/core_crypto/ks_bench.rs
  tfhe-benchmark/src/params.rs
Labels: cla-signed, approved

#2359 fix(doc): hpu example was not compiling
  tfhe/docs/configuration/hpu_acceleration/run_on_hpu.md
Labels: cla-signed, approved

#2356 chore: some more CODEOWNERS
  CODEOWNERS
Labels: cla-signed, approved

#2360 chore: fix typos
  .github/workflows/gpu_pcc.yml
  backends/tfhe-cuda-backend/cuda/src/integer/integer.cuh
Labels: cla-signed, approved

#2363 fix(gpu): fix degrees after abs
  tfhe/src/integer/gpu/mod.rs
Labels: cla-signed, approved

#2358 fix(gpu): allow to build with hpu feature enabled
  .github/workflows/gpu_pcc.yml
  Makefile
  tfhe/src/high_level_api/booleans/inner.rs
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/base.rs
  tfhe/src/high_level_api/integers/unsigned/inner.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
Labels: cla-signed, approved

#2331 fix(gpu): add indexes to modulus switch noise reduction
  backends/tfhe-cuda-backend/cuda/include/ciphertext.h
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/src/crypto/ciphertext.cu
  backends/tfhe-cuda-backend/cuda/src/crypto/torus.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap.cuh
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic.cu
  backends/tfhe-cuda-backend/cuda/src/pbs/programmable_bootstrap_classic_128.cu
  backends/tfhe-cuda-backend/src/bindings.rs
  tfhe/src/core_crypto/gpu/algorithms/test/modulus_switch_noise_reduction.rs
  tfhe/src/core_crypto/gpu/mod.rs
Labels: cla-signed, approved

#2366 chore(ci): handle multi directories for parameters records
  ci/benchmark_parser.py
Labels: cla-signed, ci, approved

#2367 fix(bench): add missing internal keycache feature
  tfhe-benchmark/Cargo.toml
Labels: cla-signed, approved

#2364 fix(gpu): fix the internal benchmark
  backends/tfhe-cuda-backend/cuda/include/pbs/pbs_utilities.h
  backends/tfhe-cuda-backend/cuda/tests_and_benchmarks/benchmarks/benchmark_pbs.cpp
Labels: cla-signed, approved

#2276 feat(gpu): add support for GPU-accelerated expand on the HL Api
  Makefile
  tfhe-benchmark/benches/integer/zk_pke.rs
  tfhe/docs/configuration/gpu_acceleration/zk-pok.md
  tfhe/src/core_crypto/gpu/entities/lwe_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_compact_ciphertext_list.rs
  tfhe/src/core_crypto/gpu/entities/lwe_keyswitch_key.rs
  tfhe/src/core_crypto/gpu/mod.rs
  tfhe/src/high_level_api/backward_compatibility/compact_list.rs
  tfhe/src/high_level_api/compact_list.rs
  tfhe/src/high_level_api/keys/inner.rs
  tfhe/src/high_level_api/keys/server.rs
  tfhe/src/high_level_api/tests/tags_on_entities.rs
  tfhe/src/integer/ciphertext/compact_list.rs
  tfhe/src/integer/gpu/ciphertext/compact_list.rs
  tfhe/src/integer/gpu/key_switching_key/mod.rs
  tfhe/src/integer/gpu/zk/mod.rs
  tfhe/src/test_user_docs.rs
Labels: cla-signed, approved

#2365 feat(gpu): add memory tracking functions for comparisons
  tfhe/src/high_level_api/integers/signed/ops.rs
  tfhe/src/high_level_api/integers/signed/scalar_ops.rs
  tfhe/src/high_level_api/integers/signed/tests/gpu.rs
  tfhe/src/high_level_api/integers/unsigned/ops.rs
  tfhe/src/high_level_api/integers/unsigned/scalar_ops.rs
  tfhe/src/high_level_api/integers/unsigned/tests/gpu.rs
  tfhe/src/high_level_api/prelude.rs
  tfhe/src/high_level_api/traits.rs
  tfhe/src/integer/gpu/mod.rs
  tfhe/src/integer/gpu/server_key/radix/comparison.rs
  tfhe/src/integer/gpu/server_key/radix/scalar_comparison.rs
Labels: cla-signed

#2373 chore(gpu): fix oom error in ci
  .github/workflows/gpu_full_multi_gpu_tests.yml
  Makefile
  scripts/integer-tests.sh
Labels: cla-signed, approved

#2375 Al/fix long run div
  tfhe/src/integer/server_key/radix_parallel/tests_long_run/test_signed_random_op_sequence.rs
Labels: cla-signed, approved

#2341 Add dex throughput benchmarks
  tfhe-benchmark/benches/high_level_api/dex.rs
Labels: cla-signed, approved

#2371 fix(gpu): build with hpu and zk features
  Makefile
  tfhe/src/high_level_api/compact_list.rs
Labels: cla-signed, approved
